= Codename _Phoenix_

Reborn from ashes.

== Human needs / Menschliche Bedürfnisse / Ľudské potreby

by / nach / podľa Manfred Max-Neef, Marshall B. Rosenberg and me

---

The needs is *the only reason*, why I'm feeling the way I'm feeling. Not the actions of other people, or the state of the environment. These are only the stimulus for my feelings.

---

What is a need? / Was ist ein Bedürfnis?
* Life seeking expression within oneself.
* Manifestation of the divine energy in each living phenomenon.

---

* *need [bold face] / das Bedürfniss [dick geschrieben] / potreba [tučne zvýraznené]*
* _not a need - feedback / kein Bedürfniss - eine Rückmeldung / nie je potreba - spätná väzba_ - Only as a feedback that the needs were or were not fulfilled. / Nur als Rückmeldung, dass die Bedürfnisse erfült oder nicht erfüllt wurden.
* [line-through]#not a need - a strategy / kein Bedürfniss - eine Strategie / nie je potreba - stratégia#

---

* *subsistence / das Lebensunterhalt / živobytie*
* long life / langes Leben / dlhý život
* air / die Luft / vzduch
* fresh air / frische Luft / čerstvý vzduch
* clean air / saubere Luft / čistý vzduch
* water / das Wasser / voda
* drinking water / Trinkwasser / pitná voda
* nature / Nature / príroda
* physical health / physische Gesundheit / fyzické zdravie
* mental health / psychische Gesundheit / mentálne zdravie
* clothes / die Kleidung / oblečenie
* food / das Essen / jedlo
* movement / Bewegung / pohyb
* sleep / der Schlaf / spánok
* shelter / Obdach / prístrešie
* cleanliness / Sauberkeit / čistota
* bodily flexibility / körperliche Gelenkigkeit / telesná pružnosť
* warmth / Wärme / teplo
* people / Menschen / ľudia
* energy / Energie / energia
* enrichment of life / Bereicherung des Lebens / obohatenie života
* to make life wonderful / das Leben wunderbar machen
* light / das Licht / svetlo
* sunlight / Sonnenlicht / slnečné svetlo
* hygiene / Hygiene / hygiena
* environment / Umwelt / prostredie
* _pain / Schmerz / bolesť_
* _illness / Krankheit / choroba_

---

* *protection / die Schutz, Geborgenheit / ochrana*
* stability / Stabilität / stabilita
* safety / Sicherheit, Geborgenheit / bezpečnosť, bezpečie, istota
* security / Sicherheit / bezpečnosť, zabezpečenie
* equality / Gleichheit / rovnosť
* predictability / Vorsehbarkeit / predvídateľnosť
* power (with) / Macht (mit) / moc (s)
* strength / Kraft / sila
* protective use of force / beschützende Nutzung der Kraft / použitie sily na obranu
* protecting the nature / Umweltschutz / ochrana prírody
* ecology / Ökologie / ekológia
* sustainability / Nachhaltigkeit / udržateľnosť
* preservation / Erhaltung / zachovanie, udržanie
* durability / Haltbarkeit / trvácnosť
* robustness / Robustheit / odolnosť, robustnosť
* recycling / Wiederverwendung / recyklácia, znovupoužiteľnosť
* cautiousness / Vorsichtigkeit / opatrnosť
* economy, thrift / Sparsamkeit / úspornosť, šetrnosť
* justice, fairness, equity / Gerechtigkeit / spravodlivosť
* compensation / Ausgleich / kompenzácia, odškodnenie - nie ako odplata alebo trest, ale ako pomoc pri napĺňaní nenaplnených potrieb pre niekoho iného
* [line-through]#war / Krieg / vojna#
* [line-through]#violence / die Gewalt / násilie#
* [line-through]#government / die Regierung / vláda#

---

* *affection / Zuwendung / náklonnosť*
* love / Liebe / láska
* tenderness / Zärtlichkeit / neha
* sensuality / Sinnlichkeit / zmyselnosť
* passion / Leidenschaft / vášeň
* touch / Berührung / dotyk
* intimacy / Intimität / intimita
* closeness / Nähe / blízkosť
* trust / Vertrauen / dôvera
* care / Pflege / starostlivosť
* connection / Verbindung / spojenie, kontakt
* empathy _(Giraffe Dance)_ / Empathie (Precondition: courage / Mut) / empatia, súcit
* honesty _(Giraffe Dance)_ / Ehrlichkeit (Precondition: vulnerability / Verletzlichkeit) / úprimnosť
* generosity / Großzügigkeit / veľkorysosť
* support / Unterstützung / podpora
* communication / Kommunikation / komunikácia
* friendship / Freundschaft / priateľstvo
* mourning / Trauern / smútenie
* consideration / Rücksicht / ohľad
* respekt / Respekt / rešpekt
* honor / Ehre / úcta
* control / Kontrolle / kontrola - možnosť ovplyvniť prostredie okolo seba
* reassurance / Beschwichtigung / uistenie
* importance / Wichtigkeit / dôležitosť (potrieb)
* consciousness that my needs matter, that my needs are important and taken into consideration / Bewusstsein, dass meine Bedürfnisse wichtig sind, und in Frage genommen sind / vedomie, že na mojich potrebách záleží, že moje potreby sú dôležité a brané do úvahy
* relationships / Beziehungen / vzťahy
* tolerance / Toleranz / tolerancia
* nurturing, upbringing / Erziehung / výchova
* help / Hilfe / pomoc
* dignity / Würde / dôstojnosť
* _recognition, acknowledgement / Anerkennung / uznanie_
* _appretiation / Wertschätzung / ocenenie_
* _gratitude / Dankbarkeit / vďačnosť_
* [line-through]#apology (masked need for *empathy*: link:...[Marshall Rosenberg - Making Life Wonderful ???-which part???]), When we empathize, there is nothing to forgive. link:???[(SELF EMPATHY)], Forgiveness and empathy are the same thing [in the language of life.] link:???[(SELF EMPATHY)] / Verzeihung / ospravedlnenie#
* [line-through]#approval / Genehmigung / dovolenie, odobrenie#
* [line-through]#affirmation / Bestätigung / potvrdenie#
* [line-through]#sex / Geschlechtsverkehr#
* [line-through]#sexuality / Sexualität / sexualita#

---

* *understanding / Verständnis / porozumenie*
* critical thinking / kritisches Denken / kritické myslenie
* logical thinking / logisches Denken / logické myslenie
* curiosity / Neugier / zvedavosť
* interest / Interesse / záujem
* intuition / Intuition / intuícia
* concentration / Konzentration / sústredenie
* learning / Lernen / učenie sa
* competence / Fähigkeit / schopnosť
* utility / Nutzen / úžitok
* sense, purpose / Sinn, Zweck / zmysel
* goal / Ziel / cieľ
* common purpose / gemeinsames Ziel / spoločný cieľ
* effectivity [does it work, or not? - boolean] / Effektivität / efektivita
* efficiency [as much as possible in as little time as possible, e.g. efficient algorithm; how well does it work?] (in comparison to other things, not people) - float, percent) / Effizienz / efektivita
* growth / Wachstum / rast
* development / Entwicklung / rozvoj, vývoj
* consciousness / Bewusstsein / vedomie
* repetition / Wiederholung / opakovanie
* solution / Lösung / riešenie
* answer / Antwort / odpoveď
* feedback / Rückmeldung / spätná väzba
* understandability, clarity / Verständlichkeit, Klarheit / zrozumiťeľnosť
* education / Ausbildung / vzdelanie
* overview / Überblick / prehľad
* explanation / Erklärung / vysvetlenie
* knowledge / Kenntnise / vedomosti
* expertise / Fachkenntnisse / odborné znalosti, odbornosť, expertíza
* randomness / Zufälligkeit / náhodnosť
* compatibility / Kompatibilität / kompatibilita
* completeness / Vollständigkeit / úplnosť
* holism / der Holismus / celostnosť
* depth / die Tiefe / hĺbka
* uniformity (in Data) / Uniformität, Einheitlichkeit, Gleichmäßigkeit / uniformita
* readability / Lesbarkeit / čitateľnosť
* brevity / Kürze / stručnosť
* thoroughness / Gründlichkeit / dôkladnosť
* correctness / Richtigkeit / správnosť
* validity / Gültigkeit / platnosť
* seriousness / Ernsthaftigkeit / vážnosť
* transparency / Transparenz / transparentnosť, priehľadnosť
* links, coherences, context / Zusammenhänge, Kontext / súvislosti
* _complication / Komplikation_
* _problem / Problem_
* _mistake / Fehler / chyba_
* [line-through]#chaos / Chaos, Durcheinander#
* [line-through]#school / Schule / škola#
* [line-through]#work / Arbeit / práca#
* [line-through]#consumption / Konsum / spotreba#

---

* *participation / Teilnahme / účasť*
* acceptance (by others) / Annahme / prijatie
* community / Gemeinschaft / komunita, spoločenstvo, spoločnosť
* receptiveness (from others) / Annahmefähigkeit / prijímanie
* company / Gesellschaft / spoločnosť (ľudí)
* oneness, unity / Einheit / jednotnosť
* belonging / Zugehörigkeit / spolupatričnosť
* cooperation / Zusammenarbeit / spolupráca
* presence / Anwesendheit / prítomnosť
* sharing / Teilen / zdieľanie
* inclusion / Integration / integrácia, začlenenie
* common good / Gemeinwohl / verejné blaho
* [line-through]#competition / Wettbewerb / súťaž#
* [line-through]#competition / Konkurenz / konkurencia#
* [line-through]#race / Rennen / závodenie, preteky#

---

* *leisure / Freizeit / voľný čas*
* serenity / Gelassenheit / pokoj
* peace / Frieden / mier
* rest / Erholung / oddych
* harmony / Harmonie / harmónia
* calmness / Ruhe / pokoj
* awareness / Aufmerksamkeit / pozornosť
* celebration / Feier / oslava
* mindfulness / Achtsamkeit / vnímavosť
* fun / Spaß / zábava
* humor / Humor
* amusement / Vergnügen / potešenie
* enjoyment / Genuss / pôžitok
* softness / Weichheit / mäkkosť
* culture / Kultur / kultúra
* silence / Stille / ticho
* relaxation / Entspannung / uvoľnenie
* well-being / Wohlergehen, Wohlbefinden / blaho, spokojnosť
* relax / Erholung / oddych
* comfort / Bequemheit / pohodlie
* gratification / Befriedigung / uspokojenie
* contentment, satisfaction / Zufriedenheit / spokojnosť
* balance / Gleichgewicht / rovnováha
* gentleness / Sanftheit / jemnosť
* agility / Beweglichkeit / pohyblivosť
* _discomfort / Unbehagen / nepohodlie_
* [line-through]#instant gratification / sofortige Befriedigung / okamžité uspokojenie#

---

* *creation / Schöpfung / tvorivosť*
* imagination / Fantasie, Vorstellungskraft
* inventiveness / Ideenreichtum / nápaditosť
* play / Spiel / hra
* beauty / Schönheit / krása
* inspiration / Inspiration / inšpirácia
* art / Kunst / umenie
* challenge / Herausforderung / výzva
* discovery / Entdeckung / objav
* stimulation / Anregung / podnietenie
* music / Musik / hudba
* rhythm / Rhythmus / rytmus
* adaptability / Anpassbarkeit / prispôsobiteľnosť
* _smell / der Gestank / zápach_
* smell, scent / der Duft / vôňa
* flow / Flow, Strömung / prúdenie
* change / Änderung / zmena
* intrinsic motivation / eigene Motivation / vlastná motivácia
* fulfilment / Erfüllung / naplnenie
* quality / Qualität / kvalita
* innovation / Innovation, Erneuerung / inovácia
* performance / Leistungsfähigkeit / výkonnosť
* flexibility / Flexibilität / pružnosť, prispôsobiteľnosť
* freshness / Frischheit / čerstvosť
* handling (e.g. of a car) / Handling, Steuerungsfähigkeit / ovládateľnosť
* tightness / Dichtheit / tesnosť
* thickness / Dichte / hustota
* humidity / Feuchtigkeit / vlhkosť
* dryness / Trockenheit / sucho
* elasticity / Elasizität / elasticita, pružnosť
* plasticity / Plastizität / plasticita
* viscosity / Viskosität / viskozita
* style / Stil / štýl
* alternative / Alternative / alternatíva
* cohesion / Kohäsion / kohézia, súdržnosť
* coupling / Kopplung / väzbovosť
* match / Übereinstimmung / zhoda
* roughness / Rauheit / drsnosť
* smoothness / Glätte / hladkosť
* diversity / Vielfalt(igkeit) / rôznorodosť, diverzita
* transparency / Durchsichtigkeit / priehľadnosť
* [line-through]#productivity / Produktivität / produktivita#

---

* *identity / Identität / identita*
* consistency / Konsistenz / pravidelnosť, vytrvalosť
* integrity / Integrität / integrita, súlad
* authenticity / Authentizität / autenticita, svojskosť
* spontaneity / Spontaneität / spontánnosť
* reliability / Verlässlichkeit / spoľahlivosť
* accuracy / Genauigkeit / presnosť
* precision / Präzision / precíznosť
* privacy / Privatsphäre / súkromie
* simplicity /Einfachheit / jednoduchosť
* punctuality / Pünklichkeit / dochvíľnosť
* trustworthiness / Glaubwürdigkeit / dôveryhodnosť
* spirituality / Spiritualität / spiritualita
* lightness / Leichtigkeit / ľahkosť
* fluency, smoothness / Flüssigkeit / plynulosť
* gracefulness / Anmut / ladnosť
* endurance / Ausdauer / vytrvalosť
* naturalness / Natürlichkeit / prírodnosť, prirodzenosť
* resonance / Resonanz / rezonancia, súzvuk
* determination / Entschlossenheit / rozhodnosť
* intensity / Intensität / intenzita
* dedication / Einsatz / nasadenie
* self-fullness / Selbsvölligkeit / sebanaplnenie
* maintainability / Wartbarkeit, Wartungsfreundlichkeit / udržovateľnosť
* patience / Geduldigkeit / trpezlivosť
* speed, velocity / Geschwindigkeit, Schnelligkeit / rýchlosť
* responsiveness / Schlagfertigkeit / promptnosť, pohotovosť, bystrosť
* tradition / Tradition / tradícia
* habit / Gewohnheit / zvyk
* courage / Mut / odvaha
* responsibility / Verantwortung / zodpovednosť
* altruism / Altruismus / altruizmus
* solidarity / Solidarität / solidarita
* humanity / die Menschlichkeit / ľudskosť
* order / Ordnung / poriadok
* consentual rules / gemeinsam bestimmte Regeln / spoločne stanovené pravidlá
* [line-through]#rules / Regeln / pravidlá#
* [line-through]#power (over) / Macht (über) / moc (nad)# link:...[Ökonomische Pseudowerte: https://www.youtube.com/watch?v=7mRe1ntgbj8&feature=youtu.be&t=1260]
* [line-through]#money / Geld / peniaze#
* [line-through]#success / Erfolg / úspech#
* [line-through]#[social] status / [soziales] Status / [spoločenský] status,  stav, postavenie#
* [line-through]#popularity (to be liked by other people) / Popularität (unter Leuten beliebt zu sein) / popularita (byť oblúbený medzi ľuďmi)#
* [line-through]#individualism / Individualismus / individualizmus#
* [line-through]#ownership (to have and to have more) / Eigentum / vlastníctvo#
* [line-through]#religion / Religion / náboženstvo#

---

* *freedom / Freiheit / sloboda*
* risk / Risiko / riziko
* hope / Hoffnung / nádej
* space / Raum / priestor
* choice / Auswahl / voľba
* availibility / Verfügbarkeit /  dostupnosť
* time / Zeit / čas
* access / Zugriff / prístup
* mobility / Mobilität / prenosnosť
* transportation / Transport / preprava, doprava, transport
* autonomy / Selbstständigkeit, Autonomie / samostatnosť
* faith / Glaube / viera
* voluntariness / Freiwilligkeit / dobrovoľnosť
* willingness / Bereitschaft / ochota

== Feelings at unfulfilled needs (Sweet pain - Girrafe mourning) / Gefühle bei unerfüllten Bedürfnissen

What needs of mine are not being met?

What needs of the other are not being met?

* terrified / erschrocken / vystrašený (vystrašiť, báť sa)
* frightened / verängstigt / vystrašený (vystrašiť)
* alarmed / erschrocken / vystrašený (vystrašiť)
* scared / erschrocken / vyľakaný (vyľakať)
* anxious / besorgt / ustarostený (robiť si starosti, mať starosti, obávať sa)
* fearful / ängstlich / ustarostený (robiť si starosti, mať starosti, obávať sa)
* concerned / bekümmert / ustarostený (robiť si starosti, mať starosti, obávať sa)
* worried / besorgt / ustarostený (robiť si starosti, mať starosti, obávať sa)
* shocked / schockiert / šokovaný (šokovať)
* surprised / überrascht / prekvapený (prekvapiť)
* disturbed / beunruhigt, gestört / znepokojený, rozrušený, vyrušený (znepokojiť, rozrušiť, rušiť, vyrušovať, rozptyľovať, vadiť)
* irritated / irritiert / iritovaný, nervózny (iritovať, znervózniť)
* nervous / nervös / nervózny (znervózniť)
* discontented / unzufrieden / nespokojný
* tense / angespannt / napätý (napínať)
* frustrated / frustriert / frustrovaný (frustrovať)
* disgusted / geeckelt, angeeckelt / znechutený (znechutiť)
* sick (e.g. upset stomach) / übel (z.B. Magen-Verdauungsbeschwerden) / zle, nevoľno (napr. od žalúdka)
* hesitant / zögernd / váhavý (váhať)
* distrusting / misstrauend / nedôverčivý (nedôverovať)
* doubting / zweifelnd / pochybovačný (pochybovať)
* sceptical / skeptisch / skeptický, pochybovaťný (pochybovať)
* imatient / ungeduldig / netrpezlivý (I can't wait / ich kann nicht warten / nevedieť sa dočkať)
* confused / durcheinander / zmätený (zmiasť)
* bewildered / verwirrt / zmätený (zmiasť)
* discouraged / entmutigt / odradený (odradiť)
* lonely (this one manifests as a pain and weakness in heart) / einsam / osamelý
* apathetic / apathisch / apatický, ľahostajný (to loose interest in something, burn out / die Interesse an etwas [Akk.] verlieren, ausbrennen / stratiť záujem, vyhorieť)
* bored / gelangweilt / znudený (nudiť sa, unudiť)
* indifferent / gleichgültig / ľahostajný (lose interest / Interesse verlieren / stratiť záujem)
* tired / müde / unavený (unaviť)
* exhausted / erschöpft / vyčerpaný (vyčerpať)
* regretful / bedauernd / byť ľúto
* helpless / hilflos, ratlos / bezradný (nevedieť si rady, nevedieť si poradiť)
* powerless (often misunderstood as _stress_) / +
machtlos (häufig verwechselt mit _Stress_) / +
bezmocný (často zamieňaný so _stresom_)
* disappointed / enttäuscht / sklamaný (sklamať)
* sad / traurig / smutný (smútiť)
* hurt / verletzt / ranený, zranený, dotknutý
* hopeless / hoffnungslos / beznádejný (stratiť nádej)
* desperate / verzweifelt / zúfalý (zúfať)
* vulnerable / verletzlich / zraniteľný
* leiden / suffer / trpieť
* suffer / sich quälen / trápiť sa
* pain / der Schmerz / bolesť

*Bitter pain - Alarm feelings / Bittere Schmerzen - Weckgefühle*

Disconnected from needs / Unterbunden von Bedürfnissen

* *angry / ärgerlich / nahnevaný (hnevať sa)*
* indignant / empört / rozhorčený (rozhorčiť sa)
* furious, mad, enraged / wütend, zornig, aufgebracht / zúrivý (zúriť)
* hating / hassend / nenávidiaci, nenávistný (nenávidieť)
* *depressed / deprimiert (in Depression fallen) / deprimovaný (upadnúť do depresie)*
* *guilty / schuldig / vinný*
* *ashamed / beschämt / zahanbený (hanbiť sa)*
* envious / neidisch / závistlivý (závidieť)
* jealous / eifersüchtig / žiarlivý (žiarliť)
* embarassed / verlegen / rozpačitý, v rozpakoch

*Not-feelings - thoughts, analyses, diagnoses, interpretations, criticisms / Nicht Gefühle / ne-pocity*

link:...[Source]

* resentful
* overwhelmed
* lost
* abandoned
* abused
* attacked
* belitted
* betrayed
* blamed
* bullied
* boxed in
* caged
* cheated
* coerced
* cornered
* critcized
* disconnected
* discounted
* diminished
* disliked
* distrusted
* dumped on
* harassed
* hassled
* horny / geil / nadržaný
* ignored
* insulted
* interrupted
* intimidated
* invisible
* isolated
* judged
* left out
* let down
* manipulated
* mistrusted
* misunderstood
* neglected
* overpowered
* patronized
* pressured
* provoked
* put down
* rejected -> disappointed
* ripped off
* screwed
* smothered
* suffocated
* taken for granted
* threatened
* trampled
* walked on
* tricked
* unaccepted
* unappreciated
* unheard
* unloved
* unseen
* unsupported
* unwanted
* used
* victimized
* violated
* wronged
* resentful

*Not feelings - Moralistic judgements - Social constructs*

* smart
* dumb
* generous
* lazy
* considerate
* inconsiderate
* responsible
* irresponsible
* guilty
* innocent
* good
* bad
* right
* wrong
* normal
* abnormal
* weird
* awkward
* sick
* awesome
* nice
* sinful
* wretched
* creepy
* perverse
* unfair
* pretty
* handsome
* ugly
* handsome
* sexy
* reasonable
* unreasonable
* lucky
* unlucky
* hyperactive
* crazy
* professional
* unprofessional
* amateur
* _all vulgarisms_
* vulgar
* ridiculous
* decent
* appropriate
* selfish
* generous
* disrespectful
* spoiled
* naïve
* fast
* slow
* competent
* incompetent
* adequate
* inadequate
* inferior
* important
* unimportant
* significant
* insignificant
* charismatic
* würdig
* unwürdig

== Feelings at fulfilled needs - Dream Feelings - Flow

Gefühle bei erfüllten Bedürfnissen / Pocity pri naplnených potrebách.

How do I want to feel? [RPM]

---

[line-through]#(November 2019) Ich kann meine Gefühle beschreiben, die ich bei meinen Traumaktivitäten erleben möchte, weil ich nicht den Wortschatz an Gefühle habe. Ich brauche mir die Äußerung meiner Gefühle erreichern. Ich brauche die Fähigkeit, die Gefühle in mir bewusst werden und sie benennen. Dann kann ich mir an maine Traumgefühle erinnern und sie gleich wiederherstellen.#

---

Flow - a state of optimal human performance and happiness +
*_optimal human performance_* means the same as *_happiness_* link:...[(Cedric Dumont - TEDx; Flow - Mihály Csíkszentmihályi)]

Celebration of life / Feier des Lebens / oslava života

link:https://sci-hub.st/10.1080/10413200290103545[The Dream - Dream Feelings: Doug Newburg]

link:...[Nonviolent Communication (NVC) - Feelings at fulfilled needs]

[quote, Marshall B. Rosenberg - Chief from one of the tribes in northern Nigeria, Making Life Wonderful ?/4; San Francisco Workshop]
____

If we know how to speak this language, we don't have to kill each other.

____

Wie will ich mich fühlen wenn ich: +
spreche, mit jemandem spreche, schreibe, zuhöre, mich dusche, mich mit kaltem Wasser dusche, programmiere, UML-Diagramme zeichne, lerne, Algorithmen ausdenke, nachdenke, Akkordeon spiele, nach etwas suche, esse, Wäsche wasche, Wäsche aufhänge, einkaufe, schlafe, einschlafe, Pilates übe, Yoga übe, laufe, TRX übe, Augen übe, Atem übe, übe, mich bewege, ausruhe, meditiere, plane, Fremdsprachen lerne, Bücher lese, Bücher höre, zu gesprochenem Wort höre, Musik höre, mir Videos anschaue, Artikel lese, Artikel schreibe, lehre, forsche, in C++ programmiere, in Fremdsprachen Geschichten schreibe, zu Projekten beitrage, "Nein" höre, ein Auto fahre, mich vorbereite, Musik komponiere, übersetze, Musik in Noten überschreibe, Aussagen in gewaltfreie Kommunikation übersetze, Noten eines Liedes lese, experimentiere, Fehler mache, nach Zusammenhängigkeiten suche, von Fehlern lerne, präsentiere, einen Quellcode lese, einen fremden Quellcode lese, einen fremden Quellcode lese, einen fremden Quellcode ändere, einen fremden Quellcode bearbeite, einen komplizierten Quellcode ändere, einen komplizierten Quellcode bearbeite, einen kompliziertes Software entwerfe, einen, ein kompliziertes Software entwickle, ein kompliziertes Software analysiere, ein fremdes Software analysiere, schnell an die Tastatur schreibe, schnell programmiere, Probleme löse, Fragen beantworte, mich in mich oder anderen hineinfühle, Empathie zeige, Konflikte löse, Fragen beantworte, mich mit meinen Gefühlen und Bedürfnissen verbinde, Fragen stelle, aufräume, mir das Essen vorbereite, das Geschirr spüle, die Gefühle und Bedürfnisse hinter jeder Aussage rate, programmieren lerne, Programmiersprache lerne...

^^ Das mache ich...

\... und so will ich mich dabei fühlen:

* free / frei / voľný, slobodný
* relaxed / entspannt / uvoľnený
* excited / erregt / vzrušený
* courageous / mutig / odvážny
* energetic, full of energy / energisch / energický
* optimitstic / optimistisch / optimistický
* concentrated, focused / konzentriert, fokusiert / sústredený
* calm / ruhig / pokojný
* curious / neugierig / zvedavý
* interested / interessiert / zaujímajúci sa
* wondering / wundernd / čudujúci sa
* glad / froh / rád
* cheerful / fröhlich / radostný
* friendly / freundlich / priateľský
* joyful / freudvoll / veselý (tešiť sa, zabaviť sa, pobaviť, zasmiať sa z ...)
* happy / glücklich / šťastný
* confident / selbstsicher / sebaistý
* safe / sicher, geborgen / v bezpečí
* light / leicht / ľahký
* fulfilled / erfüllt / naplnený
* content / zufrieden / spokojný
* satisfied / befriedigt / uspokojený
* immersed / eingetaucht / ponorený
* strong / stark / silný
* powerful / kräftig, kraftvoll / silný
* mighty / machtvoll / mocný
* attentive / aufmerksam / pozorný
* determined / entschlossen / rozhodný
* blissful / glückselich / blažený
* lively / lebendig / nažive
* vigorous / lebhaft / húževnatý
* hungry (before exercising) / hungrig / hladný
* unstoppable / unaufhaltbar / nezastaviteľný
* dedicated / eingesetzt / v nasadení
* patient / geduldig / trpezlivý
* full of expectations / erwartungsvoll / plný očakávaní
* sleepy / schläfrig / ospalý
* on fire (at hardening) / in Brand gesetzt (bei Härten) / ako v ohni (pri otužovaní)
* rested / erholt / oddýchnutý
* deeply rooted / tief verwurzelt / hlboko zakorenený
* impressed / beeindruckt / ohúrený
* touched / berührt / dojatý
* relieved / erleichtert / uľavený (uľaviť)
* encouraged / ermutigt / odhodlaný
* hopeful / hoffnungsvoll / plný nádeje
* goot (vague feeling - needs to be more closely specified in order to make a closer connection) / gut / dobre
* passionate / leidenschaftlich / vášnivý

^^ Dream feelings [Doug Newburg - RPM]. Diese Gefühle habe ich bei erfühlten Bedürfnissen. [NVC Buch]

== Comparisons

- Punishment and Rewards vs Discipline, Care, Unconditional Love and Reason - link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4], Alfie Kohn, Samuel P. Oliner + Pearl M. Oliner [Altruistic Personality + Samuel Oliner Testimony], Miki Kashtan [Exiting the Either/Or Trap - 17th minute]
- Shame, Punishment and Revenge vs Safety, Respect, Responsibility, Care and Unconditional Love - Miki Kashtan-Bullying, link:https://www.youtube.com/watch?v=2KXwnbsQUrI&feature=youtu.be&t=87[Restorative Justice Continuum - Howard Zehr Ph.D EM 1:27-2:12], link:https://www.youtube.com/watch?v=0pleCht2jN4&feature=youtu.be&t=439[NVC Guilt and Shame - Kirsten Kristensen: ???-???, Alfie Kohn, James Gilligan - Shame]
- Production and Comsumption vs Care and Freedom - link:https://www.youtube.com/watch?v=kikzjTfos0s&feature=youtu.be&t=2958[On Bullsh*t Jobs | David Graeber | RSA Replay: 49:18-49:44]
- Gratitude and Appreciation vs Reward, Praise and Compliments- M. B. Rosenberg, Alfie Kohn, Peter Gray
- Criticism, Punishment, Praise and Compliments vs Observation, Feeling, Need, Request and Unconditional Love - M. B. Rosenberg, Alfie Kohn
- Observation vs Evaluation - Jiddu Krishnamurti, M.B. Rosenberg, link::https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1711[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 28:31-29:40]
- Criticism, Punishment, Praise and Compliments vs Unconditional Love - Alfie Kohn [OFJCC - 26:10-27:28-30:04]
- Honesty vs Criticism and Blame - M. B. Rosenberg [Making life wonderful - part 1/4 - somewhere at the beginning]
- Feedback and life-serving Judgement and Evaluation for decision-making vs moralistic Evaluation and Judgement, Praise, Compliments, Reward, Blame, Criticism and Punishment - Alfie Kohn
- Request vs Demand - M. B. Rosenberg - Portland Workshop time: ??? + resolving conflicts with children workshop time: ???
- Power over (people and nature) vs Power with (people and nature) - Mary Parker Follett, link:https://sci-hub.st/10.5840/pom20033221[Power, Freedom and Authority in Management: Mary Parker Follett’s ‘PowerWith’ - Domènec Melé, Josep M. Rosanas] Miki Kashtan [Exiting the Either/Or Trap - 30th minute], M. B. Rosenberg, Alfie Kohn, Mark Shepard-"Power over nature vs Power with nature"
- Authority based on 'power over' model vs Authority based on 'power with' model - M. B Rosenberg [interview with paula gloria], Mary Parker Follett
- Obedience vs Responsibility - link:https://www.youtube.com/watch?v=HLgGt7yLhJg&feature=youtu.be&t=3373[Atelier communication non violente - Marshall Rosenberg - Danemark - sous-titres français: 56:13-57:15]
- Respect vs Obedience - link:https://www.youtube.com/watch?v=HLgGt7yLhJg&feature=youtu.be&t=3373[Atelier communication non violente - Marshall Rosenberg - Danemark - sous-titres français: 56:13-57:15], link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4]
- Respect vs Fear - link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4]
- Respect vs Approval - link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=1008[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 16:48-22:20)]
- Empathy, Power with People and Respect vs Obedience - link:https://www.youtube.com/watch?v=NqJ-0EIsy9U&feature=youtu.be&t=5658[Marshall Rosenberg - NVC Workshop 2004 Portland, OR: 1:34:18-1:36:18], Mary Parker Follett, Power, Freedom and Authority in Management: Mary Parker Follett’s ‘Power With’-Domènec Melé and Josep M Rosanas-10.5840@pom20033221
- Intrinsic motivation vs Extrinsic motivation - Alfie Kohn [OFJCC Overemphasizing achievement]
- Internal motivation vs Extrinsic motivation - Alfie Kohn [OFJCC Overemphasizing achievement]
- Excellence vs Superiority - Is Meritocracy a Sham? | Amanpour and Company: link:https://www.youtube.com/watch?v=BLEvJUNfyBY&feature=youtu.be&t=592[9:52-11:32], link:https://www.youtube.com/watch?v=BLEvJUNfyBY&feature=youtu.be&t=910[15:10-16:24]
- Duty and Obligation vs Freedom and Choice - Maria Montessori, Peter Gray, Alfie Kohn, M. B. Rosenberg
- Retributive justice vs Restorative justice - M. B. Rosenberg, Miki Kashtan, Howard Zehr, link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]
- Violence vs Justice - link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]
- Oikonomia vs Chrematistike - Aristoteles, link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=273[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 4:33-6:41)], link:https://sci-hub.st/10.2307/40295009[Oikonomia versus Chrematistike: Learning from Aristotle about the Future Orientation of Business Management  - Claus Dierksmeier, Michael Pirson]
- Growth vs Development link:???[Manfred Max-Neef - Democracy Now]
- Agriculture vs Permaculture - Mark Shepard
- Efficiency vs Sufficiency and Well-being - link:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3357638/#Sec4title[Manfred Max-Neef - The World on a Collision Course and the Need for a New Economy: Chapter "Crisis of Crises"]
- School vs Education - Peter Gray
- Education vs Indoctrination - link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=771[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 12:51-13:41)], Peter Gray
- Consentual Rule and Dogma - M. B. Rosenberg [Consentual rules: Resolving conflicts with children workshop], link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=771[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 12:51-13:41)]
- Interdependency vs Codependency - Alfie Kohn
- Process vs Product - Rachel Rainbolt - episode with peter gray, Peter Gray - Play
- Empathy vs Sympathy - link:...[M. B. Rosenberg], link:https://youtu.be/KX_tgRM84RA?t=370[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 6:10-8:08)]
- Empathy vs Forgiveness - link:...[maybe Creating Life Serving System Withing Ourselves???]
* Intensity vs Consistency - link:???[Simon Sinek]
* To deserve something vs To need something (me)
* Robustness vs Perfection link:https://www.youtube.com/watch?v=kzHrBM6CHfE&feature=youtu.be&t=1889[An Interview with Elinor Ostrom: 31:29-31:53]
* Participatory Democracy, Flatpack Democracy (Frome), Democratic Confederalism, Communalism, Stateless Democracy and Anarchist Communism, vs Autocracy, Representative Democracy, Authoritarianism, Populism, Fascism, Nazism and Nationalism etc. link:https://mesopotamia.coop/the-internal-system-of-the-communes-in-rojava/[(THE INTERNAL SYSTEM OF THE COMMUNES IN ROJAVA)]
* link:https://www.fachverband-gfk.org/wp-documents/anlage_3_schluesselunterscheidungen.pdf[und mehr Unterschiede...]

Culturally learned beliefs - Life-harming beliefs:

- spare the rod, spoil the child - Bible, Proverbs 13:24, Rosenberg - Resolving conflicts with children
- No pain, no gain.
- Čím väčším peklom si prejdeš, tým silnejší z toho výjdeš. Ak z toho výjdeš. - (Jaroslav Slávik, Československo má talent)
- Tréning robí majstra.
- Better get used to it! (BGUTI - Alfie Kohn)
- Like it or not! (Alfie Kohn)
- That's just how it is. link:https://veganvanguardpodcast.com/how-competition-dominates-our-lives/(Mexie - 2. The Trope of “Competition” Dominates Our Lives: 2:04-2:28)

== Resonance Performance Model [RPM]

by Doug Newburg

*The goal:* C++ programmer in Austria

*Das Ziel:* C++ Programmierer in Österreich

*1.) The Dream / Der Traum*

*Dream feelings / Traumgefühle:* +

* joy of learning / Freude an Lernen
* courage to make mistakes / Mut, Fehler zu machen
* relaxed speed / entspannte Geschwindigkeit
* easy effort / einfache Mühe
* persistence of steel / Ausdauer aus Stahl
* connection to feelings and needs under all circumstances / Verbindung mit Gefühlen und Bedürfnissen unter allen Umständen
* empathic connection before correction / empathische Verbindung vor der Korrektur
* fast reflexes / schnelle Reflexe
* huge and accurate memory / riesengroßes und genaues Gedächtnis
* energy of a powerhouse / Energie eines Kraftwerkes
* empathy for everyone everytime / Empathie für jeden jederzeit
* calm limbs / ruhige Glieder
* quick reading with understanding / schnelles Lesen mit Verständnis
* energy without violence - joyful energy / Energie ohne Gewalt - freudvolle Energie
* success without victory - collective success / Erfolg ohne Sieg - gemeinsamer Erfolg
* programming with joy and lightness / Programmieren mit Freude und Leichtigkeit
* empathy with the ease of a hot knife cutting through a butter / Empathie mit der Leichtigkeit eines Messers, das durch die Butter geht
* joy of every single line of code that I write / Freude an jeder Zeile des Codes, die ich schreibe
* fulfilment of my needs that will be more effective and less costly to my and other people / die Erfüllung meiner Bedürfnisse, die effektiver und weniger kostlich für mich und andere Menschen ist

*2.) Preparation / Vrobereitung*

* Training
* Exercise / Übung
** body / Körper
** mind / Geist
* (Perfect) preparation precedes mastery. +
  (Perfekte) Vorbereitung geht der Meisterschaft voraus. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???], link:???[Daniel Markovits - Meritocracy and Its Discontents: ???-???]

*3.) Obstacles, Successes / Hindernisse, Erfolge*

* Gefühle, erfüllte Bedürfnisse, Erfolge und Ergebnisse bei der Vorbereitung
* loosing connection with dream feelings / die Verbindung zu meinen Traumgefühlen wird schwächer

*3.5) Obstacle-Preparation Loop / Hindernis-Vorbereitungs-Schleife

* Burn-out spiral / Ausbrennungsspirale
* Lose of interest, energy, meaning, intrinsic motivation
* Depression
* ???

*4.) Revisiting the dream / Wiederverbindung mit dem Traum*

* Reconnection with my dream feelings. / Wiederverbindung mit meinen Traumgefühlen.
* Ask myself "How do I want to feel?". / Ich frage mich "Wie ich mich fühlen will?".
* Revisit my feelings, needs and the dream. / Meine Gefühle, Bedürfnisse, und den Traum wiederholen
* Revisit the feelings at unfulfilled and fulfilled needs. / Die Gefühle bei unerfüllten und erfüllten Bedürfnissen wiederholen.
* Burn-out prevention / Ausbrennungsprävention / Prevencia proti vyhoreniu.
* Expressing gratitude / Dankbarkeit äußern
* Empathize / Fühle dich hinein
* Empathy / Empathie
* Nonviolent Communication - NVC / Gewaltfreie Kommunikation - GFK
* Expressive writing link:...[(James Pennebaker - Researchgate link???)]
** Showing empathy to me, my inner educator and my inner chooser through NVC - talking or writing about my feelings and needs *in the present moment*, stimulated by various events. Talking about the past is the domain of psychotherapy and doesn't contribute to the healing of the pain. The more we spend in the past, the less healing takes place.
* How you feel is more important than what you do. +
  Wie du dich fühlst ist wichtiger als das, was du machst. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]
* Attitude is more important than aptitude. +
  Innere Einstellung ist wichtiger als Fähigkeit. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]
* The act of learning is more important than how well [or fast] I'm learning.
  Das, dass ich lerne ist wichtiger, als das, wie gut [oder schnell] ich lerne. +
  link:???[Alfie Kohn ??? + Cedric Dumont - From Fear to Flow ???]
* People who I let myself to inspire from / Leute von denen ich mich inspirieren lasse
** Ivo Toman - TAXUS Learninig - Lernen einer Fremdsprache durch gleichzeitiges Hören und Lesen eines wortwortlichen Textes in der Mutter- oder Fremdsprache, der zu dem gehörtem Text gehört.
** *Wim Hof - Wim Hof Methode*
** Marie Kondo - Konmari-Methode
** Blue Zones / Blaue Zonen - Forschung; überdurchschnittliche Gebiete mit überdurchschnittlicher Lebenslänge, z. B. Moai: Okinawa-Japan
** Simon Sinek - Intensity vs Consistency
** Josh Millburn & Ryan Nycodemus - minimalizmus
** Fumio Sasaki - minimalizmus
** *Maria Montessori - education; Buch: Montessori method / Il metodo della pedagogia scientifica applicato all'educazione infantile nelle case dei bambini* link:[(Maria Montessori - thehistorychicks: 1:24:24-1:24:32)]
** *Lucia Rolcekova - Pilates, Physiotherapie; ActiveClinic*
** *Kristina Zanova - Yoga; Rücken Rollen; ActiveClinic*
** Matus Chochlik - FRI UNIZA -> GlobalLogic
** Zdenko Pavlik - Scheid & Bachmann Zilina - Tankstellenabteilung -> GlobalLogic
** James Pennebaker - Expressive writing
** *Marshall B. Rosenberg - NVC: Nonviolent Communication*
** *Alfie Kohn - education, parenting*
** *Peter Gray - SDE: Self-Directed Education; play; Buch: Free to Play*
** Bethany Butzer - Stop trying so hard. Achieve more by doing less. Reference to Doug Newburg's research.
** *Doug Newburg - RPM: Resonance Performance Model*
** Milan Ondrasovic - Referenz zu Autophagozytose von Yoshinori Ohsumi
** Yoshinori Ohsumi - Autophagozytose: Hungern und seine Folgen aufs Gesundheit
** *Mihály Csíkszentmihályi - Flow*
** Cedric Dumont - From fear to Flow
** Miki Kashtan - NVC Management and Leadership
** *Daniel Markovits - Buch: The Meritocracy Trap*; Excellence vs. Superiority; "It's not about working hard, it's about doing the hard work. - connection to research from _Doug Newburg: Resonance Performance Model_"
** Lawrence Chong - Economy of Communion
** *Manfred Max-Neef - Barefoot Economy*: Economy based on fulfilling of each other's needs; **Human Scale Development**
** Christian Felber - Economy of Common Good / Gemeinwohl-Ökonomie
** Scott Meyers - Effective C++, More Effective C++
** Martin Fowler - Refactoring to Patterns
** Howard Zehr - Restorative Justice
** David Barter - Restorative Justice with NVC
** Carl R. Rogers - Humanistic Psychology; Humanism; Reference from M. B. Rosenberg and Alfie Kohn
** Mark Shepard - Permaculture; Buch: Restoration Agriculture
** Peter Kropotkin (Pyotr Alexeyevich Kropotkin) - Anarcho-Communism, Anarchist Communism, Kommunistischer Anarchismus; Bücher: Anarchist Communism: Its Basis and Principles; The Conquest of Bread
** David Harvey - Buch: Contradiction of Capitalism
** Ha-Joon Chang - Buch: 23 Thing They Don't Tell You About Capitalism
** Samuel P. Oliner, Pearl M. Oliner - Buch: _The Altruistic Personality: Rescuers of Jews in Nazi Europe_
** Sepp Holzer - Permakultur; Buch: Zahrada k nakousnuti
** Walter Kaufmann - Without Guilt and Justice: From Decidophobia to Autonomy
    *** concept of "deserve" broken
    *** retributive justice is suicidal
** James Gilligan - Violence: Our Deadly Epidemic and its Causes
** Elizabeth M. Elliott - Security, with Care: Restorative Justice and Healthy Societies
** Elinor Ostrom - The Tragedy of the Commons + Design Principles for Collective Managing of a Shared Resource - Arguments for collective ownership and decision making and against capitalism, private [land] ownership
** Bruce Lipton, Peter Spork - Epigenetics

== Questions

Sources: +
link:https://www.goodreads.com/review/show/1151152216?book_show_action=true[Doug Newburg - The Most Important Lesson No One Ever Taught Me] +
link:https://www.researchgate.net/publication/254102089_The_process_of_performance_of_four_track_athletes_A_resonance-based_intervention[Doug Newburg - The process of performance of four track athletes: A resonance-based intervention → The Components of the RPM → ...Specific research questions
included...]

↓ +

* How do you like to feel every day? link:https://www.youtube.com/watch?v=nraBwnT2XlY&feature=youtu.be&t=302[(bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 5:02-5:12)]
* *Does how you feel affect how you perform?* Everyone says "yes", and yet most of you don't know how you like to feel. [Is this applied *emotional intelligence*? That the most successful are not the ones who have the highest IQ, but the highest EQ?] link:https://www.youtube.com/watch?v=nraBwnT2XlY&feature=youtu.be&t=312[(bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 5:12-5:22)]
* * * *
* *_How do I want to feel when I engage in my activities?_*
* How do I want to feel every day?
* How do I want to feel about my life in general?
* _*How do I perceive these feelings?*_
* _*How do these feelings affect my performance?*_
* _*How do these feelings affect my overall well-being?*_
* _What enables me to experience these feelings?_
* When these feelings happen?
* Where these feelings happen?
* Around whom these feelings happen?
* _*What inhibits me from experiencing these feelings?*_
* What takes these feelings away?
* What gets in the way of these feelings?
* _*How do I reconnect with my dream feelings when I face obstacles?*_
* How do I recreate these feelings?
* How do I experience these feelings again?
* Am I willing to accept the risk that I can fail in the activities I engage in? / Bin ich bereit dem Risiko unterzuziehen?
* Am I willing to accept the responsibility that I can succeed in the activities I engage in?

---

* Ist daran etwas schlechtes?
* Ist Angst vor Urteilen und Bewertungen mit Aufblasen verbunden?
* Wie hängt die Angst vor Urteilen und Bewertungen und Aufblasen und andere Gesundheitsbeschwerden mit dem Hirnnerv *Nervus Vagus* zusammen?
* If every activity that serves life and fulfills my needs is play, does it mean that when I get disconnected from my needs, I loose the ability to play?
* Wie kann ich über meine Schwächen und Fehler mit jemandem sprechen, ohne mich schuldig oder beschämt zu fühlen?
* Wo finde ich Energie für meine aktivitäten?
* How can I enjoy other people's pain?

---

* Wie fühlt sich vielleicht der andere Mensch?
* Wie fühle ich mich?
* Wie will ich, dass der Andere sich fühlt?
* Wie will ich mich fühlen?
* Wo finde ich Energie für Einfühlung?
* How can I learn from my mistakes without hating myself?
* Wie kann ich mich mit meiner Angst hineinfühlen und sie zu überwinden?
* What happens to me when I don't do what others want? → *Fear of punishment*
* What happens to me when I don't do what others want? → *Desire for reward*
* Do I want my failures and concerns to stop me from following my dreams?
* What keeps you from saying "yes"?
* What keeps you from fulfilling my needs?
* Was sage ich mir im Kopf, wenn ich diese Gefühle spüre?
* *Who benefits from this? / Wer profitiert davon?*
* Wie kombiniere ich Empathie und Optimismus?

---

* What makes people to enjoy violence?
* Why did we start to educate people to enjoy violence?
* Who benefits from education to violence and obedience?
* What makes people to enjoy contributing to the well-being of other people?
* What is this person feeling and needing?

---

* Do the activities have sense?
* What value has the task I engage in?
* What is the point of this task?
* Unterstützen Hausaufgaben die Ausbrennung in den Studenten?
* Auf welcher Weise formt die Erziehung durch Bestrafungen und Belohnungen die Sprache meines inneren Lehrer? link:???[Alfie Kohn - Unconditional Parenting + Punished by Rewards], link:???[M.B. Rosenberg - How do you talk to yourself when you're making mistakes?]
* Why punishment and reward never work?
** What would I want the other person to do differently? → _punishment sometimes works_
** What do I want the other person's reasons to be for doing what I request of them? → _punishment never works_
* What teaches punishment and rewards other people?
* What are my long term goals for other people to be?
* How I like them to turn out?
* What would I want the to be like?
* Is that what I'm doing consistent with what I want?
* Is that what I'm doing consistent with my long-term goals?
* Do the things that I say and do contribute to my long term goals?
* What are my long-term goals for other people to feel about themselves?
* What are my long-term goals for other people to feel about their life in general? [connection to Doug Newburg - Resonance Performance Model questions]

=== Connection Requests

* "Can you live with it?" link:https://www.youtube.com/watch?v=6rFMoUY6KpM&feature=youtu.be&t=3730[(Making Collaboration Real: Miki Kashtan: Maximizing Willingness for Collaboration Decision-Making: 1:02:10-1:02:15)]

=== Strategy Requests



=== Restorative justice

A form of justice that concentrates on the restoring the relationships in the human, and between the human and the community. link:???[Barter - What is Restorative Justice - Youtube]

* Questions of justice

. What was the observable behavior of the perpetrator?
. Empathy of the perpetrator for the victim. - What needs was the perpetrator trying to meet? - Empathy with the perpetrator's inner chooser. Empathy with the victim's unfulfilled needs. The cost or impact of the perpetrator's behavior to the needs of other people.
. Giraffe mourning on the part of the perpertator. - What needs the perpetrator didn't meet by his/her behavior? - Self-forgiveness within the perpetrator
. Searching for ways to get everybody's needs met that would be more efficient and less costly. - Repairing the harm and healing the pain with concrete activities of the perpetrator that will contribute to life well-being of others.

[options="header"]
|===========================
| Retributive Justice | Restorative Justice (H. Zehr) | Restorative Justice (M. B. Rosenberg [NVC])
| What law was broken? | What happened during the crime? +
                         What happened before the crime? |
                                                           1.) What was the  observable behavior of the perpetrator? +
                                                           2.) What was the  observable behavior of the victim? +
| Who broke that rule? | Why did it happen? | 1.) How did the perpetrator feel? +
                                              2.) What needs was the perpetrator trying to meet? +
                                              3.) How dit the victim feel? +
                                              4.) What needs weren't met by the victim? +
                                              5.) What needs weren't met on the part of the perpetrator?
| What the punishment will be? | What can we do to repair the harm? | 1.) What can we do to fulfil these needs?
|===========================

** link:https://slideplayer.com/slide/6835782/[Building Positive Relationships Through Restorative Justice - Joan Packer]
** link:https://www.youtube.com/watch?v=Ccz55SO4Ah4&feature=youtu.be&t=2221[Howard Zehr - Human Rights Meets Restorative Justice: 37:01-???]
** Phases of restorative justice by NVC link:...[NVC Creating a life serving system within yourself ???]

== Play

by Peter Gray, author of _Self-Directed Education [SDE]_

Ich kämpfe nicht. Ich übersetze alles in die Sprache des Lebens.

Ich arbeite nicht. Ichspiele. Ich lerne. Ich mache.

Hypothese: Jede Aktivität hat in sich Elemente eines Spiels.

Hypothese: Jede Aktivität ist ein Spiel, solange sie unsere Bedürfnisse erfüllt.

Hypothese: Alles, was ich mache, mache ich, um meine Bedürfnisse zu erfüllen.

* *Don't do anything that isn't play.* link:...[M.B. Rosenberg: ???-???; Joseph Campbell]

** How to make every activity a play? +

*** *It will be play if you're connected to your needs.* link:...[M.B. Rosenberg: ???-???]
*** Everything I do is play.
*** I do everything that serves life as if it was play.
*** I do everything as if it was play. [At least I try :P ]

*What is play?* +
Play is an activity that has following _[5 - may be more, may be less]_ characteristics:

. It's freely chosen and self-directed.

    * Freedom to change the rules.
    * Freedom to choose the activity.
    * Freedom to quit the activity at any time.
    * Balance between skills and challenge: what you can do and what can be done [Flow]. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]

. *You are doing it for its own sake.*

    * The activity is autotelic. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]
    * You are not doing it for some reward that's outside of the play itself.
    * Means over the end.
    * Process over product.
    * Skill over result.
    * Intrinsic over extrinsic.
    * The joy of play is in the doing, not in the end product.
    * You do the activity do make the next step in the activity. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]
    * You do the activity not because of the end result. +
    You do the activity because you want to do the activity. Because you like how you feel when you do the activity. And you like it so much you want to do it every day. link:https://youtu.be/nraBwnT2XlY?t=255[bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 4:15-5:02]
    * How you feel is more important than what you do. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * The act of learning is more important than how well you are learning. link:???[Alfie Kohn: ???-???]

. *Play is always guided by rules.*

    * The rules create the structure. The structure is the rules.
    * There is no such thing as unstructured play. Play always has a structure. Play is not a random activity. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * The structure is always determined by the players. The players themselves choose which rules they want to follow. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * Consensual rules [M.B. Rosenberg]

. *Play involves elements of imagination.*

    * Play encourages hypothetical thining: "If this was true, what follows from that?" link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * *Hypothetical thinking is the highest form of human thinking. _[IQ]_* link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * *Observing without evaluating is the highest form of human intelligence. _[EQ]_* link:???[Jiddu Krishnamurti]
    * That's why we can plan for the future, prepare for tomorrow, invent things. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * None of these abilities can be taught by lecturing, although they are essential life skills. These abilities can only be obtaines through practical experience, through practice. For children is this practical experience, mainly, play. They are preparing themselves for a responsible life. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * Both, hypothetical thinking and observing without evaluating helps me to concentrate on what's alive in me and other people - our feelings and needs. Even if it involved screaming my feelings and needs!

. *Play involves relaxed, highly attentive, but not highly stressed attitude.*

    * Why not highly stressed?
    ** Because there are no consequences to it.
    ** You are free to fail.
    ** You are not going to blame anybody. [There is no need for it.]
    ** There is no trophy; there is no cake. link:???[The cake is a lie. (Portal)]
    ** You are not going to get an F from some teacher.
    ** You are free to quit.
    ** You are not concerned about even succeeding. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]

. *Play always involves challenges.*

    * One of the challenge is: "How much fear can I tolerate?".
    * You are playing with your own fear.
    * We develop a sense of our own abilities.
    * We learn how to manage fear.
    * *I can feel fear, and I can survive it.*
        ** This discovery can be very empowering. It makes you less affraid of life. It helps you live your life courageously. Things can happen that are scary and I can deal with them.
        ** If you are deprived of this kind of risky play that involves deliberately putting yourself into a scary situation, then the first time you feel a real emergency in your life, you might fall apart because you didn't have the opportunity to practice how to deal with fear, how to control your body, how to control your mind, [how to control your own emotions and show yourself empathy,] when you feel fear.
    * If something serious happens, [or you get stuck,] ask for help.
    * *To protect children from any possible harm by nnot allowing them adventures or risky play, and never allowing them to get out of our sight and control, is having harmful long-term consequences on children.*
    * Someone who is willing to take more eisks in the daily life will not only become better and improve, expand the comfort zone, but also more fulfilled, happy and satisfied. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * You'll learn how to accept and learn from failure. It leads to sustainable resuslts, more engagement, satisfaction, [instrinsic] motivation. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * When you stop taing risks, you stop living a life. link:???[Cedric Dumont - From Fear to Flow: ???-???]

== Nonviolent Communication (NVC) / Gewaltfreie Kommunikation (GFK) / Nenásilná Komunikácia

Nonviolent communication is a way of

* talking (language),
* thinking (emotional intelligence),
* communication (communication skills, dialogue) and
* using power (means of influence, management, parenting)

Sources: +
link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=614[Self Empathy: 10:14-11:16] +
link:https://www.youtube.com/watch?v=GZnXBnz2kwk&feature=youtu.be&t=92[CNVC org Session #1 Introduction Nonviolent Communication Training Course Marshall Rosenberg: 0:01:32-0:01:57]

* What is the message of all religions?
** To live compassionately. To not do anything that isn't play. Unfortunately, religions are vague in the specific ways, how to live compassionately and enjoy compassionately.
* What skill do we need to live compassionately?
** Language, thinking, communication and use of power.
* Why don't we educate peopleto live compassionately, but instead we educate them to enjoy violence?
** We have been educated to enjoy violence, in order to contribute to the structures [institutions] of the society. In these structures are people that claim to be superior and know what's right for others, and have the power to impose what they believe is right on others. That way of living requires a certain way of thinking, communication, talking and using power. That is the problem. [The sustaining of the structures is more than contributing to the well-being of the society.]
* How are we meant to live?
** To live naturaly, compassionately.
* How to live natrally?
** Natural living is the usage of our power to enrich my and other people's needs.

* The entire concept of a mental illness and the attribution of the violence as a cause of the mentall illness takes the focus away from the education [and upbringing] that the structures provide which create the [environment for] violence.

=== Nurturing, parenting, upbringing to violence

Source: link:???[M.B. Rosenberg - Erziehung zur Gewalt]

. Educate people to use *jackal language* link:???[(CNVC Training Session 1 - ??? - ???)]
* Jackal language = Static language
** A language of domination, Punishment (criticism, blame), Rewards (praise, compliments)
** A language that is
*** disconnected from life [i.e. feelings and needs] and
*** violence provocative link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6137[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 1:42:17-1:44:56]
in order to maintain domination structures.
** A language that makes it difficult to resolve differences. link:???[NVC Denmark Workshop, CNVC Session 1]

* Educate people to think what's wrong with them. Educate people to think what they are, so that they in each moment wonder whether they are right or wrong, good or bad, normal or abnormal, appropriate or inappropriate etc. +
Judge yourself with moralistic judgements.

* Educate people to think what other people are. Educate people to think what's wrong with other people. Whether other people are normal or abnormal, kind or unkind, responsible or irresponsible, selfish or generous, lazy or hard-working etc. +
Judge other people with moralistic judgements.

* Educate people to think what other people think of them. What will other people say? What will other people think?

* Teach people the concept of *deserve* link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=1230[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 20:30-], link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6137[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 1:44:56-1:45:15]
** Teach them that you need to deserve love. That you have to earn it.
** But if they behave in a way that's judged _bad_, teach them they deserve to suffer.
** Teach them that if other people behave bad, they deserve to suffer.
** We've been systematically educated in a way that makes violence enjoyable. [e.g. through media, television, society, institutions and religion]. ... Always for good reasons: to serve the God and serve the country. link:https://youtu.be/jArsTeP66FE?t=6222[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg: 1:43:42-1:44:56]
** The concept of deserve makes violence enjoyable.
** There are whole cultures and countries who speak nonviolent communication [Rojava - northern Syria, Orang Asli - Malaysia]. They have hardly any violence. They don't know what punishment means. It doesn't make any sense to them, why one person wanna hurt another person. It only makes sense when you believe they deserve it. Why do they deserve it? Because are labeled negatively by moralistic judgements. link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6528[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg: 1:48:58-1:49:18]

* Teach them that punishment is sometimes necessary. +
Teach them to use punishment to get their needs met.

* Teach them to use rewards to get what they want.

* Teach them to use guilt and shame to manupulate us.

* Teach them to do things to get influence out of the concept of duty and obligation.
** This requires teaching them a language that denies choice. *Amtssprache*.
** Such as there are some things you gave to do. That you have no choice. It's your duty and obligation.
** Amtssprache link:???[M.B. Rosenberg - San Francisco Workshop ???-???], link:???[Eichmann in Jerusalem]
*** a language that denies responsibility and denies choice, i.e. it implies that we have no choice
*** a language that denies reponsibility for my actions
*** a language that implies that I have no choice
*** Examples: +
**** "There is no alternative." [TINA; you must!] - link:https://en.wikipedia.org/wiki/There_is_no_alternative[Margaret Thatcher]
**** "There is no such thing as society." - link:https://newlearningonline.com/new-learning/chapter-4/margaret-thatcher-theres-no-such-thing-as-society[Margaret Thatcher]
**** "There are just some things you have to do!"
**** *must, should, ought, can't, have to*
**** *it's the [company] policy, rule, law, order, tradition, habit*

. Teach people *retributive justice* link:???[(CNVC Training Session 1 - ??? - ???)], link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=1230[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 20:30-]
* It's all about the word *deserve*.

But why did we start to educate people to enjoy violence?

Because this education works in sustaining dominantion structures. [M.B. Rosenberg - Experiencing Needs As Gifts] +
This education makes us obedient to authority. +
This language makes us obedient to authority. link:???[CNVC #1 ~31:00]

What happens to people if we educate them to enjoy violence?

. They become nice, dead people. +
They do what they're told by the people above. They do what their parents want. They do what their teachers want. What the bosses want. What the government wants. They are nice, dead people.
. They become monsters.

The education to violence is just a temporary thing. Although it takes for approximately 5000 years. By the paleontologist Pierre Teilhard de Chardin, we are gradually returning back to the ways of living that are more natural.

Everything that we do out of penitence or self-hate, fear of punishment, desire for reward, concept of deserve, duty, obligation, submission, rebellion, giving in or self-sacrifice, buying love, guilt, shame, anger, depression, everybody pays for it. Therefore *don't do things for other people. Do things only when you do so willingly to enrich your and other people's life.* If you do things from the energy that damages life, it will affect commitment to values that serve life, care about other people, depth of thinking, interest in learning, preference to challenge link:???[M.B. Rosenberg] link:???[tilt parenting], link:???[alfie kohn ofjcc]

== Fascism

Mussolini created the _Fasci Italiani di Combattimento (Liktorské zväzky prútov)_ which consisted mostly of men and *glorified violence*. Violence lies at the heart of fascism. link:https://www.youtube.com/watch?v=uE-ewzt9Yfg[What is Fascism? | World History Project: ] +
_Liktor_ - služobník, ktorý chráni kráľa.  link:https://de.wikipedia.org/wiki/Liktor[Liktor - Wiki]

*What is Fascism?* link:https://www.mtholyoke.edu/courses/rschwart/hist151/Paxton_Fascism/Paxton_mainpoints.htm[Robert Paxton] +
Fascism may be defined as +
a form of political behavior +
marked by obsessive preoccupation with community decline, humiliation, or victimhood +
and by compensatory cults of unity, energy, and purity, +
in which a mass-based party of committed nationalist militants, +
working in uneasy but effective collaboration with traditional elites, +
abandons democratic liberties +
and pursues with redemptive violence and without ethical or legal restraints goals of internal cleansing and external expansion.

* Fascism, authoritarianism or populism support *power over* people, not *power with* people [like Mary Parker Follett did].

== Quotes

*The Montessori Method*

* Chapter 15: Intellectual Education (librivox)

** 0:49-1:33

    *** The directress/educator intervenes to lead the child from sensations to ideas, from the concrete to the abstract and to the association of ideas. For this, she uses a method which isolates the inner attention of the child and to focus it upon the perceptions. As in the first lessons, his objective attention was fixed in isolation upon single stimuli. The teacher, in other words, when she gives a lesson limits the field of the child's consciousness to the object of the lesson. As, for example, during the sense education, she isolated the sense which she whished the child to exercise.
        **** When the teacher gives a lesson, he limits the field of consciousness of the student to a single stimuli - to the object of the lesson - e.g. by exercising only one of the student's senses at a time.

** 1:39-1:53

    *** The educator limits his/her intervention to the greatest possible extent, and at the same time shows care for the other person's well-being by *requesting* the other person to stop the autoeducation when the educator sees that the other person feels tired.
    **** Intervention: As much as necessary, but as little as possible.

** 4:56-6:23

    *** But, if he has not done this, that is, if he makes a mistake, she does not correct him, but suspends her lesson to take it up another day. Indeed, why correct him? If the child has not succeeded in associating the name with the object, the only way in which he succeeds would be to repeat both the action of the sense stimuli and the name. In other words, to repeat the lesson. But when the child has failed, we know, that he was not at that moment ready for the psychic association which we wished to provoke in him. Therefore, we choose another moment. If we correct the child by saying "No, you have made a mistake!", all these words, which, being in the form of reprove, would strike him more forcibly and would remain in the mind of the child retarding the learning. On the contrary, the silence which follows the error leaves the field of consciousness clear and the next lesson may successfully follow the first. In fact, by revealing the error we may lead the child to make an undue effort to remember, or we may discourage him. And it is our responsibility to avoid, as much as possible, all unnatural effort, and all the pressure [depression].

** 8:08-8:17

    *** The teacher carefully watches when and how the child arrives at the generalization of ideas.

** 9:13-9:21

    *** The goal of education is to promote the *spontaneous* development of a human. / Das Ziel der Ausbildung ist, die spontane Entwicklung des Menschen zu unterstützen.

** 10:50-11:20

    *** We can not create observers by saying "Observe!", but by giving them the power and the abilities for these observations. And these abilities are obtained through the education of the senses. Once we have aroused such an activity, autoeducation is assured. Refined, well-trained senses, lead us to a closer observation of the environment, and this with its infinite variety attracts the attention and continues the psychosensory education.

** 13:16-13:28

    *** The spontaneous development of the child continues indefinitely and is in direct relation to the psychic potentiality of the child himself and not with the work of the teacher.

** 13:28-13:39

    *** The spontaneous activity starts from the education of the senses, and is maintained by observation.

** 13:29-13:49

    *** The human receives his/her ability, not from the education given by the master, but from special acuteness/sensitivity of his/her senses.

** 13:49-14:03

    *** When somebody is in an environment where he/she can apply his senses in his/her's spontaneous activity, the activity itself gives him/her the pleasure, joy and fulfillment

    **** Develpoment of intrinsic motivation (Alfie Kohn)
    **** The activity becomes *autotelic* (Mihály Csíkszentmihályi - Flow)
    **** Process over Product (Rachel Rainbolt, Peter Gray)

* Montessori put her theories into practice in *Casa dei Bambini* in San Lorenzo, 1907. +
Until that time people had thought of children as empty vessels or cups which had to be filled with knowledge. Knowledge was simply poured into them. All he children had to do was to sit still and take it in. Maria Montessori observed that children learned in a very different way. That they spontaneously reached out for knowledge, that they explored they created. Looking at very young children we can see the spontaneity. And in fact, a lot of what was happening in schools was preventing that and stopping children [from being spontaneous]. +
She believed that, if given the opportunity, children would rather focus their attention on work than idleness. +
Montessori discovered so many years ago what modern research is confirming today: that children learn best from their own activity. They learn best when they're active and exploring. And she found a way to make this possible. +
It was a scientific experiment. What she observed in a San Lorenzo project became the basis of Montessori education. She created a new environment. One completely diffrent from mainstream schools in Italy. +
All inovation in Montessori education didn't come about necessarily because Montessori said "We have to do that!". She saw "Well, this is something that I observed children do, and I'm curious how this will affect their experience." And then she applied the science to it. +
As she watched the children engaging with the new materials, she observed that this formally naughty children thrived on learning. They would work for the sake of working and would become completely engaged in their task. +
One child of 4 became so engrosed in her work that when Maria had the other children dance around, and make as much noise and fuss as possible, the girl never deviated from her task. Maria then lifted her from her seat, but the girl just continued working. [Is this a demonstration of *Flow* by Mihály Csíkszentmihályi?] +
Maria also observed that children had an innate love for order. +
The parents often say "Oh, my child doesn't like to tidy up at all." But actually they enjoy doing it, they like the idea of putting something back in order so that it's ready for someone else to use. And at the end of the day you'll often find children on their own deciding around the children's house rolling up matts, making things straight on the shelf. It's a sense of caring for a space, caring for the community. [Is this a demonstration of *The Altruistic Personality* from Samuel and Pearl Oliner?] +
She thought them simple acts of cleanliness, like how to blow their nose. No one had ever told them how to to this before. Montessori understood that children have a sense of personal dignity often not recognized by adults. Neither they require rewards or punishments. The acts they were engaged in were rewarding enough. But the most surprising and remarkable of all her observations was when these children without her orchestrating it taught themselves to read. She had introduced some paper letters mounted on wood as a multisensory tool. The children could trace them with their fingers, feelilng the shape and learning the sound of the letter. She gave them no other instructions. +
The children began put together sounds of words they knew. When they heard a word they didn't know, they could decompose it to letters by sound and write it down. *Montessori managed to ignite an explosion of ideas in children.* +
The *Casa dei Bambini* was an enormous success. Montessori method was starting to get more popularity and attention. Legislators, teachers, parents and doctors [were impressed by the results of this method and] soon started to use this method in their practice. In 1909 she published her book *Il metodo della pedagogia scientifica applicato all'educazione infantile nelle case dei bambini*. In 1912 this book was translated to English and published with the title *The Montessori Method*. The book was translated into multiple languages and spread across the world. link:https://www.kpbs.org/news/2014/jul/16/extraordinary-women-maria-montessori/[Image: Popularity of Montessori method in the world in ~1912]. *Almost the entire world wanted to use Montessori method.* Even the academia. Maria started a revolution in education. link:https://youtu.be/TXqeTYHn0p4?t=1282[(Maria Montessori: 21:22-28:03)] +
By 1913 were in USA almost 100 Montessori schools. +
Then in 1914 war broke out across the Europe. +
To Maria, the appaling devastation convinced her that *there should be a connection between education and pacifism*. "Now comes the time for our work. We are working for peace and humanity midst the inhumanity of war. Our eyes are turned to a little child where lies the future and the hope of our world." +
In France and Belgium Montessori schools were set up for the orphans of the conflict. +
After the first world war, Maria Montessori returned to Italy, only to walk into the path of the world's most ambitious man. *Benito Mussolini* was impressed ... by the discipline of the students educated by Montessori method. He wanted to build a new efficient and industrial country. Mussolini supported Montessori and her's education. ... Mussolini and Montessori cooperated, but neither of them were happy with it. *The trouble was that Montessori believed that children learn best as  [responsible,] independent, free thinkers.* But free thinking was not something that Il Duce was intrested in. *Mussolini's aim was to create a nation of [obedient,] disciplined and loyal fascist.* The idea of Montessori education was educating people to think for themselves, and act for themselves, and was *scientific* rather than political. ... *"The goal [of education of Mussolini and fascism] is total indoctrination. From childhood to the soldiers grade. Fascism shapes young minds with Italy's destiny and the beauty of war."* In 1931 Mussolini announced that all schools must conform to fascism. Maria refused outright. Maria Montessori and her partner left in a hurry. In 1931 she lef her homeland never to live there again. *Within months Mussolini closed all Montessori schools in Italy.* ... Maria Montessori met with Ghandi in London. They had a great connection. Ghandi supported her philosophy: the element of community, an education that can work with all children in all cultures. *Hitler closed down all Montessori schools in Germany. In Berlin, all Montessori books were thrown on burning piles.* [Mussolini and Hitler (and fascist) didn't like citizens that ask "Why?" and complain about regulations] link:https://www.youtube.com/watch?v=TXqeTYHn0p4&feature=youtu.be&t=1785[Maria Montessori: 29:45-38:47], link:???[Episode_143-Maria_Montessori-thehistorychicks: 1:24:01-1:40:38] +
The world piece can only be achieved by the education of the children. link:https://www.youtube.com/watch?time_continue=7&v=TXqeTYHn0p4&feature=emb_logo[Maria Montessori: 43:19-43:28] +
But in the absence of Maria Montessori, much of her work had been forgotten. link:https://www.youtube.com/watch?v=TXqeTYHn0p4&feature=youtu.be&t=2638[Maria Montessori: 43:58-44:04] +
In 1945 Maria Montessori started to revive and reestablish her education in preschools and schools in Europe. Many of the creative people benefitted from early Montessori education. *The life should be challenging, and the challenge should be fun. [Larry Page & Sergey Brin - Founders of Google - both educated in Montessori method]* link:https://youtu.be/TXqeTYHn0p4?t=2647[Maria Montessori: 44:07-46:00] +
*Don't look at me. Look at the way I'm pointing.* link:https://youtu.be/TXqeTYHn0p4?t=2647[Maria Montessori: 47:21-47:40]

* Maria Montessori didn't see any virtue in obeying. link:???[Episode_143-Maria_Montessori-thehistorychicks: 1:35:48-1:35:53]

* Few parents have the courage and independence to care for the children's happines than about their success.
[Erich Fromm; Alfie Kohn - Unconditional Parenting: Moving from Rewards and Punishments to Love and Reason: ch. 5 - "Pushed to succeed", p. 75
; Alfie Kohn at the OFJCC - Performance vs. Learning - The Costs of Overemphasizing Achievement: ???-???]

* ... because if I persuade you that something ... you're doing with kids is getting in the way, not what I happen to like, but of your own long-term goals for other people then either you have to rethink the practice or you have to rethink the outcome.
(Alfie Kohn at the OFJCC - Performance vs. Learning - The Costs of Overemphasizing Achievement: 10:45-11:04)

* There was less cheating when [the teachers] made it clear that the point was to enjoy the learning, when understanding mattered more than memorizing, and when mistakes were accepted as a natural result of exploration. link:alfiekohn.org/???[Alfie Kohn - Who's Cheating Whom, paragraph 11], link:https://montessoritraining.blogspot.com/2013/09/montessoris-three-levels-of-obedience.html[Mistakes - Montessori]

* Leadership is not defined by the exercise of power but by the capacity to increase sense of power among those led. The most essential work of the leader is to create more leaders. link:https://scontent.fbts2-1.fna.fbcdn.net/v/t1.0-9/31781853_10156828091695628_8027792006530990080_n.png?_nc_cat=106&_nc_sid=8024bb&_nc_ohc=sdfVZfeBPpoAX84ENlX&_nc_ht=scontent.fbts2-1.fna&oh=35dff8d3e47555a204245ba9ae13be32&oe=5F25FD09[(Mary Parker Follett)]

* There are three ways of dealing with difference: domination, compromise and integration. By domination only one side gets what it wants; by compromise neither side gets what it wants; by integration we find a way by which both sides may get what they wish. [NVC supports integration ;) ] link:https://www.toolshero.com/toolsheroes/mary-parker-folett/#:~:text=Mary%20Parker%20Follett%20quotes,is%20to%20create%20more%20leaders.%E2%80%9D[Mary Parker Follett], link:miki.kashtan_2020[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 30:14-32:57)]

* Internalized Powerlessness: link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=1008[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 16:48-22:20)]

    ** "Can I ...?" - that's how the upbringing to powerlesness and obedience starts. +
    Alternative questions: "Will I take <something> / Will I <do an action>? / I want to <...> What do you say?"
    ** When I say someone, e.g. a child, that he *can not do* something, then I interfere with what is true physically. I not only control the others, but also mess with their understanding of the reality. If I tell the somebody *No, you can not turn on the TV* when in reality I'm saying *I really don't want you to turn on the TV, and if you turn on the TV I will punish you!*
    ** Between the somebody's action and my reaction is my choice.
    ** We are not sufficiently inner oriented to our own needs and our willingness to decide which consequence to my action am I willing to accept. So Nonviolence is to face whatever will be the consequeces of our action so long as they are inline with our needs.
    ** If we are trained to be fearful of our consequeces we're less likely to feel powerful.
    ** Samuel P. Oliner, Pearl M. Oliner - *The Altruistic Personality*
        *** *People who saved Jews, tended to come from nonpunitive households.*
        *** [big]*If you come from a nonpunitive houshold, you're less oriented towards fear, and more more oriented towards needs and intrinsic motivation.*

* Flatpack Democracy - Frome, England link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=4434[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 1:13:54-1:14:39)]
    ** ... if you don't have facilitation, you're less likely to have an integrated result.

* *Instead of believing somebody's words to be true, I believe their experience to be true.* ... So I put my focus on their feelings and needs.  ... On their experience behind the words. And the whole art is the art of guessing. [Focus on their humanity, on their observation, feelings and needs and requests.] link:https://www.youtube.com/watch?v=KX_tgRM84RA&feature=youtu.be&t=4515[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 1:15:15-1:15:59)]

* As much as possible in as little time as possible vs The best of possible in whatever time necessary to do it. link:https://www.youtube.com/watch?v=bux3TJWvyqE&feature=youtu.be&t=98[(Manfred Max-Neef - The Benefits of a Slow Life: 1:38-1:51)]

* _Book - James Gilligan - Violence: Our Deadly Epidemic and its Causes_. +
Every act of violence somewhere is an attempt to create justice to right a wrong that happened before. That wrong may happen two seconds before or might have happened 50 years before. But there's somewhere in the person's deep organism some wrong that have happend that needs to be righted, and the violence is an expression of that. Now we can all understand the pull to justice *but why does it go to violence rather than to other means? Because we feel shame. All the people that he had talked with essentially without exception were carrying boatloads of shame* in them about who they are, about what has happened to them, about what they want, and most particulary, about anything that had to do with tenderness, with any need for love, for connection, for appreciation.* They had so much shame about it. One of the things that are so clear coming out of this is that *punishment makes things worse because it increases shame. If shame is at the root of violence, punishment is not going to work. It only going to make the person get into a deeper loop* about who they are now. "Not only I'm ashamed about everything else, now I'm ashamed about the things that I've done and I've been punished,  I've been ostricized, there's no room for me." link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]

* [Shame] is not only now more common, its purpose has shifted from protecting the group [,i.e. the community] to protecting the powerful. So *most of us walk around with some degree of shame that is just there in the background that keeps us from doing things.* And *we get shamed for what we want. If you look at early childhood, you are made to be ashamed for wanting what you want, for moving spontaneously, for going for what is of direct interest to you, for saying what is true for you, everything that is about being you is put into question.* ... This is why I decided to become 100% shameless. Why is this funny? Because the word _shameless_ describes someone who is a terrible person, totally outside of the norm. It's as if we're told that having a certain amount of shame, constatly, is a good thing. link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2029[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 33:49-34:40, 1:34:51-1:35:23]

* Authorities figures tend just by nature to use shame. link:https://www.youtube.com/watch?v=2KXwnbsQUrI&feature=youtu.be&t=123[(Restorative Justice Continuum - Howard Zehr Ph.D EM 2:03-2:12)]

* Shame is calling me to do self-reflection. And that is sometimes very painful to be willing to do my self-reflection, and to stop projecting my frustrated feelings onto other people. link:https://www.youtube.com/watch?v=0pleCht2jN4&feature=youtu.be&t=439[(NVC Guilt and Shame - Kirsten Kristensen: 7:19-7:40)]

* There's a moral transformation, transformation of basic political categories which what a revolution really is. But I think in order to go further with this we need to change our basic categories of what labor is. It's just as in the 19th century, the idea of labor theory of value as material production, was incredibly effective, although it turned out to have very real limits which allowed it to be reversed. We need to change our conceptions of labor to one that starts from caring labor. *What society is, is a process of the mutual creation of human beings. So not just the creation of material world, it's a creation of each other.* That's what we're doing. That's what we're doing right now here. Caring, education are the primary things. There is a free education movement right now in Amsterdam and London, there is a huge student movement emerging. I find this very exciting. One of the first things that they're putting in their plank is that *"We've been told that the purpose of education is to improve economy. We want it backwards. The purpose of the economy is to improve education. To give the people the freedom and leisure to understand the world. To learn things."* Our perspectives are totally backwards. *If you take education as part of that broader process of caring, mutual nurture and mutual support that creates the world by which we create each other.* I think that if we begin to look at the world that way, well of course that's the way the most people who ever lived get see the world. Most societies it's just assumed that material production is just one subordinate moment in a broader process by which we create each other - creating people. *Thus factory labor is a form of carying labor if the stuff you're producing in a factory is that people care about, is that people need. But it's sort of second order form. It's things that are useful in what's the really primary business of human life which is our taking care of each other. And I think that if we transform our categories, begin to rethink the world in that and make that common sense, then we'll truly have achieved a revolution.* link:https://www.youtube.com/watch?v=2QUdrdgPI-I&feature=youtu.be&t=1837[(David Graeber: All Economies are Ultimately Human Economies (2015): 30:37-33:23)]

* So, I suggested that instead of production and consumption we substitute care and freedom. Perhaps caregiving and care is really that work we do which maintains and increases other people's freedom of which the paradigm would be *play*. Because play is action done for itself. Because what is caregiving labor? You take care of kids so they can play. link:https://www.youtube.com/watch?v=kikzjTfos0s&feature=youtu.be&t=2958[On Bullsh*t Jobs | David Graeber | RSA Replay: 49:18-49:38, link to Peter's Gray - Play ???]

* Practice does not make perfect. Only perfect practice makes perfect. +
 Übung macht nicht perfekt. Perfekte Übung macht perfekt. +
 Tréning nerobí majstra. Majstrovský tréning robí majstra. +
 link:...[(Vince Lombardi - baseball player)]

* It's not practice that makes perfect... but perfect practice that makes perfect. +
  Es ist nicht Übung die perfekt macht..., sondern perfekte Übung, die perfekt macht. +
  Nie je to tréning, ktorý robí majstra..., ale perfektný tréning, ktorý robí majstra. +
  link:???[(Cal Ripken Sr.)], link:???[(Daniel Markovits - Meritocracy and its Discontents: 48:40-49:30)]

* Our greatest glory is not in never falling, but in rising every time we fall. +
  Unsere größte Ehre liegt nicht darin, nie zu fallen, sondern darin, dass wir jedes Mal aufstehen, wenn wir fallen. +
  link:???[Confucius]

* I've learned that people will forget what you said, people will forget what you did, but *people will remember how they felt with you.* +
  Ich habe gelernt, dass Leute vergessen, was du gesagt hast, Leute vergessen, was du gemacht hast, aber Leute werden sich daran erinnern, wie sie sich bei dir gefühlt haben. +
  link:???[Maya Angelou]

* This is what I love about friends. Good friends agree with my jackal. Actually, that's the most dangerous thing on the planet. If somebody else  agrees with my jackal, now I can believe my jackal to be true. This is in the society how we create jackals. We call it *"sympathy party"*. It's very different than empathy. Sympathy party is to agree with someone else's jackal. ... In that moment it's the most delicious for her. "Oooh! Thank you! Finally somebody agrees that I'm right and he's wrong!". *It's a pleasure for a short term* because then you go back home, pumped up by this sympathy party, you come to the other person, and you say: "You see? There's really something wrong with you!". *And then you'll have a bigger fight.* link:https://youtu.be/KX_tgRM84RA?t=370[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 6:10-8:08)]

* Out beyond the ideas of right and wrong there is a field. I'll meet you there. / We'll meet us there. +
  Jenseits den Ideen von richtig und falsch gibt es einen Platz. Ich treffe dich da. / Wir treffen uns da. +
  Za hranicou dobrých a zlých myšlienok je miesto. Tam ťa stretnem. / Tam sa stretneme. +
  link:???[Rumi - poet]

* If you need to do something, you can do it badly. +
  Wenn du etwas tun brauchst, kannst du das schlecht tun. +
  Keď niečo potrebuješ urobiť, môžeš to urobiť zle. +
  link:???[Gilbert Keith Chesteron]

* Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away. +
  Perfektion wird nicht erreicht, wenn es nicht mehr dazuzugeben gibt, sondern wenn es nicht mehr etwas wegzunehmen gibt.
  link:???[Antoine de Saint-Exupéry]

* Pane, ty sa postaraj. Dôverujem Ti. (Otec Ľuboš ???)

* Minimalism doesn't mean to have as little things as possible, but to have such amount of particular kind of things that one necessarily needs and are important for him/her. +
  Minimalismus bedeutet nicht so wenig Sachen wie möglich haben, sondern so viel solchen Sachen haben, die er/sie notwendig braucht, und sind wichtig für ihn/sie. +
  Minimalizmus neznamená mať čo najmenej vecí, ale mať iba toľko takých vecí, ktoré nevyhnutne potrebuje a zaleží mu/jej na nich. (me)

* At shopping as yourself: "Will this thing bring value to my life?" [What needs will this thing fulfil in my life?] +
  Beim Einkaufen frage dich: "Wird dieses Ding Wert in mein Leben bringen?" [Welche Bedürfnisse erfüllt dieses Ding in meinem Leben?] +
  Pri nakupovani sa pytaj: "Prinesie toto hodnotu do mojho zivota?" [Aké potreby naplní táto vec v mojom živote?] +
  link:???[The Minimalists - Youtube Podcast]

* Vyhadzovacie pravidlo - najprv odlozit _nepotrebnu_ vec bokom na chvilu (par dni, tyzdnov, mesiacov). Pokial ju nebudem potrebovat pocas toho ako bude odlozena, zbavim sa jej.

* The world is shaped by people who believe and trust the future and their past experiences, abilities and intuition. The more you can trust the future, the more you can engage in the present moment. And vice versa. link:???[Cedric Dumont - From Fear to Flow: 13:19-???]

* Educated risk-takers enjoy to study things on their own. We know the consequences. We know there is something at stake. Everything is prepared. Preparation plays a vital role. link:???[Cedric Dumont - From Fear to Flow: ???-???]

* If the risk is bigger that the satisfaction, don't do it. +
  If the satisfaction is bigger than the risk, do it. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]

* *Emotions -> Actions -> Habits -> Life -> Destiny* +
  The more more positive the emotions are, the more chances that the rest will follow. Fear is a necessity in a high rist environment. It reinds you that you're onto something important with high consequences. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]

* Staying in touch with your own mortality helps you to make decisions that are meaningful to you. link:???[Cedric Dumont - From Fear to Flow: ???-???]

* When you're tense, you can't feel it. And when you can't feel it, you can't recreate it. [Relaxed attitude helps me to experience my dream feelings again.] link:???[Doug Newburg - RPM Researchgate link ???]

* ... to make business more spiritual we must make business more humane. link:https://sci-hub.tw/10.1023/b:busi.0000005730.37745.07[Searching for Spirituality in All the Wrong Places - Journal of Business Ethics - Conclusion]

* The structures focus more on self-regulation than on expressing the student's feelings, needs and ideas. link:???[Alfie Kohn - OFJCC: ???-???]

* *Tests* measure what matters least. If the teacher needs to give a est, the teacher needs help in how to teach and assess. No matter whether they're standardized or not. Tests create more anxiety and achievement pressure. link:???[Alfie Kohn - OFJCC: ~1:23:00]

* *Homework* is unnecessary. Research shows no benefit of homework before high school. And even there it's questionable. So why do we persist? BGUTI! - an abbreviation for "Better get used to it!". +
Homework is literally all pain and no gain. It produces frustration, exhaustion, family conflicts and nagging, less time for kids to do what they care about when they get home, and loss of interest in learning. Homework effectively extinguishes curiosity [when the kid doesn't do it and the teacher or parent punishes the kid physically or psychologically with shame, guilt, the concept of duty, obligation or deserve]. There is no sacrifice in not giving homework academically. +
"As I got better in teaching, I assigned less and less homework. Now I assign none." Getting rid of homework was intellectually beneficial. "Students talked during the lesson about things they learned at the subject and compared them with current events in the world." Homework is a tool for the school how to manage family time. The family needs to have the freedom to decide how to spend its time! Instead of making the students work a *second shift* of academeics at home. +
Six hour of academics is more than enough.

* Talk to your kids at home about what they're learning in school. Never about how well the teacher thinks they're learning!

* If you need to give grades [or evaluate / judge]:
    . write acomment or talk with the student *without* the grades and points. The students will be more interested in learning *only* when there is no letter or number attached to the comment.
    . let the student decide the final amount of points and the final grade or letter. *The good you've done by removing grades from the occasion [and consciousness] and the trust you've shown to the students _far_ outweights the situations in which some students use the system for their advantage.* +
    They will see that obedience contributes to vilence in the same way that grades or tests do.
    
* Self-discipline is more important than empathy. [Alfie Kohn - OFJCC]
    
* People of all ages are more likely to perservere when theu have a chance to make the decisions about the things that affect them. Therefore, if someone doesn't persist, he or shewas to some extent excluded from decision-making, rather than he or she didn't have enough self-discipline. [Alfie Kohn ???]

* Miki

* Kohn

* link:https://www.youtube.com/watch?v=h4fQEn15NgI[The Gun Has No Trigger: David Graeber]
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=507[[8:27]-8:46] ... but if we would incorporate ourselves then we have to have a whole hierarchical structure, president, vicepresident, and those rules and regulations are enforced ultimately by violence ...
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=575[[9:35]-9:47] ... It's because the moment you have large, heavy objects [cars, buildings], they fall under government regulation [endless laws] in various ways, and that regulation is ultimately enforced by violence and that violence is a sort of a thing that we often oversee ...
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=575[[12:09]-13:41] Violence becomes incorporated into our world in ways we don't recognize it. ... Even the structural vivolence: there are forms of inequality and oppression which are ultimately displacement of violence. So racism, is a form os structural violence, sexism, patriarchy. *These are forms of inequality that have violent effects.* ... *It's actually the violence that holds the entire thing together* and away there are displacements of violence. ... They are ultimately based on larger structures where violence is systematically deployed. ... but these structures work best when the violence isn't actually deployed.
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=903[[15:03]-16:05] ... because all forms of action are symbolic and communicative. *What interesting about violence is that it's the only form of action that has any real chance of having a systematic and predictable effect on others without the medium of symbolic communication of any kind.* ... like the're doing something, you shoot them and they stop. ... *But the effects of violence are fairly predictable ... and that very fact gives the violence a quality which almost all other forms of action lack which is that you can relatively predictable effects on the actions of other people about whom you understand nothing.* Any other way you want to affect some other person's actions you have to have some idea what they think is going on, who they think they are, who they think you are, what they want, what they fear. If you shoot them or hit them hard enough is kind of becomes irrelevant. *This is why violence is the preferred weapon of the stupid.*

* Observing without evaluating is the highest form of human intelligence. +
Beobachten ohne zu bewerten ist die höchste Form der menschlichen Intelligenz. +
Pozorovanie bez posudzovania je najvyššou formou ľudskej inteligencie. +
link:???[Jiddu Krishnamurti]

* Ich kämpfe nicht. Ich *übersetze* alles in gewaltfreie Kommunikation. In die Sprache des Lebens. In die Sprache der Beobachtungen, Gefühle, Bedürfnisse und Bitten. I do it for me. link:???[(M.B. Rosenberg)], link:???[Some Palestinian event video], (me)

* Let's find another way of meeting your needs that will be more effective and less costly. [M.B. Rosenberg]

* Everything everybody does at every moment, does it to fullfil his or her needs. [M.B. Rosenberg]

* Ich mache nichts falsch. Ich mache keine Fehler. Giraffen machen keine Fehler. Giraffen machen nur Sachen, die ihre Bedürfnisse erfüllen. Wir machen keine Fehler. Wir machen nur Sachen, die wir nicht gemacht hätten, wenn wir damals gewusst hätten, was wir seitdem gelernt haben. Das bedeutet nicht, dass wir perfekt sind. Das Ziel des Lebens ist nicht perfekt zu sein. Das Ziel des Lebens ist, fortschreitend weniger dumm zu sein. Das Ziel des Lebens ist zu feiern, wenn unsere Bedürfnisse erfüllt werden, und trauern, wenn nicht. [M.B. Rosenberg]

* Empathy vs Forgiveness; If we try to forgive before we've got enough empathy, the forgiveness creates even more pain. Verzeihung bedeutet, dass ich etwas falsch gemacht habe. Niemand macht etwas schlecht oder falsch. Wir alle handeln in jedem Augenblick, um unsere Bedürfnisse zu erfüllen. link:???[M.B. Rosenberg - maybe Creating Life Serving System Withing Ourselves???]

* Alle Bedürfnisse sind wichtig. Ihre Wichtigkeit ändert sich mit der Zeit,  Umständen und Präferenzen. [ich]

* A *need* is a manifestation of life, of divine energy within us. All human beings have the same needs. A *value* is a need with a particular level of importance. The importance of a need changes with time, circumstances and preferences.

* Being alive means to be connected to your feelings and needs. Whenever you feel angry, guilty, ashamed or depressed *take your time* to bring yourself to life [to reconnect with your feelings and needs]. link:...[M.B. Rosenberg Workshop Making Life Wonderful 1/4 55:12-???, M.B. Rosenberg - Take your time]

* I found that 4 year olds learn this [NVC] process much faster than adults. And on much deeper level. ... [Nonviolent communication] is faster [to learn] when people have the purpose of it in mind. ... *The purpose is not to get people to do what you want, but to create the quality of connection that everybody's needs get met [compassionately].* That is a radicaly different story that most of us have been taught. *We have been taught, there is a right and a wrong way to do everything. The authorities know what's right. If you want to make it in this world, you have to do what the authorities say is right.* link:https://www.youtube.com/watch?v=NqJ-0EIsy9U[(Marshall Rosenberg - NVC Workshop 2004 Portland, OR: 1:59:39-2:00:38)]

* link:...[(M. B. Rosenberg - Nonviolent Communication Audiobook ~4:43:00-???)]

* Request vs Demand [(M. B. Rosenberg San Francisco Workshop 1:16:19-1:19:46)]

* How a person responds when it's burdened by a request link:...[(M. B. Rosenberg San Francisco Workshop 1:26:17-1:29:52)]

* Only things that people are saying: Please and Thank you link:...[(M. B. Rosenberg San Francisco Workshop ~1:30:00-???)]

* Criticism = Pain + Unmet Need link:...[(M. B. Rosenberg San Francisco Workshop ~1:34:00-1:42:29, M .B. Rosenberg Resolvng Conflicts with Children ???-???)]

* Hear the yes behind the no. "No" is a "yes" to other needs. Hear the feelings and needs behind the "no". "No" is a tragic expression of a "yes". Say the need! link:...[(M.B. Rosenberg - San Francisco Workshop ???-???)]

* Enjoy my pain, Caressing the Jackal [NVC Rosenberg, Mosenzon]

* please! please!! please!!! link:youtube KdFc2B-tZLc[Marshall Rosenberg - Making Life Wonderful 2_4 - Nonviolent Communication NVC: cca 1:13:00-1:25:00]

* Eye for an eye and the world goes blind link:...[ghandi], link:...[detroit become human]

* We have been trained to be quite habitual in things that are quite unnatural. 

* the importance of present request link:...[Marshall Rosenberg Making Life Wonderful cca 1:31:36-1:33:35]

* ... because *all human beings have the same needs.* link:...[(Film 02 SELF EMPATHY Session 1 - M. B. Rosenberg)]

* Take your time to come from an energy you choose to come from, not from an energy you've been programmed to come from.

* Quotes link:https://www.youtube.com/watch?v=RDkh1al3P9k&feature=youtu.be&t=2487[Speaking Peace - M.B.Rosenberg]

* ??? link:...[(M. B. Rosenberg San Francisco Workshop ~2:26:00-???)]

* No human being is good [no human being is bad - judging is too easy], but all are sacred. link:https://www.youtube.com/watch?v=LdOFhyKACxE[Dr. James Gilligan - On How All Human Beings Are Sacred], link:restoration_justice_part[Rosenberg - Creating a Life Serving System within Oneself]

* https://www.youtube.com/watch?v=bH9t1lAX2UQ Training Session # 2 Marshall Rosenberg CNVC org - 49:20-49:42

* https://www.youtube.com/watch?v=bH9t1lAX2UQ Training Session # 2 Marshall Rosenberg CNVC org - 58:10-1:07:16

* Never give them the power to submit or rebel link:...[(Training Session # 2 Marshall Rosenberg CNVC org - 58:10-???, M.B. Rosenberg - resolving conflicts with children, NVC San Fran workshop)]

* The behavior of somebody else is never the cause of our feelings. The behavior of somebody else is only the *stimulus* for our feelings. The cause of our feelings is our *thoughts* stimulated by the behavior and our *unmet needs* behind our thoughts. ... If we're trying to convince ourselves or somebody else that their behavior is the cause for our feelings, then we're are trying to use *guilt* and *shame* to change the behavior of the other person. Guilt means that the other person is responsible for our feelings. This is not possible because we cannot be responsible for something else outside of ourselves. We are only responsible for our intentions, thoughts, words and actions. The other person is not responsible for my feelings, but it's responsible for his or her intentions, thoughts, words and actions. I'm responsible for how I respond to the response of the other person, and for what ear do I have on, giraffe or jackal, when I'm reacting to their response. Shame on the other hand means that the other person is _bad_ for what they're doing and _deserving_ punishment. By Dr. James Gilligan, shame and ebarassement without nonviolent stimulation is the most reliable predictor of future violence and recidivism. Shame increases violence. Punishment increases shame. Therefore, punishment causes higher rates of violence and recidivism. link:...[(M.B. Rosenberg, James Gilligan, Miki Kashtan)]

* Sometimes I do things that i wouldn't have done if I knew then what I've since learned. +
  Manchmal tue ich Dinge, die ich nicht getan hätte, wenn ich damals gewusst hätte, was ich seitdem gelernt habe. +
  Niekedy robím veci, ktoré by som nebol urobil, keby som vtedy vedel, čo som sa odvtedy naučil. +
  link:???[(M.B. Rosenberg - Fehler)], link:???[(M.B. Rosenberg one of the vimeo videos / corona series)]

* *Rückmeldung bei unerfüllten Bedürfnissen: Kritik / Bitte:* +
  *Beobachtung* [ein Satz] -> *Gefühle* [ein Satz] -> *Bedürfnisse* [nächster Satz] -> *Bitte* [der letzte Satz] +
  oder +
  *Gefühl* -> *Bitte* +
  oder, wenn ich unter Zeitdruck bin: +
  *Bitte* -> *Bedürfnisse* -> *Gefühle* -> *Beobachtung*

* *Rückmeldung bei erfüllten Bedürfnissen: Dankbarkeit:* +
  *Beobachtung* -> *Gefühle* -> *Bedürfnisse*

* *Stimulus / Anreiz* +
  Beobachtung / observation +
  Erlebnis / experience +
  Erinnerung / memory +
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Grund, Ursache / reason, cause* +
  Gedanke (kann auch blitzschnell sein) / though (can also be very quick) +
  Thoughts that are *disconnected from needs (i.e. life)* and *violence provocative* + [M.B. Rosenberg - Film 02 SELF EMPATHY Session 1: 1:43:00]
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Gefühl / feeling* +
  Wahrnehmungen im Körper / sensations in the body +
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Wurzel / root* +
  erfüllte/unerfüllte Bedürfnisse (wenn wir mit den Bedürfnissen verbunden sind) +
  Urteil, Analyse, Diagnose, Interpretation (wenn wir von den Bedürfnissen getrennt sind und mit einfühlungsblockierender Kommunikation verbunden sind)
  
Nothing anybody does can't make us angry. It's only a stimulus.
  
link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=5863[Film 02 SELF EMPATHY Session 1: 1:37:43 (1:39:14)-]

* The map is not the territory. [Alexander Korzhybsky - General semantics], link:???[Rosenberg: Experiencing Needs as a Gift]

* selfish, selfless, self-full [M.B. Rosenberg - Experiencing Needs as a Gift]
  
== Fundamental Attribution Error

Who's Cheating Whom - Alfie Kohn

Daniel Markovits - The Meritocracy Trap

???

== Warum will ich programmieren?

* Lebo potrebujem prostredie, v ktorom sa budem cítiť v bezpečí.
* Lebo potrebujem prostredie, v ktorom môžem rásť.
* Lebo potrebujem tvorivé prostredie.
* Lebo je to práca, pri ktorej môžem tvoriť.
* Lebo programovania som sa bál.
* Lebo sa bojím programovania.
* Lebo pri programovaní sa cítim ponorený.
* Lebo sa chcem naučiť improvizovať.
* Lebo si chcem zlepšiť hypotetické myslenie.
* Lebo chcem rozvíjať svoju fantáziu.
* Lebo sa chcem naučiť samostatne programovať.
* Lebo chcem pracovať cez deň.
* Lebo chcem žiť svoj sen.
* Lebo chcem mať okolo seba ľudí, od ktorých sa môžem niečo naučiť.
* Lebo chcem mať prácu, ktorá mi umožní učiť sa stále niečo nové.
* Lebo chcem mať prácu, ktorá mi dáva zmysel.
* Lebo chcem každý deň dávať zo seba to najlepšie.
* Lebo chcem mať prácu, ktorá pomáha ostatným.
* Lebo chcem byť samostatný.
* Lebo chcem mať moc.
* Lebo chcem mať moc tvoriť veci.
* Lebo chcem mať moc samostatne tvoriť veci.

== Programming

???

== Pilates + Yoga

Active Clinic

???

== Food

* Slow sugars
** Millet/Hirse
** Spelt/Dinkel
** Buckwheat/Buchweizen

* Quick sugars
** Honey
** Jams (prefferably home made)

* Calcium
** Poppy seeds
** Sesame seeds

* Mineral waters with calcium
** Gemerka
** Baldovská
** Kláštorná

* Oils
** Rapeseed oil + mineral water with calcium
** Sunflower oil + mineral water with calcium
** Poppy seeds
** Sesame seeds

* Probiotics
** 5 stems, 50-60B: Custom Probiotic CP-1 Adult Formula
** 11 stems, 11B: Advance Probio24
** *Saccharomyces boulardii:* ExHelico / Yomogi (lactose) / Enterol (lactose)
** Probio-fix inum / Probio-fix (lactose) / Probio-fix ATB assist
** link:https://www.adc.sk/databazy/produkty/pil/uro-vaxom-243674.html[URO-VAXOM] (link:https://www.adc.sk/databazy/humanne-lieky/ucinna-latka/lyzat-escherichia-coli-6364.html[an alternative to Mutaflor]; only with prescription) / Hylak Forte

* Food supplements

** Dietary fiber
*** link:https://www.lekaren-bella.sk/zbozi/3634053/#letak[Prebiolax] / Vemica Psyllium PROBIO PLUS / Vemica Inulín PROBIO PLUS
** link:https://www.adc.sk/clanky/spravna-dispenzacia-digestiva-145.html[Digestion enzymes]
*** Pankreolan forte / Pangrol 20 000 (lactose)

** link:https://www.adc.sk/clanky/spravna-dispenzacia-systemova-enzymova-terapia-63.html[Enzymes]
*** ProfiZYM Plus / link:shorturl.at/kqvwD[H-Protect Enzyme] / EnzyMAX V

** Blood donation
*** link:https://www.adc.sk/databazy/produkty/detail/salus-floradix-zelezo-754866.html[SALUS Floradix Železo]

== Hygiene

* Body
** link:https://www.rosemont.sk/mydla/az-na-kozu-mydlo-musk-2366.html?search_query=az+na+kozu&results=40[MuSK]
** link:https://www.rosemont.sk/mydla/olivove-jemne-mydlo-ponio-1261.html[Ponio] / link:https://www.rosemont.sk/mydla/bambucke-jemne-mydlo-ponio-1257.html[Ponio]

* Teeth
** Curaprox 5460
** ApaCare Remineralisierende Zahncreme / link:https://zubne-pasty.heureka.sk/[dalsie zubne pasty]
** Compostable dental floss - bambus
** Interdental brushes: 0.4mm + 0.7mm
** Tongue scraper
** GC MI Paste Plus (with fluoride) / VOCO Remin Pro / ApaCare Repair / GC Tooth Mousse (without fluoride)

== Why did I create this?

Chcel som sa vyliečiť z tráviacich problémov. Bolestí žalúdka, nafukovania, únavy po jedle.

Doktori to vzdali. Skúšali všetko možné. Nakoniec mi povedali: "Nevieme liečiť niečo, čo nevieme ani diagnostikovať".

Ja som bol zúfalý a vyčerpaný z choroby. Lekári tiež. Tak som po dvoch rokoch prevzal zodpovednosť za svojou liečbu do vlastných rúk.

Do ďalších dvoch rokoch sa môj zdravotný stav výrazne zlepšil. Asi som mal šťastie. Ale liečba psychosomatickej choroby, syndrómu dráždivého čreva (IBS - Irritable Bowel Syndrome), je komplikovaná a zdĺhavá. A nie len vnútorné, ale aj vonkajšie prostredie, hrá rovnako významnú úlohu pri liečbe. Toto tvrdenie potvrdzuje aj vedecká disciplína *epigenetika*. Ak naozaj vonkajšie prostredie ovplyvňuje biológiu človeka, t. j. jeho epigenóm, potom dokážeme vytvoriť vzťah medzi spoločnosťou a zdravím človeka, a medzi telom a dušou človeka, jeho pocitmi, potrebami, zážitkami, vnímaním vonkajšieho prostredia.

Čo vytvára našu realitu?

* Výchova
* Vzdelanie
* Vonkajšie prostredie
** Médiá
** Spoločnosť
** Inštitúcie
** Náboženstvo

A teraz, vďaka epigenetike vieme zmerať, od ako vonkajšie prostredie vplýva na zdravie človeka. Vieme vytvoriť spojenie medzi spoločenskými vplyvmi a biológiou človeka. link:???[(Peter Spork - Gesundheit is kein Zufall)], link:???[(Zitat)]

Chcel som si konečne začať užívať život, potom, čo som asi šesť krát vyhorel. Asi som vymyslel prevenciu proti vyhoreniu a zachovanie radosti zo života. Ale berte to s rezervou: žiadne, že buď 100% garancia spokojnosti, alebo vrátenie peniazí ;) Ale pomohlo mi to začať odznova. Postupne prekonávať depriesie. Menej sa nenávidieť za chyby :/ A pomaly sa liečiť z chorôb, keď lekári hovorili, že ma nevedia vyliečiť.

*I just want to be healthy and live well! Do I want so much?!link:https://www.fileformat.info/info/unicode/char/203d/index.htm[‽]*

*Why did I recreated everything to feel good again? Why isn't it here right from the beginning!?*

Lebo môžem byť neviemaký odborník, keď neviem vychádzať s ľuďmi.

To ma vždy bude vyrušovať pri učení sa čohokoľvek odborného.

Chcem sa cítiť dobre s druhými ľuďmi.

Odbornosť nie je všetko. Odbornosť je jedna časť.

Ďalšia časť je ľudskosť.

Ľudskosť rozvíjam empatiou.

Empatia mi pomáha spájať sa so sebou samým a s ostatnými ľuďmi a rozumieť dobrým dôvodom, pocitom a potrebám, prečo ľudia robia to, čo robia.

Empatia lieči rany na duši rýchlejšie a do väčšej hĺbky než psychoanalýza, pretože empatia sa zameriava na prítomnosť. Pri psychoanalýze sa rozpráva o minulosti, lenže rozprávanie o minulosti a jej analyzovanie spomaľuje liečbu a môže jej dokonca brániť. Psychoanalýza poskytuje skôr intelektuálne porozumenie než emocionálne liečenie: súcit - empatiu.

Empatia je súčasťou emocionálnej inteligencie.

Lenže väčšina škôl a väčšina pedagógov používa praktiky, ktoré bránia rozvoju empatie a emocionálnej inteligencie. Veď akoby aj mohli. Pedagógovia sa trápia, lebo oni sami nevedia veľa o emocionálnej inteligencii a jej dôležitosti, a aj väčšina školských inštitúcii je  navrhnutá tak, aby kládli väčší dôraz na výkon, výsledky, súťaživosť, povinnosť a poslušnosť, než na starostlivosť, ochotu, dobrovoľnosť, súcit a zodpovednosť.

A namiesto altruistických ľudí vychovávajú ľudí sebeckých. Lebo, čo sa asi študent naučí? *Že ostatní ľudia sú potencionálnou prekážkou k jeho/jej úspechu.* A, že *ja dokážem uspieť iba vtedy, keď druhí zlyhajú.* link:???[Alfie Kohn - OFJCC], link:???[Daniel Markovits - Excellence vs Superiority]

V takomto prostredí potom trpia nielen študenti, ale aj učitelia a vedenie. Podobne vo firmách, trpia zamestnanci aj menežéri, ktorí vyznávajú túto ideológiu.

Som presvedčený, že nízka úroveň emocionálnej inteligencie a hrozba násilím umožňuje, aby sa takýto systém udržal.

A chcem sa vedieť smiať na svojich chybách. Chcem sa učiť zo svojich chýb a prestať sa nenávidieť za to, že robím chyby.

Výrazne mi v tom pomohlo štúdium a tréning nenásilnej komunikácie. Začal som v auguste 2019 _(14.8.2019)_. Pokračujem až dodnes. Vždy, keď ju použijem, uľaví sa mi. Máloktorá technika, ktorú som kedy skúšal bola tak spoľahlivá, ako je táto. Nenásilná komunikácia zvyšuje moju emocionálnu inteligenciu, vnímavosť, duševný pokoj a rovnováhu. Dáva mi nádej, že veci môžu byť aj inak. Lepšie. Udržateľné. Prospešné pre všetkých. Nielen iba pre elitu.

== Notes

Emotional intelligence, empathy and the idea of communism look to me very similar +
*Emotional inteligence:* The ability to recognize and manage one's own emotions and emotions of other people. link:https://www.skillsyouneed.com/general/emotional-intelligence.html[EI - Source] +
*Empathy:* Awareness of the feelings and needs in myself and other people and being able to see things from the point of view of others. link:https://www.skillsyouneed.com/general/emotional-intelligence.html[Empathy - Source] +
*Communism:* From each according to their abilities to each according to their needs. link:https://en.wikipedia.org/wiki/From_each_according_to_his_ability,_to_each_according_to_his_needs#:~:text=%22From%20each%20according%20to%20his,of%20goods%2C%20capital%20and%20services.[Idea of communism - Source]

---

Stres nie je pocit. Stres je úsudok. +
... +
...


stres = napätie + bezmocnosť +
Stress = Anspannung + Machtlosigkeit +
stress = tension + powerlessness

---

*Paradox*: I'm ashamed when I speak to a girl, that I'm not good enough for her, and she's ashamed as well because she thinks she doesn't deserve love and is ashamed of her beauty.

---

* *The prayer of peace / Das Gebet der Ruhe / Modlitba pokoja* _(27.5.2019)_ +
  Pokoj sa rozlieva každou bunkou môjho tela, moju myseľ napĺňa sústredenie a moje telo dýcha uvoľnením. +
  Die Ruhe fließt durch jede Zelle meines Körpers, mein Geist erfüllt Konzentration und mein Körper atmet die Entspannung. +
  The calmness flows through every cell of my body, my mind fills concentration and my body breaths relaxation. +

---

stav horiacej zúrivosti ???

---

Čo je to _svedomie_ / Gewissen / conscience?

---

Čo si len ja počnem, +
čo si len ja počať mám, +
jablkový rezeň si ja na obed dám. +
Juchuuu!

---

_Sonntag 9.8.2020_ +
*Sladký život*

Budeme sa hladkať, škrabkať, +
objímať a bozkávať. +
Budeme si hryzkať do uška +
a šepkať sladké nezmysly. +
Dotýkať sa telami aj slovami.

Škrabkať sa vo vlasoch, +
štekliť sa po nohách, +
túliť sa pod perinou +
v bezpečí, dôvere a radosti. +

Ochutnám tvoje sladké pery, +
stisnem tvoj mäkký zadoček, +
nadýchnem sa tvojich vlasov, +
nežne ťa pohryzkám na krk +
poškrabkám ťa svojimi fúzikmi, +
ktoré si už šiesty týždeň pestujem.

Privinieš si moju hlavu na svoju hruď, +
a budem počúvať tlkot tvojho srdca +
vo vzrušujúcom očakávaní.

Stisneme si naše hrude +
v horúcom objatí, +
a budme tancovať +
ako zemiačiky +
vo vriacej vode +
pôžitku a vášne.

Unavíme sa +
budeme spotení a smrdieť. +
Potom zaspíme. +
Budeme slintať do vankúša, +
prdieť do periny, +
hádzať rukami a nohami, +
chrápať a škrípať zubami, +
keď budeme v hlbokom spánku. +

Bude sa nám snívať +
o jednorožcoch, +
v ružovom vesmíre, ktorí +
skáču po obláčikoch, +
grcajú dúhu, +
a prdia motýle. +

Jesť +
eko, bio, racio, +
raw, vegan, organic +
bezlaktózové a bezlepkové +
potraviny z dovozu. +
Budeme grgať po každom jedle. +
Ach, tá úľava.

Zostarneme mladí, +
a pôjdeme na predčasný dôchodok. +

Ej! A budeme mať popiči život :D Bardzo zajebisty!

---

*Chcieť môžeš.* Marshall Bertram Rosenberg - parody +
*Snívaj ďalej.* Doug Newburg - parody

---

Unterstützen Hausaufgaben für Punkte die Ausbrennung in den Studenten? +
Ich gehe aus meiner eigenen Erfahrung aus. In der Grundschule, am Gymnasium, an der Uni, ich lernte und arbeitete hart jeden Tag. Von Tag bis Nacht. Ich fühlte mich angespannt und erschöpft. Um die Anspannung zu entspannen, habe ich mich körperlich befriedigt und Computerspiele gespielt. Manchmal bis frühen Morgen über die ganze Nacht. Ich arbeitete, und arbeitete, und spielte, ... Und dann wurde ich krank. Ich unterband mich von meinen Gefühlen und Bedürfnissen. Ich konzentrierte mich auf die Leistung, anstatt auf den Genuss und Freude am Lernen. Das TODO-Liste war mir wichtiger als meine eigene Gesundheit.s

---

Ich will es beschleunigen. Ich möchte gewaltfreie Erziehung, Kommunikation, Ausbildung und Management erleben. Ich will gewaltfrei leben.

---

https://www.rtvs.sk/televizia/archiv/13986/240457#973

---

Why the life is not fair? +
Because the world is driven by capitalism which supports meritocracy.

---

No one deserves anything. But everybody needs something. Everybody needs the same things. What differs immensely is the strategies in which we fulfil our needs.
