= Codename _Phoenix_

Reborn from ashes.

== Human needs / Menschliche Bedürfnisse / Ľudské potreby

by / nach / podľa Manfred Max-Neef, Marshall B. Rosenberg and me

---

The needs is *the only reason*, why I'm feeling the way I'm feeling. Not the actions of other people, or the state of the environment. These are only the stimulus for my feelings.

---

*What is a need? / Was ist ein Bedürfnis?*

* Life seeking expression within oneself.
* Manifestation of the divine energy in each living phenomenon.
* A *need* is a manifestation of life, a manifestation of divine energy within us. All human beings have the same needs. A *value* is a need with a particular level of importance. The importance of a need changes with time, circumstances and preferences.
* The need is "Why you want something?" ... Then you will discover a pool of why's that all humans share. link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4085[Miki Kashtan - Liberation 1: 1:08:05]
* A need is something that all infants have. When an infant doesn't need it, it's not a need. link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4085[Miki Kashtan - Liberation 1: 1:08:05]

Properties of needs:
* Needs are universal and nonconflicting link:https://veganvanguardpodcast.com/47-social-emotional-learning-sel-for-socialism-and-animal-liberation-with-pierce-delahunt/[47. Social Emotional Learning (SEL) for Socialism and Animal Liberation with Pierce Delahunt: 16:49-17:30]
* They contain no reference to any particular activity or person

---

* Alle Bedürfnisse sind wichtig. Ihre Wichtigkeit ändert sich mit der Zeit,  Umständen und Präferenzen.

---

* *need [bold face] / das Bedürfniss [dick geschrieben] / potreba [tučne zvýraznené]*
* _not a need - feedback / kein Bedürfniss - eine Rückmeldung / nie je potreba - spätná väzba_ - Only as a feedback that the needs were or were not fulfilled. / Nur als Rückmeldung, dass die Bedürfnisse erfült oder nicht erfüllt wurden.
* [line-through]#not a need - a strategy / kein Bedürfniss - eine Strategie / nie je potreba - stratégia#

---

* *subsistence / das Lebensunterhalt / živobytie*
* long life / langes Leben / dlhý život
* air / die Luft / vzduch
* fresh air / frische Luft / čerstvý vzduch
* clean air / saubere Luft / čistý vzduch
* water / das Wasser / voda
* drinking water / Trinkwasser / pitná voda
* nature / Nature / príroda
* physical health / physische Gesundheit / fyzické zdravie
* mental health / psychische Gesundheit / mentálne zdravie
* clothes / die Kleidung / oblečenie
* food / das Essen / jedlo
* movement / Bewegung / pohyb
* sleep / der Schlaf / spánok
* shelter / Obdach / prístrešie
* cleanliness / Sauberkeit / čistota
* bodily flexibility / körperliche Gelenkigkeit / telesná pružnosť
* warmth / Wärme / teplo
* people / Menschen / ľudia
* energy / Energie / energia
* enrichment of life / Bereicherung des Lebens / obohatenie života
* to make life wonderful / das Leben wunderbar machen
* light / das Licht / svetlo
* sunlight / Sonnenlicht / slnečné svetlo
* hygiene / Hygiene / hygiena
* environment / Umwelt, Umgebung / prostredie
* _pain / Schmerz / bolesť_
* _illness / Krankheit / choroba_

---

* *protection / die Schutz, Geborgenheit / ochrana*
* stability / Stabilität / stabilita
* safety / Sicherheit, Geborgenheit / bezpečnosť, bezpečie, istota
* security / Sicherheit / bezpečnosť, zabezpečenie
* order / Ordnung / poriadok
* equality / Gleichheit / rovnosť
* predictability / Vorsehbarkeit / predvídateľnosť
* power (with) / Macht (mit) / moc (s)
* (direct) democracy / (direkte) Demokratie / (priama) demokracia
* strength / Kraft / sila
* protective use of force / beschützende Nutzung der Kraft / použitie sily na obranu
* protecting the nature / Umweltschutz / ochrana prírody
* ecology / Ökologie / ekológia
* sustainability / Nachhaltigkeit / udržateľnosť
* preservation / Erhaltung / zachovanie, udržanie
* durability / Haltbarkeit / trvácnosť
* robustness / Robustheit / odolnosť, robustnosť
* recycling / Wiederverwendung / recyklácia, znovupoužiteľnosť
* cautiousness, carefulness / Vorsichtigkeit / opatrnosť
* economy, thrift / Sparsamkeit / úspornosť, šetrnosť
* justice, fairness, equity / Gerechtigkeit / spravodlivosť
* compensation / Ausgleich / kompenzácia, odškodnenie - nie ako odplata alebo trest, ale ako pomoc pri napĺňaní nenaplnených potrieb pre niekoho iného
* _fragileness / Zerbrechlichkeit (Bedürfnis nach Schutz (physisch) oder Empathie (psychisch)) / krehkosť_
* [line-through]#war / Krieg / vojna#
* [line-through]#violence / die Gewalt / násilie#
* [line-through]#government / die Regierung / vláda#
* [line-through]#colonization / Kolonisation / kolonizácia#

---

* *affection / Zuwendung / náklonnosť*
* love / Liebe / láska
* tenderness / Zärtlichkeit / neha
* sensuality / Sinnlichkeit / zmyselnosť
* passion / Leidenschaft / vášeň
* touch / Berührung / dotyk
* intimacy / Intimität / intimita
* closeness / Nähe / blízkosť
* trust / Vertrauen / dôvera
* care / Pflege / starostlivosť
* connection / Verbindung / spojenie, kontakt
* empathy _(Giraffe Dance)_ / Empathie (Precondition: courage / Mut) / empatia, súcit
* honesty _(Giraffe Dance)_ / Ehrlichkeit (Precondition: vulnerability / Verletzlichkeit) / úprimnosť
* reassurance / Beschwichtigung / uistenie, utešenie
* help, aid / Hilfe / pomoc
* support, aid / Unterstützung / podpora
* generosity / Großzügigkeit / veľkorysosť
* communication / Kommunikation / komunikácia
* friendship / Freundschaft / priateľstvo
* mourning / Trauern / smútenie
* importance (of my needs) / Wichtigkeit (meiner Bedürfnisse) / dôležitosť (potrieb)
* consciousness that my needs matter, that my needs are important and taken into consideration / Bewusstsein, dass meine Bedürfnisse wichtig sind, und in Frage genommen sind / vedomie, že na mojich potrebách záleží, že moje potreby sú dôležité a brané do úvahy
* consideration / Rücksicht / ohľad (Precondition: importance / that my needs matter)
* respekt / Respekt / rešpekt (Precondition: importance / that my needs matter)
* honor / Ehre / úcta (Precondition: importance / that my needs matter)
* dignity / Würde / dôstojnosť (Precondition: importance / that my needs matter)
* tolerance / Toleranz / tolerancia
* relationships / Beziehungen / vzťahy
* nurturing, upbringing / Erziehung / výchova
* interdependency / ??? / ???
* _recognition, acknowledgement / Anerkennung / uznanie_
* _appretiation / Wertschätzung / ocenenie_
* _gratitude / Dankbarkeit / vďačnosť_
* [line-through]#apology Verzeihung / ospravedlnenie#
** (*masked need for empathy*: link:...[Marshall Rosenberg - Making Life Wonderful ???-which part???]), When we empathize, there is nothing to forgive. link:???[(San Fran Workshop)], Forgiveness and empathy are the same thing [in the language of life.] link:???[(SELF EMPATHY)]
* [line-through]#approval / Genehmigung / dovolenie, odobrenie#
* [line-through]#affirmation / Bestätigung / potvrdenie#
* [line-through]#sex / Geschlechtsverkehr#
* [line-through]#sexuality / Sexualität / sexualita#
* [line-through]#duty, obligation / die Pflicht / nutnosť, povinnosť#
* [line-through]#commitment / Verpflichtung / obetavosť, oddanosť#
* [line-through]#codependency / ??? / ???#

---

* *understanding / Verständnis / porozumenie*
* critical thinking / kritisches Denken / kritické myslenie
* logical thinking / logisches Denken / logické myslenie
* curiosity / Neugier / zvedavosť
* interest / Interesse / záujem
* intuition / Intuition / intuícia
* concentration / Konzentration / sústredenie
* learning / Lernen / učenie sa
* competence / Fähigkeit / schopnosť
* utility / Nutzen / úžitok
* sense, purpose / Sinn, Zweck / zmysel
* goal / Ziel / cieľ
* effectivity [Does it work, or not? - boolean] / Effektivität / efektivita
* efficiency [How well does it work? As much as possible in as little time as possible, e.g. in case of algorithms or other things not people!] (in comparison to other things, not people) - float, percent) / Effizienz / efektivita
* growth / Wachstum / rast
* development / Entwicklung / rozvoj, vývoj (Precondition: individual initiative, dedication link:https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=1584[(source)])
* consciousness / Bewusstsein / vedomie
* repetition / Wiederholung / opakovanie
* solution / Lösung / riešenie
* answer / Antwort / odpoveď
* feedback / Rückmeldung / spätná väzba
* understandability, clarity / Verständlichkeit, Klarheit / zrozumiťeľnosť
* education / Ausbildung / vzdelanie
* overview / Überblick / prehľad
* universality / Allgemeinheit, Universalität / univerzálnosť
* generality / Allgemeinheit / všeobecnosť
* specificity / Genauigkeit, Spezifizität / konkrétnosť
* control / Kontrolle / kontrola - možnosť ovládať prostredie okolo seba
* explanation / Erklärung / vysvetlenie
* knowledge / Kenntnise / vedomosti
* expertise / Fachkenntnisse / odborné znalosti, odbornosť, expertíza
* randomness / Zufälligkeit / náhodnosť
* compatibility / Kompatibilität / kompatibilita
* completeness / Vollständigkeit / úplnosť
* holism / der Holismus / celostnosť
* depth / die Tiefe / hĺbka
* uniformity (in Data) / Uniformität, Einheitlichkeit, Gleichmäßigkeit / uniformita
* readability / Lesbarkeit / čitateľnosť
* brevity / Kürze / stručnosť
* thoroughness / Gründlichkeit / dôkladnosť, dôslednosť
* correctness / Richtigkeit / správnosť
* validity / Gültigkeit / platnosť
* seriousness / Ernsthaftigkeit / vážnosť
* transparency / Transparenz / transparentnosť, priehľadnosť
* links, coherences, context / Zusammenhänge, Kontext / súvislosti
* _complication / Komplikation_
* _problem / Problem_
* _mistake, error / Fehler / chyba_
* [line-through]#chaos / Chaos, Durcheinander#
* [line-through]#school / Schule / škola#
* [line-through]#work / Arbeit / práca#
* [line-through]#consumption / Konsum / spotreba#

---

* *participation / Teilnahme / účasť*
* acceptance (by others) / Annahme / prijatie
* community / Gemeinschaft / komunita, spoločenstvo, spoločnosť
* receptiveness (from others) / Annahmefähigkeit / prijímanie
* company / Gesellschaft / spoločnosť (ľudí)
* oneness, unity / Einheit / jednotnosť
* belonging / Zugehörigkeit / spolupatričnosť
* cooperation / Zusammenarbeit / spolupráca
* presence / Anwesendheit / prítomnosť
* sharing / Teilen / zdieľanie
* inclusion / Einbeziehung / začlenenie
* integration / Integration / integrácia
* common good / Gemeinwohl / verejné blaho
* [line-through]#competition / Wettbewerb / súťaž#
* [line-through]#competition / Konkurenz / konkurencia#
* [line-through]#race / Rennen / závodenie, preteky#

---

* *leisure / Freizeit / voľný čas*
* serenity / Gelassenheit / pokoj
* peace / Frieden / mier
* rest / Erholung / oddych
* harmony / Harmonie / harmónia
* calmness / Ruhe / pokoj
* awareness / Aufmerksamkeit / pozornosť
* celebration / Feier / oslava
* mindfulness / Achtsamkeit / vnímavosť
* fun / Spaß / zábava
* humor / Humor
* amusement / Vergnügen / potešenie, zábava
* enjoyment / Genuss / pôžitok
* softness / Weichheit / mäkkosť
* culture / Kultur / kultúra
* silence / Stille / ticho
* relaxation / Entspannung / uvoľnenie
* well-being / Wohlergehen, Wohlbefinden / blaho, spokojnosť
* relax / Erholung / oddych
* comfort / Bequemheit / pohodlie
* gratification / Befriedigung / uspokojenie
* contentment, satisfaction / Zufriedenheit / spokojnosť
* balance / Gleichgewicht / rovnováha
* gentleness / Sanftheit / jemnosť
* agility / Beweglichkeit / pohyblivosť
* _discomfort / Unbehagen / nepohodlie_
* [line-through]#instant gratification / sofortige Befriedigung / okamžité uspokojenie#

---

* *creation, creativity / Schöpfung, Kreativität / tvorivosť*
* imagination / Fantasie, Vorstellungskraft / fantázia, predstavivosť
* inventiveness / Ideenreichtum / nápaditosť
* play / Spiel / hra
* beauty / Schönheit / krása
* inspiration / Inspiration / inšpirácia
* art / Kunst / umenie
* challenge / Herausforderung / výzva
* discovery / Entdeckung / objav
* stimulation / Anregung / podnietenie
* music / Musik / hudba
* rhythm / Rhythmus / rytmus
* adaptability / Anpassbarkeit / prispôsobiteľnosť
* smell, scent / der Duft / vôňa
* flow / Flow, Strömung / prúdenie
* change / Änderung / zmena
* intrinsic motivation / eigene Motivation / vlastná motivácia
* fulfilment / Erfüllung / naplnenie
* quality / Qualität / kvalita
* innovation / Innovation, Erneuerung / inovácia
* performance / Leistungsfähigkeit / výkonnosť
* flexibility / Flexibilität / pružnosť, prispôsobiteľnosť
* freshness / Frischheit / čerstvosť
* handling (e.g. of a car) / Handling, Steuerungsfähigkeit / ovládateľnosť
* tightness / Dichtheit / tesnosť
* thickness / Dichte / hustota
* humidity / Feuchtigkeit / vlhkosť
* dryness / Trockenheit / sucho
* elasticity / Elasizität / elasticita, pružnosť
* plasticity / Plastizität / plasticita
* viscosity / Viskosität / viskozita
* style / Stil / štýl
* alternative / Alternative / alternatíva
* cohesion / Kohäsion / kohézia, súdržnosť
* coupling / Kopplung / väzbovosť
* match / Übereinstimmung / zhoda
* roughness / Rauheit / drsnosť
* smoothness / Glätte / hladkosť
* diversity / Vielfalt(igkeit) / rôznorodosť, diverzita
* transparency / Durchsichtigkeit / priehľadnosť
* _extrinsic motivation / extrinsische, äußere Motivation / vonkajšia motivácia_
* _smell / der Gestank / zápach_
* [line-through]#productivity / Produktivität / produktivita#

---

* *identity / Identität / identita*
* consistency / Konsistenz / pravidelnosť, vytrvalosť
* integrity / Integrität / integrita, súlad
* authenticity / Authentizität / autenticita, svojskosť
* spontaneity / Spontaneität / spontánnosť
* reliability / Verlässlichkeit / spoľahlivosť
* accuracy / Genauigkeit / presnosť
* precision / Präzision / precíznosť
* privacy / Privatsphäre / súkromie
* simplicity /Einfachheit / jednoduchosť
* punctuality / Pünklichkeit / dochvíľnosť
* trustworthiness / Glaubwürdigkeit / dôveryhodnosť
* spirituality / Spiritualität / spiritualita
* lightness / Leichtigkeit / ľahkosť
* fluency, smoothness / Flüssigkeit / plynulosť
* gracefulness / Anmut / ladnosť
* endurance / Ausdauer / vytrvalosť
* naturalness / Natürlichkeit / prírodnosť, prirodzenosť
* resonance / Resonanz / rezonancia, súzvuk
* determination / Entschlossenheit / rozhodnosť
* intensity / Intensität / intenzita
* dedication / Einsatz / nasadenie
* self-fullness / Selbsvölligkeit / sebanaplnenie
* maintainability / Wartbarkeit, Wartungsfreundlichkeit / udržovateľnosť
* patience / Geduldigkeit / trpezlivosť
* speed, velocity / Geschwindigkeit, Schnelligkeit / rýchlosť
* responsiveness / Schlagfertigkeit / promptnosť, pohotovosť, bystrosť
* tradition / Tradition / tradícia
* habit / Gewohnheit / zvyk
* courage / Mut / odvaha (Precondition: mutual aid -> mutual confidence)
* responsibility / Verantwortung / zodpovednosť
* altruism / Altruismus / altruizmus
* solidarity / Solidarität / solidarita
* humanity / die Menschlichkeit / ľudskosť
* consentual rules / gemeinsam bestimmte Regeln / spoločne stanovené pravidlá
* [line-through]#rules / Regeln / pravidlá#
* [line-through]#power (over) / Macht (über) / moc (nad)# link:...[Ökonomische Pseudowerte: https://www.youtube.com/watch?v=7mRe1ntgbj8&feature=youtu.be&t=1260]
* [line-through]#obedience / Gehorsamkeit / poslušnosť#
* [line-through]#money / Geld / peniaze#
* [line-through]#success / Erfolg / úspech#
* [line-through]#[social] status / [soziales] Status / [spoločenský] status,  stav, postavenie#
* [line-through]#popularity (to be liked by other people) / Popularität (unter Leuten beliebt zu sein) / popularita (byť oblúbený medzi ľuďmi)#
* [line-through]#individualism / Individualismus / individualizmus#
* [line-through]#ownership (to have and to have more) / Eigentum / vlastníctvo#
* [line-through]#religion / Religion / náboženstvo#

---

* *freedom / Freiheit / sloboda*
* risk / Risiko / riziko
* hope / Hoffnung / nádej
* space / Raum / priestor
* choice / Auswahl / voľba
* availibility / Verfügbarkeit /  dostupnosť
* time / Zeit / čas
* access / Zugriff / prístup
* mobility / Mobilität / prenosnosť
* transportation / Transport / preprava, doprava, transport
* autonomy / Selbstständigkeit, Autonomie / samostatnosť
* faith / Glaube / viera
* voluntariness / Freiwilligkeit / dobrovoľnosť
* willingness, good will / Bereitschaft, Entgegenkommen / ochota

== Feelings at unfulfilled needs (Sweet pain - Girrafe mourning) / Gefühle bei unerfüllten Bedürfnissen

What needs of mine are not being met?

What needs of the other are not being met?

* terrified / erschrocken / vystrašený (vystrašiť, báť sa)
* frightened / verängstigt / vystrašený (vystrašiť)
* alarmed / erschrocken / vystrašený (vystrašiť)
* scared / erschrocken / vyľakaný (vyľakať)
* anxious / besorgt / ustarostený (robiť si starosti, mať starosti, obávať sa)
* fearful / ängstlich / ustarostený (robiť si starosti, mať starosti, obávať sa)
* concerned / bekümmert / ustarostený (robiť si starosti, mať starosti, obávať sa)
* worried / besorgt / ustarostený (robiť si starosti, mať starosti, obávať sa)
* shocked / schockiert / šokovaný (šokovať)
* surprised / überrascht / prekvapený (prekvapiť)
* disturbed / beunruhigt, gestört / znepokojený, rozrušený, vyrušený (znepokojiť, rozrušiť, rušiť, vyrušovať, rozptyľovať, vadiť)
* irritated / irritiert / iritovaný, nervózny (iritovať, znervózniť)
* nervous / nervös / nervózny (znervózniť)
* discontented / unzufrieden / nespokojný
* tense / angespannt / napätý (napínať)
* frustrated / frustriert / frustrovaný (frustrovať)
* disgusted / geeckelt, angeeckelt / znechutený (znechutiť)
* sick (e.g. upset stomach) / übel (z.B. Magen-Verdauungsbeschwerden) / zle, nevoľno (napr. od žalúdka)
* hesitant / zögernd / váhavý (váhať)
* distrusting / misstrauend / nedôverčivý (nedôverovať)
* doubting / zweifelnd / pochybovačný (pochybovať)
* sceptical / skeptisch / skeptický, pochybovaťný (pochybovať)
* imatient / ungeduldig / netrpezlivý (I can't wait / ich kann nicht warten / nevedieť sa dočkať)
* confused / durcheinander / zmätený (zmiasť)
* bewildered / verwirrt / zmätený (zmiasť)
* discouraged / entmutigt / odradený (odradiť)
* lonely (this one manifests as a pain and weakness in heart) / einsam / osamelý
* apathetic / apathisch / apatický, ľahostajný (to loose interest in something, burn out / die Interesse an etwas [Akk.] verlieren, ausbrennen / stratiť záujem, vyhorieť)
* bored / gelangweilt / znudený (nudiť sa, unudiť)
* indifferent / gleichgültig / ľahostajný (lose interest / Interesse verlieren / stratiť záujem)
* tired / müde / unavený (unaviť)
* exhausted / erschöpft / vyčerpaný (vyčerpať)
* regretful / bedauernd / byť ľúto
* helpless / hilflos, ratlos / bezradný (nevedieť si rady, nevedieť si poradiť)
* powerless (often misunderstood as _stress_) / +
machtlos (häufig verwechselt mit _Stress_) / +
bezmocný (často zamieňaný so _stresom_)
* disappointed / enttäuscht / sklamaný (sklamať)
* sad / traurig / smutný (smútiť)
* hurt / verletzt / ranený, zranený, dotknutý
* hopeless / hoffnungslos / beznádejný (stratiť nádej)
* desperate / verzweifelt / zúfalý (zúfať)
* vulnerable / verletzlich / zraniteľný
* leiden / suffer / trpieť
* suffer / sich quälen / trápiť sa
* pain (to ache) / der Schmerz (wehtun) / bolesť (bolieť)

*Bitter pain - Alarm feelings / Bittere Schmerzen - Weckgefühle*

Disconnected from needs / Unterbunden von Bedürfnissen

* *angry / ärgerlich / nahnevaný (hnevať sa)*
* indignant / empört / rozhorčený (rozhorčiť sa)
* furious, mad, enraged / wütend, zornig, aufgebracht / zúrivý (zúriť)
* hating / hassend / nenávidiaci, nenávistný (nenávidieť)
* *depressed / deprimiert (in Depression fallen) / deprimovaný (upadnúť do depresie)*
* *guilty / schuldig / vinný*
* *ashamed / beschämt / zahanbený (hanbiť sa)*
* envious / neidisch / závistlivý (závidieť)
* jealous / eifersüchtig / žiarlivý (žiarliť)
* embarassed / verlegen / rozpačitý, v rozpakoch

*Not-feelings - thoughts, analyses, diagnoses, interpretations, criticisms / Nicht Gefühle / ne-pocity*

link:...[Source]

* resentful
* overwhelmed
* lost
* abandoned
* abused
* attacked
* belitted
* betrayed
* blamed
* bullied
* boxed in
* caged
* cheated
* coerced
* cornered
* critcized
* disconnected
* discounted
* diminished
* disliked
* distrusted
* dumped on
* harassed
* hassled
* horny / geil / nadržaný
* ignored
* insulted
* interrupted
* intimidated
* invisible
* isolated
* judged
* left out
* let down
* manipulated
* mistrusted
* misunderstood
* neglected
* overpowered
* patronized
* pressured
* provoked
* put down
* rejected -> disappointed
* ripped off
* screwed
* smothered
* suffocated
* taken for granted
* threatened
* trampled
* walked on
* tricked
* unaccepted
* unappreciated
* unheard
* unloved
* unseen
* unsupported
* unwanted
* used
* victimized
* violated
* wronged
* resentful

*Not feelings - Moralistic judgements - Social constructs*

* smart
* dumb
* generous
* lazy
* considerate
* inconsiderate
* responsible
* irresponsible
* guilty
* innocent
* good
* bad
* right
* wrong
* normal
* abnormal
* weird
* awkward
* sick
* awesome
* nice
* sinful
* wretched
* creepy
* perverse
* unfair
* pretty
* handsome
* ugly
* handsome
* sexy
* reasonable
* unreasonable
* lucky
* unlucky
* hyperactive
* crazy
* professional
* unprofessional
* amateur
* _all vulgarisms_
* vulgar
* ridiculous
* decent
* appropriate
* selfish
* generous
* disrespectful
* spoiled
* naïve
* fast
* slow
* competent
* incompetent link:https://en.wikipedia.org/wiki/Peter_principle[Peter Principle]
* adequate
* inadequate
* inferior
* important
* unimportant
* significant
* insignificant
* charismatic
* würdig
* unwürdig

== Feelings at fulfilled needs - Dream Feelings - Flow

Gefühle bei erfüllten Bedürfnissen / Pocity pri naplnených potrebách.

How do I want to feel? [RPM]

---

[line-through]#(November 2019) Ich kann meine Gefühle beschreiben, die ich bei meinen Traumaktivitäten erleben möchte, weil ich nicht den Wortschatz an Gefühle habe. Ich brauche mir die Äußerung meiner Gefühle erreichern. Ich brauche die Fähigkeit, die Gefühle in mir bewusst werden und sie benennen. Dann kann ich mir an maine Traumgefühle erinnern und sie gleich wiederherstellen.#

---

Flow - a state of highest human performance and happiness +
*_optimal human performance_* means the same as *_happiness_* link:...[(Cedric Dumont - TEDx; Flow - Mihály Csíkszentmihályi)]

Celebration of life / Feier des Lebens / oslava života

link:https://sci-hub.st/10.1080/10413200290103545[The Dream - Dream Feelings: Doug Newburg]

link:...[Nonviolent Communication (NVC) - Feelings at fulfilled needs]

[quote, Marshall B. Rosenberg - Chief from one of the tribes in northern Nigeria, Making Life Wonderful ?/4; San Francisco Workshop]
____

If we know how to speak this language, we don't have to kill each other.

____

Wie will ich mich fühlen wenn ich: +
spreche, mit jemandem spreche, schreibe, zuhöre, mich dusche, mich mit kaltem Wasser dusche, programmiere, UML-Diagramme zeichne, lerne, Algorithmen ausdenke, nachdenke, Akkordeon spiele, nach etwas suche, esse, Wäsche wasche, Wäsche aufhänge, einkaufe, schlafe, einschlafe, Pilates übe, Yoga übe, laufe, TRX übe, Augen übe, Atem übe, übe, mich bewege, ausruhe, meditiere, plane, Fremdsprachen lerne, Bücher lese, Bücher höre, zu gesprochenem Wort höre, Musik höre, mir Videos anschaue, Artikel lese, Artikel schreibe, lehre, forsche, in C++ programmiere, in Fremdsprachen Geschichten schreibe, zu Projekten beitrage, "Nein" höre, ein Auto fahre, mich vorbereite, Musik komponiere, übersetze, Musik in Noten überschreibe, Aussagen in gewaltfreie Kommunikation übersetze, Noten eines Liedes lese, experimentiere, Fehler mache, nach Zusammenhängigkeiten suche, von Fehlern lerne, präsentiere, einen Quellcode lese, einen fremden Quellcode lese, einen fremden Quellcode lese, einen fremden Quellcode ändere, einen fremden Quellcode bearbeite, einen komplizierten Quellcode ändere, einen komplizierten Quellcode bearbeite, einen kompliziertes Software entwerfe, einen, ein kompliziertes Software entwickle, ein kompliziertes Software analysiere, ein fremdes Software analysiere, schnell an die Tastatur schreibe, schnell programmiere, Probleme löse, Fragen beantworte, mich in mich oder anderen hineinfühle, Empathie zeige, Konflikte löse, Fragen beantworte, mich mit meinen Gefühlen und Bedürfnissen verbinde, Fragen stelle, aufräume, mir das Essen vorbereite, das Geschirr spüle, die Gefühle und Bedürfnisse hinter jeder Aussage rate, programmieren lerne, Programmiersprache lerne...

^^ Das mache ich...

\... und so will ich mich dabei fühlen:

* free / frei / voľný, slobodný
* relaxed / entspannt / uvoľnený
* excited / erregt / vzrušený
* courageous / mutig / odvážny
* energetic, full of energy / energisch / energický
* optimitstic / optimistisch / optimistický
* concentrated, focused / konzentriert, fokusiert / sústredený
* calm / ruhig / pokojný
* curious / neugierig / zvedavý
* interested / interessiert / zaujímajúci sa
* wondering / wundernd / čudujúci sa
* glad / froh / rád
* cheerful / fröhlich / radostný
* friendly / freundlich / priateľský
* joyful / freudvoll / veselý (tešiť sa, zabaviť sa, pobaviť, zasmiať sa z ...)
* happy / glücklich / šťastný
* confident / selbstsicher / sebaistý (Precondition: mutual aid link:https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=1584[(source)])
* safe / sicher, geborgen / v bezpečí
* light / leicht / ľahký
* fulfilled / erfüllt / naplnený
* content / zufrieden / spokojný
* satisfied / befriedigt / uspokojený
* immersed / eingetaucht / ponorený
* strong / stark / silný
* powerful / kräftig, kraftvoll / silný
* mighty / machtvoll / mocný
* attentive / aufmerksam / pozorný
* determined / entschlossen / rozhodný
* blissful / glückselich / blažený
* lively / lebendig / nažive
* vigorous / lebhaft / húževnatý
* hungry (before exercising) / hungrig / hladný
* unstoppable / unaufhaltbar / nezastaviteľný
* dedicated / eingesetzt / v nasadení
* patient / geduldig / trpezlivý
* full of expectations / erwartungsvoll / plný očakávaní
* sleepy / schläfrig / ospalý
* on fire (at hardening) / in Brand gesetzt (bei Härten) / ako v ohni (pri otužovaní)
* rested / erholt / oddýchnutý
* deeply rooted / tief verwurzelt / hlboko zakorenený
* impressed / beeindruckt / ohúrený
* touched / berührt / dojatý
* relieved / erleichtert / uľavený (uľaviť)
* encouraged / ermutigt / odhodlaný
* hopeful / hoffnungsvoll / plný nádeje
* goot (vague feeling - needs to be more closely specified in order to make a closer connection) / gut / dobre
* passionate / leidenschaftlich / vášnivý

^^ Dream feelings [Doug Newburg - RPM]. Diese Gefühle habe ich bei erfühlten Bedürfnissen. [NVC Buch]

== Comparisons

- Punishment and Rewards vs Discipline, Care, *Unconditional* Love and Reason - link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4], Alfie Kohn, Samuel P. Oliner + Pearl M. Oliner [Altruistic Personality + Samuel Oliner Testimony], Miki Kashtan [Exiting the Either/Or Trap - 17th minute]
- Shame, Punishment and Revenge vs Safety, Respect, Responsibility, Care and Unconditional Love - Miki Kashtan-Bullying, link:https://www.youtube.com/watch?v=2KXwnbsQUrI&feature=youtu.be&t=87[Restorative Justice Continuum - Howard Zehr Ph.D EM 1:27-2:12], link:https://www.youtube.com/watch?v=0pleCht2jN4&feature=youtu.be&t=439[NVC Guilt and Shame - Kirsten Kristensen: ???-???, Alfie Kohn, James Gilligan - Shame]
- Production and Comsumption vs Care and Freedom - link:https://www.youtube.com/watch?v=kikzjTfos0s&feature=youtu.be&t=2958[On Bullsh*t Jobs | David Graeber | RSA Replay: 49:18-49:44]
- Gratitude and Appreciation vs Reward, Praise and Compliments- M. B. Rosenberg, Alfie Kohn, Peter Gray
- Criticism, Punishment, Praise and Compliments vs Observation, Feeling, Need, Request and Unconditional Love - M. B. Rosenberg, Alfie Kohn
- Criticism, Punishment, Praise and Compliments vs Unconditional Love - Alfie Kohn [OFJCC - 26:10-27:28-30:04]
- Education as an obligation, contest, competition or transaction vs Education as a gift link:soundcloud???[Alfie Kohn - Interviu]
- Needs as an obligation, contest, competition or transaction vs Needs as a gift [M.B. Rosenberg - Experiencing Needs As a Gift]
- Observation vs Evaluation - Jiddu Krishnamurti, M.B. Rosenberg, link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1711[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 28:31-29:40]
- Honesty vs Criticism and Blame - M. B. Rosenberg [Making life wonderful - part 1/4 - somewhere at the beginning]
- Feedback and life-serving Judgement and Evaluation for decision-making vs moralistic Evaluation and Judgement, Praise, Compliments, Reward, Blame, Criticism and Punishment - Alfie Kohn
- Natuar vs Habitual - M. B. Rosenberg - San Francisco Workshop
- Request vs Demand - M. B. Rosenberg - Portland Workshop time: ??? + resolving conflicts with children workshop time: ???
- Power over (people and nature) vs Power with (people and nature) - Mary Parker Follett, link:https://sci-hub.st/10.5840/pom20033221[Power, Freedom and Authority in Management: Mary Parker Follett’s ‘PowerWith’ - Domènec Melé, Josep M. Rosanas] Miki Kashtan [Exiting the Either/Or Trap - 30th minute], M. B. Rosenberg, Alfie Kohn, Mark Shepard-"Power over nature vs Power with nature"
- Authority based on 'power over' model vs Authority based on 'power with' model - M. B Rosenberg [interview with paula gloria], Mary Parker Follett
- Obedience vs Responsibility - link:https://www.youtube.com/watch?v=HLgGt7yLhJg&feature=youtu.be&t=3373[Atelier communication non violente - Marshall Rosenberg - Danemark - sous-titres français: 56:13-57:15]
- Respect vs Obedience - link:https://www.youtube.com/watch?v=HLgGt7yLhJg&feature=youtu.be&t=3373[Atelier communication non violente - Marshall Rosenberg - Danemark - sous-titres français: 56:13-57:15], link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4]
- Respect vs Fear - link:https://www.youtube.com/watch?v=Qk8fOOMWOGc[Shaping Discipline with a Restorative Approach - Part 4]
- Respect vs Approval - link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=1008[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 16:48-22:20)]
- Empathy, Power with People and Respect vs Obedience - link:https://www.youtube.com/watch?v=NqJ-0EIsy9U&feature=youtu.be&t=5658[Marshall Rosenberg - NVC Workshop 2004 Portland, OR: 1:34:18-1:36:18], Mary Parker Follett, Power, Freedom and Authority in Management: Mary Parker Follett’s ‘Power With’-Domènec Melé and Josep M Rosanas-10.5840@pom20033221
- Intrinsic motivation vs Extrinsic motivation - Alfie Kohn [OFJCC Overemphasizing achievement]
- Internal motivation vs Extrinsic motivation - Alfie Kohn [OFJCC Overemphasizing achievement]
- Excellence vs Superiority - Is Meritocracy a Sham? | Amanpour and Company: link:https://www.youtube.com/watch?v=BLEvJUNfyBY&feature=youtu.be&t=592[9:52-11:32], link:https://www.youtube.com/watch?v=BLEvJUNfyBY&feature=youtu.be&t=910[15:10-16:24]
- Duty and Obligation vs Freedom and Choice - Maria Montessori, Peter Gray, Alfie Kohn, M. B. Rosenberg
- Retributive justice vs Restorative justice - M. B. Rosenberg, Miki Kashtan, Howard Zehr, link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]
- Violence vs Justice - link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]
- Oikonomia vs Chrematistike - Aristoteles, link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=273[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 4:33-6:41)], link:https://sci-hub.st/10.2307/40295009[Oikonomia versus Chrematistike: Learning from Aristotle about the Future Orientation of Business Management  - Claus Dierksmeier, Michael Pirson]
- Growth vs Development link:???[Manfred Max-Neef - Democracy Now]
- Agriculture vs Permaculture - Mark Shepard
- Efficiency vs Sufficiency and Well-being - link:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3357638/#Sec4title[Manfred Max-Neef - The World on a Collision Course and the Need for a New Economy: Chapter "Crisis of Crises"]
- School vs Education - Peter Gray
- Education vs Indoctrination - link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=771[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 12:51-13:41)], Peter Gray
- Consentual Rule and Dogma - M. B. Rosenberg [Consentual rules: Resolving conflicts with children workshop], link:https://www.youtube.com/watch?v=5EURJI9x9Qs&feature=youtu.be&t=771[(Manfred Max-Neef, Father of "Barefoot Economics" - Keynote at Zermatt Summit 2012: 12:51-13:41)]
- Interdependency vs Codependency - Alfie Kohn
- Process vs Product - Rachel Rainbolt - episode with peter gray, Peter Gray - Play
- Empathy vs Sympathy - link:...[M. B. Rosenberg], link:https://youtu.be/KX_tgRM84RA?t=370[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 6:10-8:08)]
- Empathy vs Forgiveness - link:...[M.B. Rosenberg - Creating Life Serving System Withing Oneself: ???]
* Intensity vs Consistency - link:???[Simon Sinek]
* To deserve something vs To need something
* Robustness vs Perfection link:https://www.youtube.com/watch?v=kzHrBM6CHfE&feature=youtu.be&t=1889[An Interview with Elinor Ostrom: 31:29-31:53]
* Participatory Democracy, Flatpack Democracy (Frome), Democratic Confederalism, Communalism, Stateless Democracy and Anarchist Communism, vs Autocracy, Representative Democracy, Authoritarianism, Populism, Fascism, Nazism and Nationalism etc. link:https://mesopotamia.coop/the-internal-system-of-the-communes-in-rojava/[(THE INTERNAL SYSTEM OF THE COMMUNES IN ROJAVA)]
* Einsamkeit (Loneliness) vs Selbstständigkeit (Autonomy)
* link:https://www.fachverband-gfk.org/wp-documents/anlage_3_schluesselunterscheidungen.pdf[und mehr Unterschiede...]

Culturally learned beliefs - Life-harming beliefs - irrational beliefs:

- spare the rod, spoil the child - Bible, Proverbs 13:24, Rosenberg - Resolving conflicts with children
- No pain, no gain. [RPM contradiction]
- Čím väčším peklom si prejdeš, tým silnejší z toho výjdeš. Ak z toho výjdeš. - (Jaroslav Slávik, Československo má talent)
- Tréning robí majstra.
- Better get used to it! (BGUTI - Alfie Kohn)
- Like it or not! [Alfie Kohn]
- That's just how it is. link:https://veganvanguardpodcast.com/how-competition-dominates-our-lives/(Mexie - 2. The Trope of “Competition” Dominates Our Lives: 2:04-2:28)
- There is no alternative. [M. Thatcher]
- Für jeden Preis.
- Es war schwierig zu schreiben, deshalb muss es schwierig zu sein, das zu lesen. [Kevlin Henney]
- You can have everything that you want only if only you just worked a litter harder. [contradiction to RPM and meritocracy]

== Resonance Performance Model [RPM]

by Doug Newburg

*The goal:* C++ programmer in Austria

*Das Ziel:* C++ Programmierer in Österreich

*1.) The Dream / Der Traum*

*Dream feelings / Traumgefühle:* +

* joy of learning / Freude an Lernen
* courage to make mistakes / Mut, Fehler zu machen
* relaxed speed / entspannte Geschwindigkeit
* easy effort / einfache Mühe
* connection to feelings and needs also under the most painful circumstances / Verbindung mit Gefühlen und Bedürfnissen auch unter den schmerzhaftesten Umständen
* empathic connection before correction / empathische Verbindung vor der Korrektur
* huge and accurate memory / riesengroßes und genaues Gedächtnis
* energy of a powerhouse / Energie eines Kraftwerkes
* empathy for everyone everytime / Empathie für jeden jederzeit
* calm limbs / ruhige Glieder
* quick reading with understanding / schnelles Lesen mit Verständnis
* energy without violence - joyful energy / Energie ohne Gewalt - freudvolle Energie
* success without victory - collective success / Erfolg ohne Sieg - gemeinsamer Erfolg
* programming with joy and lightness / Programmieren mit Freude und Leichtigkeit
* empathy with the ease of a hot knife cutting through a butter / Empathie mit der Leichtigkeit eines Messers, das durch die Butter geht
* joy of every single line of code that I write / Freude an jeder Zeile des Codes, die ich schreibe
* fulfilment of my needs that will be more effective and less costly to my and other people / die Erfüllung meiner Bedürfnisse, die effektiver und weniger kostlich für mich und andere Menschen ist
* Freude an Programmieren.
* Zufriedenheit mit meinen Fähigkeiten.
* Glauben an meine Fähigkeiten.
* fähige Unfähigkeit / competent incompetence, able disability / schopná neschopnosť link:https://en.wikipedia.org/wiki/Peter_principle#Summary[Peter Principle: Peter's Plateau / Final Placement]
* Schritt für Schritt
* strength in diversity
* breathing in the not knowing, playing in the not knowing / atment in Ungewisse, spielen in Ungewisse link:[(Yoram Mosenzon - ???)], link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4512[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 1:15:12-1:16:30]

*2.) Preparation / Vrobereitung*

* Training
* Exercise / Übung
** body / Körper
** mind / Geist
* (Perfect) preparation precedes mastery. +
  (Perfekte) Vorbereitung geht der Meisterschaft voraus. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???], link:???[Daniel Markovits - Meritocracy and Its Discontents: ???-???]

*3.) Obstacles, Successes / Hindernisse, Erfolge*

* Gefühle, erfüllte Bedürfnisse, Erfolge und Ergebnisse bei der Vorbereitung
* loosing connection with dream feelings / die Verbindung zu meinen Traumgefühlen wird schwächer

*3.5) Obstacle-Preparation Loop / Hindernis-Vorbereitungs-Schleife

* Burn-out spiral / Ausbrennungsspirale
* Lose of interest, energy, meaning, intrinsic motivation
* Depression
* ???

*4.) Revisiting the dream / Wiederverbindung mit dem Traum*

* Reconnection with my dream feelings. / Wiederverbindung mit meinen Traumgefühlen.
* Ask myself "How do I want to feel?". / Ich frage mich "Wie ich mich fühlen will?".
* Revisit my feelings, needs and the dream. / Meine Gefühle, Bedürfnisse, und den Traum wiederholen
* Revisit the feelings at unfulfilled and fulfilled needs. / Die Gefühle bei unerfüllten und erfüllten Bedürfnissen wiederholen.
* Burn-out prevention / Ausbrennungsprävention / Prevencia proti vyhoreniu.
* Expressing gratitude / Dankbarkeit äußern
* Empathize / Fühle dich hinein
* Empathy / Empathie
* Nonviolent Communication - NVC / Gewaltfreie Kommunikation - GFK
* Expressive writing link:...[(James W. Pennebaker - Researchgate link???)]
** Showing empathy to me, my inner educator and my inner chooser through NVC - talking or writing about my feelings and needs *in the present moment*, stimulated by various events. Talking about the past is the domain of psychotherapy and doesn't contribute to the healing of the pain. The more we spend in the past, the less healing takes place.
* How you feel is more important than what you do. +
  Wie du dich fühlst ist wichtiger als das, was du machst. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]
* Attitude is more important than aptitude. +
  Innere Einstellung ist wichtiger als Fähigkeit. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]
* The act of learning is more important than how well [or fast] I'm learning.
  Das, dass ich lerne ist wichtiger, als das, wie gut [oder schnell] ich lerne. +
  link:???[Alfie Kohn ??? + Cedric Dumont - From Fear to Flow ???]
* People who I let myself to inspire from / Leute von denen ich mich inspirieren lasse
** Ivo Toman - TAXUS Learninig - Lernen einer Fremdsprache durch gleichzeitiges Hören und Lesen eines wortwortlichen Textes in der Mutter- oder Fremdsprache, der zu dem gehörtem Text gehört.
** *Wim Hof - Wim Hof Methode*
** Marie Kondo - Konmari-Methode
** Blue Zones / Blaue Zonen - Forschung; überdurchschnittliche Gebiete mit überdurchschnittlicher Lebenslänge, z. B. Moai: Okinawa-Japan
** Simon Sinek - Intensity vs Consistency
** Josh Millburn & Ryan Nycodemus - minimalizmus
** Fumio Sasaki - minimalizmus
** *Maria Montessori - education; Buch: Montessori method / Il metodo della pedagogia scientifica applicato all'educazione infantile nelle case dei bambini* link:[(Maria Montessori - thehistorychicks: 1:24:24-1:24:32)]
** *Lucia Rolcekova - Pilates, Physiotherapie; ActiveClinic*
** *Kristina Zanova - Yoga; Rücken Rollen; ActiveClinic*
** Matus Chochlik - FRI UNIZA -> GlobalLogic
** Zdenko Pavlik - Scheid & Bachmann Zilina - Tankstellenabteilung -> GlobalLogic
** James W. Pennebaker - Expressive writing
** *Marshall B. Rosenberg - NVC: Nonviolent Communication*
** *Alfie Kohn - education, parenting*
** *Peter Gray - SDE: Self-Directed Education; play; Buch: Free to Play*
** Bethany Butzer - Stop trying so hard. Achieve more by doing less. Reference to Doug Newburg's research.
** *Doug Newburg - RPM: Resonance Performance Model*
** Milan Ondrasovic - Referenz zu Autophagozytose von Yoshinori Ohsumi
** Yoshinori Ohsumi - Autophagozytose: Hungern und seine Folgen aufs Gesundheit
** *Mihály Csíkszentmihályi - Flow*
** Cedric Dumont - From fear to Flow
** Miki Kashtan - NVC Management and Leadership
** *Daniel Markovits - Buch: The Meritocracy Trap*; Excellence vs. Superiority; "It's not about working hard, it's about doing the hard work. - connection to research from _Doug Newburg: Resonance Performance Model_"
** Lawrence Chong - Economy of Communion
** *Manfred Max-Neef - Barefoot Economy*: Economy based on fulfilling of each other's needs; **Human Scale Development**
** Christian Felber - Economy of Common Good / Gemeinwohl-Ökonomie
** Scott Meyers - Effective C++, More Effective C++
** Martin Fowler - Refactoring to Patterns
** Howard Zehr - Restorative Justice
** David Barter - Restorative Justice with NVC
** Carl R. Rogers - Humanistic Psychology; Humanism; Reference from M. B. Rosenberg and Alfie Kohn
** Mark Shepard - Permaculture; Buch: Restoration Agriculture
** Peter Kropotkin (Pyotr Alexeyevich Kropotkin) - Anarcho-Communism, Anarchist Communism, Kommunistischer Anarchismus; Bücher: Anarchist Communism: Its Basis and Principles; The Conquest of Bread
** David Harvey - Buch: The 17 Contradiction of Capitalism
** Ha-Joon Chang - Buch: 23 Thing They Don't Tell You About Capitalism
** Samuel P. Oliner, Pearl M. Oliner - Buch: _The Altruistic Personality: Rescuers of Jews in Nazi Europe_
** Sepp Holzer - Permakultur; Buch: Zahrada k nakousnuti
** Walter Kaufmann - Without Guilt and Justice: From Decidophobia to Autonomy
    *** concept of "deserve" broken
    *** retributive justice is suicidal
** James Gilligan - Violence: Our Deadly Epidemic and its Causes
** Elizabeth M. Elliott - Security, with Care: Restorative Justice and Healthy Societies
** Elinor Ostrom - The Tragedy of the Commons + Design Principles for Collective Managing of a Shared Resource - Arguments for collective ownership, collective decision making, communism and anarchism, and against capitalism, private [land] ownership
** Bruce Lipton, Peter Spork - Epigenetics

== Questions

Sources: +
link:https://www.goodreads.com/review/show/1151152216?book_show_action=true[Doug Newburg - The Most Important Lesson No One Ever Taught Me] +
link:https://www.researchgate.net/publication/254102089_The_process_of_performance_of_four_track_athletes_A_resonance-based_intervention[Doug Newburg - The process of performance of four track athletes: A resonance-based intervention → The Components of the RPM → ...Specific research questions
included...]

↓ +

* How do you like to feel every day? link:https://www.youtube.com/watch?v=nraBwnT2XlY&feature=youtu.be&t=302[(bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 5:02-5:12)]
* *Does how you feel affect how you perform?* Everyone says "yes", and yet most of you don't know how you like to feel. [Is this applied *emotional intelligence*? That the most successful are not the ones who have the highest IQ, but the highest EQ?] link:https://www.youtube.com/watch?v=nraBwnT2XlY&feature=youtu.be&t=312[(bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 5:12-5:22)]
* * * *
* *_How do I want to feel when I engage in my activities?_*
* How do I want to feel every day?
* How do I want to feel about my life in general?
* _*How do I perceive these feelings?*_
* _*How do these feelings affect my performance?*_
* _*How do these feelings affect my overall well-being?*_
* _What enables me to experience these feelings?_
* When these feelings happen?
* Where these feelings happen?
* Around whom these feelings happen?
* _*What inhibits me from experiencing these feelings?*_
* What takes these feelings away?
* What gets in the way of these feelings?
* _*How do I reconnect with my dream feelings when I face obstacles?*_
* How do I recreate these feelings?
* How do I experience these feelings again?
* Am I willing to accept the risk that I can fail in the activities I engage in? / Bin ich bereit dem Risiko unterzuziehen?
* Am I willing to accept the responsibility that I can succeed in the activities I engage in?

---

* Ist daran etwas schlechtes?
* Ist Angst vor Urteilen und Bewertungen mit Aufblasen verbunden?
* Wie hängt die Angst vor Urteilen und Bewertungen und Aufblasen und andere Gesundheitsbeschwerden mit dem Hirnnerv *Nervus Vagus* zusammen?
* If every activity that serves life and fulfills my needs is play, does it mean that when I get disconnected from my needs, I loose the ability to play?
* Wie kann ich über meine Schwächen und Fehler mit jemandem sprechen, ohne mich schuldig oder beschämt zu fühlen?
* Wo finde ich Energie für meine aktivitäten?
* How can I enjoy other people's pain?

---

* Wie fühlt sich vielleicht der andere Mensch?
* Wie fühle ich mich?
* Wie will ich, dass der Andere sich fühlt?
* Wie will ich mich fühlen?
* Wo finde ich Energie für Einfühlung?
* How can I learn from my mistakes without hating myself?
* Wie kann ich mich mit meiner Angst hineinfühlen und sie zu überwinden?
* What happens to me when I don't do what others want? → *Fear of punishment*
* What happens to me when I don't do what others want? → *Desire for reward*
* Do I want my failures and concerns to stop me from following my dreams?
* What keeps you from saying "yes"?
* What keeps you from fulfilling my needs?
* Was sage ich mir im Kopf, wenn ich diese Gefühle spüre?
* *Who benefits from this? / Wer profitiert davon?*
* Wie kombiniere ich Empathie und Optimismus?

---

* What makes people to enjoy violence?
* Why did we start to educate people to enjoy violence?
* Who benefits from education to violence and obedience?
* What makes people to enjoy contributing to the well-being of other people?
* What is this person feeling and needing?

---

* Do the activities have sense?
* What value has the task I engage in?
* What is the point of this task?
* Unterstützen Hausaufgaben die Ausbrennung in den Studenten?
* Auf welcher Weise formt die Erziehung durch Bestrafungen und Belohnungen die Sprache meines inneren Lehrer? link:???[Alfie Kohn - Unconditional Parenting + Punished by Rewards], link:???[M.B. Rosenberg - How do you talk to yourself when you're making mistakes?]
* Why punishment and reward never work?
** What would I want the other person to do differently? → _punishment sometimes works_
** What do I want the other person's reasons to be for doing what I request of them? → _punishment never works_
* What teaches punishment and rewards other people?
* What are my long term goals for other people to be?
* How I like them to turn out?
* What would I want the to be like?
* Is that what I'm doing consistent with what I want?
* Is that what I'm doing consistent with my long-term goals?
* Do the things that I say and do contribute to my long term goals?
* What are my long-term goals for other people to feel about themselves?
* What are my long-term goals for other people to feel about their life in general? [connection to Doug Newburg - Resonance Performance Model questions]

=== Connection Requests

* "Can you live with it?" link:https://www.youtube.com/watch?v=6rFMoUY6KpM&feature=youtu.be&t=3730[(Making Collaboration Real: Miki Kashtan: Maximizing Willingness for Collaboration Decision-Making: 1:02:10-1:02:15)]
* What do you think about it?
* How do you feel about it?
* Would this work for you?
* Do you like it?
* Do you have an idea what we can do?
link:https://www.youtube.com/watch?v=AJ-ctpWQkZA&feature=youtu.be&t=4216[Nonviolent Communication (NVC): Yoram Mosenzon workshop: 'Ask for the Moon': 1:10:16]
* What do you say about it?
* What feeling do you have from it?

=== Strategy Requests

* Will you do ...?
* Will you talk to ...?
* Will you tell me ...?

=== Restorative justice

A form of justice that concentrates on the restoring the relationships in the human, and between the human and the community. link:???[Barter - What is Restorative Justice - Youtube]

* Questions of justice

. What was the observable behavior of the perpetrator?
. Empathy of the perpetrator for the victim. - What needs was the perpetrator trying to meet? - Empathy with the perpetrator's inner chooser. Empathy with the victim's unfulfilled needs. The cost or impact of the perpetrator's behavior to the needs of other people.
. Giraffe mourning on the part of the perpertator. - What needs the perpetrator didn't meet by his/her behavior? - Self-forgiveness within the perpetrator
. Searching for ways to get everybody's needs met that would be more efficient and less costly. - Repairing the harm and healing the pain with concrete activities of the perpetrator that will contribute to life well-being of others.

[options="header"]
|===========================
| Retributive Justice | Restorative Justice (H. Zehr) | Restorative Justice (M. B. Rosenberg [NVC])
| What law was broken? | What happened during the crime? +
                         What happened before the crime? |
                                                           - *Helping the perpetrator to empathize with the pain of the victim.* +
                                                           1.) What was the  observable behavior of the perpetrator? +
                                                           2.) What was the  observable behavior of the victim? +
                                                           3.) How dit the victim feel? +
                                                           4.) What needs weren't met by the victim? +
| Who broke that rule? | Why did it happen? | *Giraffe mourning on the part of the perpetrator. Empathy with the perpetrator's inner educator* +
                                              1.) How is the perpetrator feeling after empathizing with the victim? +
                                              2.) What needs weren't met on the part of the perpetrator? +
                                              
                                              *Empathy with the perpetrator's inner chooser* +
                                              3.) What needs was the perpetrator trying to meet?
| What the punishment will be? | What can we do to repair the harm? | *Searching for ways to meet everybody's needs that will be more effective and less costly.* +
                                                                      1.) What can we do to fulfil these needs?
|===========================

** link:https://slideplayer.com/slide/6835782/[Building Positive Relationships Through Restorative Justice - Joan Packer]
** link:https://www.youtube.com/watch?v=Ccz55SO4Ah4&feature=youtu.be&t=2221[Howard Zehr - Human Rights Meets Restorative Justice: 37:01-???]
** Phases of restorative justice by NVC link:...[M.B. Rosenberg - Creating a Life Serving System Within Oneself ???]

== Play

by Peter Gray, author of _Self-Directed Education [SDE]_

Ich kämpfe nicht. Ich übersetze alles in die Sprache des Lebens.

Ich arbeite nicht. Ichspiele. Ich lerne. Ich mache.

Hypothese: Jede Aktivität hat in sich Elemente eines Spiels.

Hypothese: Jede Aktivität ist ein Spiel, solange sie unsere Bedürfnisse erfüllt.

Hypothese: Alles, was ich mache, mache ich, um meine Bedürfnisse zu erfüllen.

* *Don't do anything that isn't play.* link:...[M.B. Rosenberg: ???-???; Joseph Campbell]

** How to make every activity a play? +

*** *It will be play if you're connected to your needs.* link:...[M.B. Rosenberg: ???-???]
*** Everything I do is play.
*** I do everything that serves life as if it was play.
*** I do everything as if it was play. [At least I try :P ]

*What is play?* +
Play is an activity that has following _[5 - may be more, may be less]_ characteristics:

. It's freely chosen and self-directed.

    * Freedom to change the rules.
    * Freedom to choose the activity.
    * Freedom to quit the activity at any time.
    * Balance between skills and challenge: what you can do and what can be done [Flow]. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]

. *You are doing it for its own sake.*

    * The activity is autotelic. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]
    * You are not doing it for some reward that's outside of the play itself.
    * Means over the end.
    * Process over product.
    * Skill over result.
    * Intrinsic over extrinsic.
    * The joy of play is in the doing, not in the end product.
    * You do the activity do make the next step in the activity. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]
    * You do the activity not because of the end result. +
    You do the activity because you want to do the activity. Because you like how you feel when you do the activity. And you like it so much you want to do it every day. link:https://youtu.be/nraBwnT2XlY?t=255[bromont 1 - Doug Newburg - RPM - Resonance Performance Model: 4:15-5:02]
    * How you feel is more important than what you do. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * The act of learning is more important than how well you are learning. link:???[Alfie Kohn: ???-???]

. *Play is always guided by rules.*

    * The rules create the structure. The structure is the rules.
    * There is no such thing as unstructured play. Play always has a structure. Play is not a random activity. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * The structure is always determined by the players. The players themselves choose which rules they want to follow. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * Consensual rules [M.B. Rosenberg]

. *Play involves elements of imagination.*

    * Play encourages hypothetical thining: "If this was true, what follows from that?" link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * *Hypothetical thinking is the highest form of human thinking. _[IQ]_* link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * *Observing without evaluating is the highest form of human intelligence. _[EQ]_* link:???[Jiddu Krishnamurti]
    * That's why we can plan for the future, prepare for tomorrow, invent things. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * None of these abilities can be taught by lecturing, although they are essential life skills. These abilities can only be obtaines through practical experience, through practice. For children is this practical experience, mainly, play. They are preparing themselves for a responsible life. link:???[Rachel Rainbolt - Episode ??? - Peter Gray: ???-???]
    * Both, hypothetical thinking and observing without evaluating helps me to concentrate on what's alive in me and other people - our feelings and needs. Even if it involved screaming my feelings and needs!

. *Play involves relaxed, highly attentive, but not highly stressed attitude.*

    * Why not highly stressed?
    ** Because there are no consequences to it.
    ** You are free to fail.
    ** You are not going to blame anybody. [There is no need for it.]
    ** There is no trophy; there is no cake. link:???[The cake is a lie. (Portal)]
    ** You are not going to get an F from some teacher.
    ** You are free to quit.
    ** You are not concerned about even succeeding. link:???[Happiness and Its Causes - Mihály Csíkszentmihályi 2014 Living in Flow: ???-???]

. *Play always involves challenges.*

    * One of the challenge is: "How much fear can I tolerate?".
    * You are playing with your own fear.
    * We develop a sense of our own abilities.
    * We learn how to manage fear.
    * *I can feel fear, and I can survive it.*
        ** This discovery can be very empowering. It makes you less affraid of life. It helps you live your life courageously. Things can happen that are scary and I can deal with them.
        ** If you are deprived of this kind of risky play that involves deliberately putting yourself into a scary situation, then the first time you feel a real emergency in your life, you might fall apart because you didn't have the opportunity to practice how to deal with fear, how to control your body, how to control your mind, [how to control your own emotions and show yourself empathy,] when you feel fear.
    * If something serious happens, [or you get stuck,] ask for help.
    * *To protect children from any possible harm by nnot allowing them adventures or risky play, and never allowing them to get out of our sight and control, is having harmful long-term consequences on children.*
    * Someone who is willing to take more eisks in the daily life will not only become better and improve, expand the comfort zone, but also more fulfilled, happy and satisfied. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * You'll learn how to accept and learn from failure. It leads to sustainable resuslts, more engagement, satisfaction, [instrinsic] motivation. link:???[Cedric Dumont - From Fear to Flow: ???-???]
    * When you stop taing risks, you stop living a life. link:???[Cedric Dumont - From Fear to Flow: ???-???]

== Nonviolent Communication (NVC) / Gewaltfreie Kommunikation (GFK) / Nenásilná Komunikácia

Nonviolent communication is a way of

* talking (language),
* thinking (emotional intelligence),
* communication (communication skills, dialogue) and
* using power (means of influence, management, parenting, leadership)

Sources: +
link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=614[Self Empathy: 10:14-11:16] +
link:https://www.youtube.com/watch?v=GZnXBnz2kwk&feature=youtu.be&t=92[CNVC org Session #1 Introduction Nonviolent Communication Training Course Marshall Rosenberg: 0:01:32-0:01:57]

* What is the message of all religions?
** To live compassionately. To not do anything that isn't play. Unfortunately, religions are vague in the specific ways, how to live compassionately and enjoy compassionately.
* What skill do we need to live compassionately?
** Language, thinking, communication and use of power.
* Why don't we educate peopleto live compassionately, but instead we educate them to enjoy violence?
** We have been educated to enjoy violence, in order to contribute to the structures [institutions] of the society. In these structures are people that claim to be superior and know what's right for others, and have the power to impose what they believe is right on others. That way of living requires a certain way of thinking, communication, talking and using power. That is the problem. [The sustaining of the structures is more than contributing to the well-being of the society.]
* How are we meant to live?
** To live naturaly, compassionately.
* How to live natrally?
** Natural living is the usage of our power to enrich my and other people's needs.

* The entire concept of a mental illness and the attribution of the violence as a cause of the mentall illness takes the focus away from the education [and upbringing] that the structures provide which create the [environment for] violence.

=== Nurturing, parenting, upbringing to violence

Source: link:???[M.B. Rosenberg - Erziehung zur Gewalt]

. Educate people to use *jackal language* link:???[(CNVC Training Session 1 - ??? - ???)]
* Jackal language = Static language
** A language of domination, Punishment (criticism, blame), Rewards (praise, compliments)
** A language that is
*** disconnected from life [i.e. feelings and needs] and
*** violence provocative link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6137[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 1:42:17-1:44:56]
in order to maintain domination structures.
** A language that makes it difficult to resolve differences. link:???[NVC Denmark Workshop, CNVC Session 1]

* Educate people to think what's wrong with them. Educate people to think what they are, so that they in each moment wonder whether they are right or wrong, good or bad, normal or abnormal, appropriate or inappropriate etc. +
Judge yourself with moralistic judgements.

* Educate people to think what other people are. Educate people to think what's wrong with other people. Whether other people are normal or abnormal, kind or unkind, responsible or irresponsible, selfish or generous, lazy or hard-working etc. +
Judge other people with moralistic judgements.

* Educate people to think what other people think of them. What will other people say? What will other people think?

* Teach people the concept of *deserve* link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=1230[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 20:30-], link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6137[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 1:44:56-1:45:15]
** Teach them that you need to deserve love. That you have to earn it.
** But if they behave in a way that's judged _bad_, teach them they deserve to suffer.
** Teach them that if other people behave bad, they deserve to suffer.
** We've been systematically educated in a way that makes violence enjoyable. [e.g. through media, television, society, institutions and religion]. ... Always for good reasons: to serve the God and serve the country. link:https://youtu.be/jArsTeP66FE?t=6222[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg: 1:43:42-1:44:56]
** The concept of deserve makes violence enjoyable.
** There are whole cultures and countries who speak nonviolent communication [Rojava - northern Syria, Orang Asli - Malaysia]. They have hardly any violence. They don't know what punishment means. It doesn't make any sense to them, why one person wanna hurt another person. It only makes sense when you believe they deserve it. Why do they deserve it? Because are labeled negatively by moralistic judgements. link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=6528[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg: 1:48:58-1:49:18]

* Teach them that punishment is sometimes necessary. +
Teach them to use punishment to get their needs met.

* Teach them to use rewards to get what they want.

* Teach them to use guilt and shame to manipulate.

* Teach them to do things to get influence out of the concept of duty and obligation.
** This requires teaching them a language that denies choice. *Amtssprache*.
** Such as there are some things you gave to do. That you have no choice. It's your duty and obligation.
** Amtssprache link:???[M.B. Rosenberg - San Francisco Workshop ???-???], link:???[Eichmann in Jerusalem]
*** a language that denies responsibility and denies choice, i.e. it implies that we have no choice
*** a language that denies reponsibility for my actions
*** a language that implies that I have no choice
*** Examples: +
**** "There is no alternative." [TINA; you must!] - link:https://en.wikipedia.org/wiki/There_is_no_alternative[Margaret Thatcher]
**** "There is no such thing as society." - link:https://newlearningonline.com/new-learning/chapter-4/margaret-thatcher-theres-no-such-thing-as-society[Margaret Thatcher]
**** "There are just some things you have to do!"
**** *must, should, ought, can't, have to*
**** *it's the [company] policy, rule, law, order, tradition, habit*

. Teach people *retributive justice* link:???[(CNVC Training Session 1 - ??? - ???)], link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=1230[Film 02 SELF EMPATHY Session 1 - M.B. Rosenberg - 20:30-]
* It's all about the word *deserve*.

But why did we start to educate people to enjoy violence?

Because this education works in sustaining dominantion structures. [M.B. Rosenberg - Experiencing Needs As Gifts] +
This education makes us obedient to authority. +
This language makes us obedient to authority. [It's a language of domination.] link:???[CNVC #1 ~31:00]

What happens to people if we educate them to enjoy violence?

. [Either] they become nice, dead people. +
They do what they're told by the people above. They do what their parents want. They do what their teachers want. What the bosses want. What the government wants. They are nice, dead people.
. Or they become monsters.

The education to violence is just a temporary thing. Although it takes for approximately 5000 years. By the paleontologist Pierre Teilhard de Chardin, we are gradually returning back to the ways of living that are more natural.

Everything that we do out of penitence or self-hate, fear of punishment, desire for reward, concept of deserve, duty, obligation, submission, rebellion, giving in or self-sacrifice, buying love, guilt, shame, anger, depression, everybody pays for it. Therefore *don't do things for other people. Do things only when you do so willingly to enrich your and other people's life.* If you do things from the energy that damages life, it will affect commitment to values that serve life, care about other people, depth of thinking, interest in learning, preference to challenge link:???[M.B. Rosenberg] link:???[tilt parenting], link:???[alfie kohn ofjcc]

== Fascism

Mussolini created the _Fasci Italiani di Combattimento (Liktorské zväzky prútov)_ which consisted mostly of men and *glorified violence*. Violence lies at the heart of fascism. link:https://www.youtube.com/watch?v=uE-ewzt9Yfg[What is Fascism? | World History Project: ] +
_Liktor_ - služobník, ktorý chráni kráľa.  link:https://de.wikipedia.org/wiki/Liktor[Liktor - Wiki]

*What is Fascism?* link:https://www.mtholyoke.edu/courses/rschwart/hist151/Paxton_Fascism/Paxton_mainpoints.htm[Robert Paxton] +
Fascism may be defined as +
a form of political behavior +
marked by obsessive preoccupation with community decline, humiliation, or victimhood +
and by compensatory cults of unity, energy, and purity, +
in which a mass-based party of committed nationalist militants, +
working in uneasy but effective collaboration with traditional elites, +
abandons democratic liberties +
and pursues with redemptive violence and without ethical or legal restraints goals of internal cleansing and external expansion.

* Fascism, authoritarianism or populism support *power over* people, not *power with* people [like Mary Parker Follett did].

== Quotes

*The Montessori Method*

* Chapter 15: Intellectual Education (librivox)

** 0:49-1:33

    *** The directress/educator intervenes to lead the child from sensations to ideas, from the concrete to the abstract and to the association of ideas. For this, she uses a method which isolates the inner attention of the child and to focus it upon the perceptions. As in the first lessons, his objective attention was fixed in isolation upon single stimuli. The teacher, in other words, when she gives a lesson limits the field of the child's consciousness to the object of the lesson. As, for example, during the sense education, she isolated the sense which she whished the child to exercise.
        **** When the teacher gives a lesson, he limits the field of consciousness of the student to a single stimuli - to the object of the lesson - e.g. by exercising only one of the student's senses at a time.

** 1:39-1:53

    *** The educator limits his/her intervention to the greatest possible extent, and at the same time shows care for the other person's well-being by *requesting* the other person to stop the autoeducation when the educator sees that the other person feels tired.
    **** Intervention: As much as necessary, but as little as possible.
    
** 2:01-2:10

*** ... in other words, in the quality of the teacher's intervention lies the art which makes up the individuality of the teacher.
  **** maybe NVC will improve that quality)

** 2:10-2:17

*** An important part of the teachers work is that of teaching an *exact nomenclature*.
**** Describing things accurately
**** pronouncing clearly and loudly
**** explaining the meaning and differences understandably

** 4:56-6:23

    *** But, if he has not done this, that is, if he makes a mistake, she does not correct him, but suspends her lesson to take it up another day. Indeed, why correct him? If the child has not succeeded in associating the name with the object, the only way in which he succeeds would be to repeat both the action of the sense stimuli and the name. In other words, to repeat the lesson. But when the child has failed, we know, that he was not at that moment ready for the psychic association which we wished to provoke in him. Therefore, we choose another moment. If we correct the child by saying "No, you have made a mistake!", all these words, which, being in the form of reprove, would strike him more forcibly and would remain in the mind of the child retarding the learning. On the contrary, the silence which follows the error leaves the field of consciousness clear and the next lesson may successfully follow the first. In fact, by revealing the error we may lead the child to make an undue effort to remember, or we may discourage him. And it is our responsibility to avoid, as much as possible, all unnatural effort, and all the pressure [depression].

** 8:08-8:17

    *** The teacher carefully watches when and how the child arrives at the generalization of ideas.

** 9:13-9:21

    *** The goal of education is to promote the *spontaneous* development of a human. / Das Ziel der Ausbildung ist, die spontane Entwicklung des Menschen zu unterstützen.

** 10:50-11:20

    *** We can not create observers by saying "Observe!", but by giving them the power and the abilities for these observations. And these abilities are obtained through the education of the senses. Once we have aroused such an activity, autoeducation is assured. Refined, well-trained senses, lead us to a closer observation of the environment, and this with its infinite variety attracts the attention and continues the psychosensory education.

** 13:16-13:28

    *** The spontaneous development of the child continues indefinitely and is in direct relation to the psychic potentiality of the child himself and not with the work of the teacher.

** 13:28-13:39

    *** The spontaneous activity starts from the education of the senses, and is maintained by observation.

** 13:29-13:49

    *** The human receives his/her ability, not from the education given by the master, but from special acuteness/sensitivity of his/her senses.

** 13:49-14:03

    *** When somebody is in an environment where he/she can apply his senses in his/her's spontaneous activity, the activity itself gives him/her the pleasure, joy and fulfillment

    **** Develpoment of intrinsic motivation (Alfie Kohn)
    **** The activity becomes *autotelic* (Mihály Csíkszentmihályi - Flow)
    **** Process over Product (Rachel Rainbolt, Peter Gray)

* Montessori put her theories into practice in *Casa dei Bambini* in San Lorenzo, 1907. +
Until that time people had thought of children as empty vessels or cups which had to be filled with knowledge. Knowledge was simply poured into them. All he children had to do was to sit still and take it in. Maria Montessori observed that children learned in a very different way. That they spontaneously reached out for knowledge, that they explored they created. Looking at very young children we can see the spontaneity. And in fact, a lot of what was happening in schools was preventing that and stopping children [from being spontaneous]. +
She believed that, if given the opportunity, children would rather focus their attention on work than idleness. +
Montessori discovered so many years ago what modern research is confirming today: that children learn best from their own activity. They learn best when they're active and exploring. And she found a way to make this possible. +
It was a scientific experiment. What she observed in a San Lorenzo project became the basis of Montessori education. She created a new environment. One completely diffrent from mainstream schools in Italy. +
All inovation in Montessori education didn't come about necessarily because Montessori said "We have to do that!". She saw "Well, this is something that I observed children do, and I'm curious how this will affect their experience." And then she applied the science to it. +
As she watched the children engaging with the new materials, she observed that this formally naughty children thrived on learning. They would work for the sake of working and would become completely engaged in their task. +
One child of 4 became so engrosed in her work that when Maria had the other children dance around, and make as much noise and fuss as possible, the girl never deviated from her task. Maria then lifted her from her seat, but the girl just continued working. [Is this a demonstration of *Flow* by Mihály Csíkszentmihályi?] +
Maria also observed that children had an innate love for order. +
The parents often say "Oh, my child doesn't like to tidy up at all." But actually they enjoy doing it, they like the idea of putting something back in order so that it's ready for someone else to use. And at the end of the day you'll often find children on their own deciding around the children's house rolling up matts, making things straight on the shelf. It's a sense of caring for a space, caring for the community. [Is this a demonstration of *The Altruistic Personality* from Samuel and Pearl Oliner?] +
She thought them simple acts of cleanliness, like how to blow their nose. No one had ever told them how to to this before. Montessori understood that children have a sense of personal dignity often not recognized by adults. Neither they require rewards or punishments. The acts they were engaged in were rewarding enough. But the most surprising and remarkable of all her observations was when these children without her orchestrating it taught themselves to read. She had introduced some paper letters mounted on wood as a multisensory tool. The children could trace them with their fingers, feelilng the shape and learning the sound of the letter. She gave them no other instructions. +
The children began put together sounds of words they knew. When they heard a word they didn't know, they could decompose it to letters by sound and write it down. *Montessori managed to ignite an explosion of ideas in children.* +
The *Casa dei Bambini* was an enormous success. Montessori method was starting to get more popularity and attention. Legislators, teachers, parents and doctors [were impressed by the results of this method and] soon started to use this method in their practice. In 1909 she published her book *Il metodo della pedagogia scientifica applicato all'educazione infantile nelle case dei bambini*. In 1912 this book was translated to English and published with the title *The Montessori Method*. The book was translated into multiple languages and spread across the world. link:https://www.kpbs.org/news/2014/jul/16/extraordinary-women-maria-montessori/[Image: Popularity of Montessori method in the world in ~1912]. *Almost the entire world wanted to use Montessori method.* Even the academia. Maria started a revolution in education. link:https://youtu.be/TXqeTYHn0p4?t=1282[(Maria Montessori: 21:22-28:03)] +
By 1913 were in USA almost 100 Montessori schools. +
Then in 1914 war broke out across the Europe. +
To Maria, the appaling devastation convinced her that *there should be a connection between education and pacifism*. "Now comes the time for our work. We are working for peace and humanity midst the inhumanity of war. Our eyes are turned to a little child where lies the future and the hope of our world." +
In France and Belgium Montessori schools were set up for the orphans of the conflict. +
After the first world war, Maria Montessori returned to Italy, only to walk into the path of the world's most ambitious man. *Benito Mussolini* was impressed ... by the discipline of the students educated by Montessori method. He wanted to build a new efficient and industrial country. Mussolini supported Montessori and her's education. ... Mussolini and Montessori cooperated, but neither of them were happy with it. *The trouble was that Montessori believed that children learn best as  [responsible,] independent, free thinkers.* But free thinking was not something that Il Duce was intrested in. *Mussolini's aim was to create a nation of [obedient,] disciplined and loyal fascist.* The idea of Montessori education was educating people to think for themselves, and act for themselves, and was *scientific* rather than political. ... *"The goal [of education of Mussolini and fascism] is total indoctrination. From childhood to the soldiers grade. Fascism shapes young minds with Italy's destiny and the beauty of war."* In 1931 Mussolini announced that all schools must conform to fascism. Maria refused outright. Maria Montessori and her partner left in a hurry. In 1931 she lef her homeland never to live there again. *Within months Mussolini closed all Montessori schools in Italy.* ... Maria Montessori met with Ghandi in London. They had a great connection. Ghandi supported her philosophy: the element of community, an education that can work with all children in all cultures. *Hitler closed down all Montessori schools in Germany. In Berlin, all Montessori books were thrown on burning piles.* [Mussolini and Hitler (and fascist) didn't like citizens that ask "Why?" and complain about regulations] link:https://www.youtube.com/watch?v=TXqeTYHn0p4&feature=youtu.be&t=1785[Maria Montessori: 29:45-38:47], link:???[Episode_143-Maria_Montessori-thehistorychicks: 1:24:01-1:40:38] +
The world piece can only be achieved by the education of the children. link:https://www.youtube.com/watch?time_continue=7&v=TXqeTYHn0p4&feature=emb_logo[Maria Montessori: 43:19-43:28] +
But in the absence of Maria Montessori, much of her work had been forgotten. link:https://www.youtube.com/watch?v=TXqeTYHn0p4&feature=youtu.be&t=2638[Maria Montessori: 43:58-44:04] +
In 1945 Maria Montessori started to revive and reestablish her education in preschools and schools in Europe. Many of the creative people benefitted from early Montessori education. *The life should be challenging, and the challenge should be fun. [Larry Page & Sergey Brin - Founders of Google - both educated in Montessori method]* link:https://youtu.be/TXqeTYHn0p4?t=2647[Maria Montessori: 44:07-46:00] +
*Don't look at me. Look at the way I'm pointing.* link:https://youtu.be/TXqeTYHn0p4?t=2647[Maria Montessori: 47:21-47:40]

* Maria Montessori didn't see any virtue in obeying. link:???[Episode_143-Maria_Montessori-thehistorychicks: 1:35:48-1:35:53]

* Few parents have the courage and independence to care for the children's happines than about their success.
[Erich Fromm; Alfie Kohn - Unconditional Parenting: Moving from Rewards and Punishments to Love and Reason: ch. 5 - "Pushed to succeed", p. 75
; Alfie Kohn at the OFJCC - Performance vs. Learning - The Costs of Overemphasizing Achievement: ???-???]

* ... because if I persuade you that something ... you're doing with kids is getting in the way, not what I happen to like, but of your own long-term goals for other people then either you have to rethink the practice or you have to rethink the outcome.
(Alfie Kohn at the OFJCC - Performance vs. Learning - The Costs of Overemphasizing Achievement: 10:45-11:04)

* There was less cheating when [the teachers] made it clear that the point was to enjoy the learning, when understanding mattered more than memorizing, and when mistakes were accepted as a natural result of exploration. link:alfiekohn.org/???[Alfie Kohn - Who's Cheating Whom, paragraph 11], link:https://montessoritraining.blogspot.com/2013/09/montessoris-three-levels-of-obedience.html[Mistakes - Montessori]

* Leadership is not defined by the exercise of power but by the capacity to increase sense of power among those led. The most essential work of the leader is to create more leaders. link:https://scontent.fbts2-1.fna.fbcdn.net/v/t1.0-9/31781853_10156828091695628_8027792006530990080_n.png?_nc_cat=106&_nc_sid=8024bb&_nc_ohc=sdfVZfeBPpoAX84ENlX&_nc_ht=scontent.fbts2-1.fna&oh=35dff8d3e47555a204245ba9ae13be32&oe=5F25FD09[(Mary Parker Follett)]

* Other critics of the homo economicus model of humanity, such as Bruno Frey, point to the excessive emphasis on extrinsic motivation (rewards and punishments from the social environment) as opposed to intrinsic motivation [not internal!]. For example, it is difficult if not impossible to understand how homo economicus would be a hero in war or would get inherent pleasure from craftsmanship. Frey and others argue that too much emphasis on rewards and punishments can "crowd out" (discourage) intrinsic motivation: paying a boy for doing household tasks may push him from doing those tasks "to help the family" to doing them simply for the reward. +
Another weakness is highlighted by economic sociologists and anthropologists, who argue that homo economicus ignores an extremely important question, i.e. the origins of tastes and the parameters of the utility function by social influences, training, education, and the like. The exogeneity of tastes (preferences) in this model is the major distinction from homo sociologicus, in which tastes are taken as partially or even totally determined by the societal environment (see below). +
Further critics[citation needed], learning from the broadly defined psychoanalytic tradition, criticize the homo economicus model as ignoring the inner conflicts that real-world individuals suffer, as between short-term and long-term goals (e.g., eating chocolate cake and losing weight) or between individual goals and societal values. Such conflicts may lead to "irrational" behavior involving inconsistency, psychological paralysis, neurosis, and psychic pain. Further irrational human behaviour can occur as a result of habit, laziness, mimicry and simple obedience. +
The emerging science of "neuroeconomics" suggests that there are serious shortcomings in the conventional theories of economic rationality.[16] Rational economic decision making has been shown to produce high levels of cortisol, epinephrine and corticosteroids, associated with elevated levels of stress. It seems that the dopaminic system is only activated upon achieving the reward, and otherwise the "pain" receptors, particularly in the pre-frontal cortex of the left hemisphere of the brain show a high level of activation.[17] Serotonin and oxytocin levels are minimised, and the general immune system shows a level of suppression. Such a pattern is associated with a generalised reduction in the levels of trust. Unsolicited "gift giving", considered irrational from the point of view of homo-economicus, by comparison, shows an elevated stimulation of the pleasure circuits of the whole brain, reduction in the levels of stress, optimal functioning of the immune system, reduction in cortico-steroids and epinephrine and cortisol, activation of the substantia nigra, the striatum and the nucleus acumbens (associated with the placebo effect), all associated with the building of social trust. Mirror neurons result in a win-win positive sum game in which the person giving the gift receives a pleasure equivalent to the person receiving it.[18] This confirms the findings of anthropology which suggest that a "gift economy" preceded the more recent market systems where win-lose or risk-avoidance lose-lose calculations apply.[19] +
Sources:+
16 Schmitz, Sigrid; Köeszegi, Sabine T.; Enzenhofer, Bettina; Harrer, Christine (2015). "Quo vadis homo economicus? References to rationality/emotionality in neuroeconomic discourses". Recent Notes on Labor Science and Organization. University of Vienna (Universität Wien). Pdf.
17 Rilling, J.K.; Sanfey, A.G.; Aronson, J.A.; Nystrom, L.E.; Cohen, J.D. (2004). "Opposing BOLD responses to reciprocated and unreciprocated altruism in putative reward pathways". NeuroReport. 15 (16): 2539–2543. doi:10.1097/00001756-200411150-00022. PMID 15538191.
18 Kosfeld, M.; Heinrichs, M; Zak, P.J.; Fischbacher, U.; Fehr, E. (2005). "Oxytocin increases trust in humans". Nature. 435 (7042): 673–676. doi:10.1038/nature03701. PMID 15931222.
19 Bowles, Samuel and Herbert Gintis "A Cooperative Species: Human Reciprocity and its Evolution" (Princeton University Press; Reprint edition)

* There are three ways of dealing with difference: domination, compromise and integration. By domination only one side gets what it wants; by compromise neither side gets what it wants; by integration we find a way by which both sides may get what they wish. [NVC supports integration ;) ] link:https://www.toolshero.com/toolsheroes/mary-parker-folett/#:~:text=Mary%20Parker%20Follett%20quotes,is%20to%20create%20more%20leaders.%E2%80%9D[Mary Parker Follett], link:miki.kashtan_2020[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 30:14-32:57)]

* Internalized Powerlessness: link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=1008[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 16:48-22:20)]

    ** The upbringing to powerlesness and obedience starts with teaching kids the question "Can I ...?" +
    [Alternative questions: "Will I take <something> / Will I <do an action>? / I want to <...> What do you say?"]
    ** When I say someone, e.g. a child, that he *can not do* something, then I interfere with what is true physically. I not only control the others, but also mess with their understanding of the reality. If I tell the somebody *No, you can not turn on the TV* when in reality I'm saying *I really don't want you to turn on the TV, and if you turn on the TV I will punish you!*
    ** Between the somebody's action and my reaction is my choice.
    ** We are not sufficiently inner oriented to our own needs and our willingness to decide which consequence to my action am I willing to accept. So Nonviolence is to face whatever will be the consequeces of our action so long as they are inline with our needs.
    ** If we are trained to be fearful of our consequeces we're less likely to feel powerful.
    ** Samuel P. Oliner, Pearl M. Oliner - *The Altruistic Personality*
        *** *People who saved Jews, tended to come from nonpunitive households.*
        *** [big]*If you come from a nonpunitive houshold, you're less oriented towards fear, and more more oriented towards needs and intrinsic motivation.*

* Flatpack Democracy - Frome, England link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=4434[(Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 1:13:54-1:14:39)]
    ** ... if you don't have facilitation, you're less likely to have an integrated result.
    
* link:https://www.youtube.com/watch?v=mErG7mSzwkc[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1]
  ** 7:20- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=440
  ** 8:29- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=509
  ** 9:57- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=597
  ** 12:36- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=756
  ** 15:50- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=950
  ** 17:59- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1079
  ** 21:01- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1261
  ** 22:23- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1343
  ** 26:31- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1591
  ** 27:53- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1673
  ** 30:11- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=1811
  ** 39:06- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2346
  ** 42:37-42:54 https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2557
  ** 46:05- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2765
  ** 48:09- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2889
  ** 50:34- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3034
    *** *Restoring the centrality of the needs is an entirely subversive move.*
    *** *In society at large, it is incredibly destabilizing for people to imagine, shifting from "you earn what you deserve" to "you receive what you need on the basis of there being enough". ... It question too much of what we take for granted.*
  ** 51:47- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3107
  ** 54:50- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3290
  ** 55:47- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3347
  ** 1:04:12- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3852
  ** 1:04:40-1:05:47 https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=3880
    *** *When you put needs at the center everything changes. ... What it would look like to put needs in the center rather than concepts. Not even the concepts of rights. Because rights, again, it's a human construct, and then we can debate about it. *Needs are biologically and relationaly given. [Needs] are indisputable. [... because all human beings have the same needs. - M.B. Rosenberg]* "The human beings of the future will be rich in needs. Whereas the human being under capitalism is reduced to one need, which is the need to have [and have more]".
  ** 1:08:05- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4085
  ** 1:08:28- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4108
  ** 1:09:21- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4161
  ** 1:09:56- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4196
  ** 1:12:33- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4353
  ** 1:13:03- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4383
  ** 1:15:12-1:16:30 https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4512
    *** *Instead of having an expectation, you can have faith in it. And by moving from expectation to faith, you are aligning with life. Because faith by necessity has no control and no knowing. When you have an expectation of receiving, you have a contract with life. And the contract says "life is going to give me enough". Contract can be broken. Faith has no limit, no end, it can't be proven or unproven. Embracing not knowing is one of the most curative things I know to the illness of patriarchy. ... And to trully embrace not knowing is so liberating.*
  ** 1:22:33- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=4953
  ** 1:24:53- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5093
  ** 1:26:58- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5218
  ** 1:28:08- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5288
  ** 1:28:54- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5334
  ** 1:30:13- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5413
  ** 1:35:30- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5730
  ** 1:37:33- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5853
  ** 1:38:24- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5904
  ** 1:39:32- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=5972
  ** 1:42:14- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=6134
  ** 1:44:53- https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=6293
  
* link:https://www.youtube.com/watch?v=mCyWaSPmRkA[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 2 - From Competition, Command & Control to Collaboration for a Shared Purpose]
  ** 0:17-2:44
    *** *Collaboration is a voluntary activity that starts with togetherness, shared purpose and willingness to come up with a joint strategy. Collaboration means constantly adapting to our differences.* If that's true then structures that we have in the world are fundamentally opposed to that happening. Withing the context of *competition* it is incredibly difficult to create collaboration. [We assume scarce resources, not that it will be enough for everyone.] Because competition, by definition, means individuals against each other, or teams against each other, or always something against something else. 
  ** 3:24-4:05
    *** *Competition is one obstacle to collaboration. The other one is the structure of command and control.* Our current structures have *competition horizontally [among people at the same position in a hierarchy]* and *command and control vertically [from top to bottom, among different levels in a hierarchy]*. There is some competition between levels [when we deal with promotions].
  ** 4:53-
    *** How command and control interferes with collaboration? If I am in power, you are less likely to speak truthfully to me. If you don't speak truthfully to me, we don't collaborate. There are 4 things that you are less likely to tell me if you have less power:
    **** *Your needs*. Because the needs of the powerful, the ones on the top in a hierarchical structure, are prioritized.
    **** (7:26) *Your perspective on things*, when a decision is dictated on you from above, and you have no say about it. It creates lack of trust and apathy.
    **** (8:43) *Your creativity*. There is a myth that wisdom emerges from universities and the more elite the university, the more wisdom you have. [intellectual vs emotional wisdom]. Wisdom in sharing and mutual aid of people living in poverty.
    **** (10:24-13:53) *Your 'No'*. Having power means you rarely hear no [or descent]. That increases the likelihood that we're going to create unsustainable agreements. Because if you can't say 'No', you can't say 'Yes'. We can only say 'Yes' [or agree] when we can say 'No' [or say what keeps us from saying 'Yes']. I believe that most broken agreements are broken because they have never been entered in the first place. Do your children, your students, your colleagues, people around you, ever have a true option to say 'No' to whatever agreement you proposed? [Without responding with power over tactics?] Deciding together. Power sharing [distributed power]. 
  ** 13:55-14:04 https://www.youtube.com/watch?v=mCyWaSPmRkA&feature=youtu.be&t=835
    *** *If I want to have collaboration, and I am in a position of power, I need to do something to make it happen.*
  ** 14:25-17:00 https://www.youtube.com/watch?v=mCyWaSPmRkA&feature=youtu.be&t=865
    *** Why do we even want to collaborate? What do we gain from collaboration?
      **** creativity - diversity of thinking based on different needs
      **** increasing sense of power among individuals in the grouphave the power to make changes
      **** exercising need consciousness
      **** increasing the sense, that an individual matters
  ** 17:09- https://www.youtube.com/watch?v=mCyWaSPmRkA&feature=youtu.be&t=1029
    *** Division of labor vs Collaboration: Dividing task among people [no sharing] vs Creating the task and figuring it out [sharing]
  ** 20:40-23:24 https://www.youtube.com/watch?v=mCyWaSPmRkA&feature=youtu.be&t=1240
    *** *If I am part of creating the strategy that we're going to carry out I am more likely to be committed to carrying it out. If [somebody else] decides what's gonna happen and I just have to carry it out, and I was not part of somehow coming up with the design, I'm less [intrinsically] motivated [because now the meaning of the activity is clearer]. ... There is more energy to a project if it's done collaboratively than when it's dictated from above.
    *** (21:58) *Disengagement [alienation] is the fundamental symptom of absence of shared purpose.*
  ** 24:37-24:57 https://www.youtube.com/watch?v=mCyWaSPmRkA&feature=youtu.be&t=1477
    *** *Work is supposed to be suffering: if it's not suffering it's not work; and pleasure is supposed to be useless. If it has use it cannot possibly be pleasurable.*
    
* link:https://www.youtube.com/watch?v=xbto_pUFD08[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 3 - From Compromise to Integrated Solution that Work for Everyone]
  ** 0:41-4:14 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=41
    *** Mary Parker Follett: researcher in management science; investigated the term *_win-win_*; coined the terms *_power over_* and *_power with_*; Three ways to resolve conflicts: Domination, Compromise and Integration; Compromise is quantitative but Integration is qualitative - Compromise operates in the world of scarecity, Integration opens the options to resolve a conflict and differences among people
  ** 4:15-5:08 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=255
    *** the need to matter; to know that I matter; *"How to give everyone honestly a sense that they matter"*, *"How do I honestly show people that they matter to me?"*
  ** 5:09-
    *** Every time we make a request, we ask two questions; first question gets asked out loud: it's the request - the request is an opportunity for someone to make the life of the other person more wonderful by mutualy fulfilling their needs; the other question gets asked silently, internaly, but carries much more emotional weight: *"Do I matter to you?"*, *"Do you care about me?"*, *Am I important to you?* which serves to fulfil *the need of importance, the need to matter*. If I say "No" to the first question, and the other person who asked the question doesn't have the consciousness about empathy and "no" being a poor expression of a yes, or dogging for the needs, then the other person takes the "no" as the answer to the latter question: "So I don't matter to you." I may think I got an adequate answer. But in the end the relationship suffers, because we are in a permanent defficit around the need to matter. But we may feel vunlerable wenn we talk about the need to matter, to be important, because of our gender roles, education and other outside influences. Our dignity depends on our need to matter.
  ** 7:56- https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=476
    *** *If I want to make decisions together that build on integration, I need to show you that you are important.* We can also not do what is requested of us, [and give the other person an opportunity to make our life wonderful,] and still give the other person a sense that they matter. For example by deferring the task, or doing something else for the other person instead.
  ** 10:57- https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=657
    *** A key to collaboration is co-owning the problem [shared ownership of the problem; holding the problem, the pain of the other; being present with the other person, showing empathy] it's one way to give me a sense that I matter.
  ** 11:20-11:54 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=680
  *** *The more trust an familiarity there is between us, the less explicit we need to be [about the need to matter].* [the importance of trust and how trust simplifies communication]. [NVC - Nonviolent Communication is a tool that is available that can be very effective] when our trust is broken and then it can mend it.
  ** 13:10-13:23
    *** *You make it easy to say "No" to you. That's one of the highest compliments to a boss.*
  ** 14:01-18:37 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=841
    *** ... *when you have a sense that you matter, your creativity, your willingnes to experiment, your willingness to stretch, your willingness to accept things that are not your preference increases.* ... wanting and willing: we all have preferences and the range of our preferences is almost invariably narrower than the range of our willingness. ... Let's say I have some favourite meal - my preference. But I have a wider range of other meals that contain similar ingredients that I am willing to eat - my willingness. *It's not possible to make everyone happy. It's not possible and it's not the goal. The goal is to come up a decision, a solution, that is acceptable to everyone within their range of willingness. That range increases when the people know that they matter. ... If I know what really matters to you, [what needs you want to fulfil, if you reveal the meening, the sense, the purpose, why it matters to you,] my heart opens and understanding increases. It's from both ends, both from "I care about you" and "I would like to care about me" that willingness increases. [that you value my needs equally as your own.* M.B. Rosenberg - Resolving Conflicts with Children]
  ** 18:39-19:56 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=1119
    *** *What would be a solution that would work for everyone? What would work for everyone?* We are unhabituated to think in that way because of centuries an millenia of competition and scarecity. We are not habituated to think what would work everyone, only for either-or thinking and the perpetual sense of protecting and giving up.
  ** 20:00-20:21 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=1200
    *** *Conditions of Integration:*
      **** *having a shared purpose*
      **** *clarity of what the problem is*
      **** *co-ownership of the problem*
      **** *co-ownership of the solution*
      **** *knowing that I matter*
      **** *knowing that you matter and what matters to you*
    *** *Result of integration: _a solution that works for everyone_*
  ** 24:01-24:51
    *** If somebody doesn't have the willingness to sit in a room and solve a problem they have a meaningful contribution in, you're in a entirely different position. Then it can be more effective to use strategies such as link:https://en.wikipedia.org/wiki/Nonviolent_resistance[*Nonviolent Resistance*]. The problem with nonviolent resistance is that it requires a whole lot more people because if you individually try to do nonviolent resistance against a corporation, it's almost impossible. You don't have enough power for that. ... We come to a limit of dialogue, not nonviolence. Violence creates only more violence [Ghandi].
  ** 25:10-
    *** people converge way more on practical issues than on ideological differences. And the more the problem affects them they have a stake in solving it, and when they have the authority to solve [*a practical problem*, not an ideological one], the more likely they are to converge, because they live with the result of their deliberation. These people don't need to have direct authority. It's enough that they have moral authority. A group has moral authority when they are different groups, positions, opinions involved in the negotiation.
  ** 31:34-31:57 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=1894
    *** *Extracting, from what people say, the underlying principles [or non-controversial essences] that describe what matters to them*, and bringing together all the different principles that all the different positions [or people] in the room have into *one list of principles [or non-controversial essences]*.
  ** 36:19-37:33 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=2179
    *** I'm looking for what I call *_the non-controversial essence_ [or _principle_]*. Essentialy I look for something that captures in *positive language* what's wanted, not in negative language of what's not wanted, but in positive language of what's wanted, capturing something that has the essential meaning that the person is talking about while being noncontroversial. [The list of needs can help, but it's too abstract, too general. We're looking for an essence that describes the meaning of the situation. The essence is *more concrete than a need* but *more general than a concrete situation* and *still refers to the discussed situation*.] The one word needs allow you to create basic connection, but not to create the parameters for proposal. Find the most specific way to reach non-controversy, *because the more of the specificity you are able to capture in the principle [in the non-controversial essence that everybody agrees to - an obvious main idea of the situation], the easier it is later to solve the problem [and create a proposal - or formulate a clear, present request].*
  ** 49:47-50:18 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=2987
    *** [By extracting the non-controversial essence or the principle, that everybody agrees to] out of everything, and getting to the essence of whats wanted, that makes sense [and is obvious to people] where it would be very strange for somebody to disagree because it makes perfect sense. And if you make it in positive language, concrete, practical, non-ideological, it's way more likely [to create a proposal and to formulate a clear, present request].
  ** 50:28-52:26 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=3028
    *** *Creating the proposal:* There is a process of methodically *putting together a list of all the principles that make up the space of the decision.* ... *That list needs to be owned by the entire group that is going to be making the decision.* That group can be just one person. You can do it internally, because there is an internal choir, an you can get from each part of within you all the different voices what is the non-controversial essence of each different voice within you and you have a whole long list and you will know: *"I need to make a decision that honors all these principles."* instead of being in a fight of internal voices. Once that list is in place, you can get the shared ownership. ... *all these principles capture within them everything that matters to everyone.* *If [the list contains] all these principles it will be a decision that is very likely to work for everyone. Based on all these principles people can then come up with proposals [that consider all the principles on the list]*.
  ** 52:35-54:11 https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=3155
    *** Once you have a proposal, ... how do you then get from proposal to decision. A lot of collaborative processes that exist out there in one form or another put pressure on people to agree. I instead advocate very counterintuitive thing [which] is to *invite descent*. Inviting descent is once again a way to show people that they matter. ... The question is *_Who disagrees?_*, but how to aks the question is an art and almost a science. I'm looking for a question that will give me as much discussion as is relevant to where we are.
  ** 54:35-57:33
    *** There is significant trust that you generate through creating a shared list of principles. But that trust can disappear in an instant. If we are early in the process *I sustain the trust, the creativity, the collaboration, by making it very easy to express descent.* Especially [for long term development] I want to have a lot of discussion so that all different points of view, all different needs, all different concerns will be integrated. *[Gradually increase the level of descent.]* So I will ask the question, inviting descent, in a very open way, which could look something like: +
    "We have the first version of the proposal. Now is the time to express any concern that you have. Small or large, it doesn't matter. Right now we are going to discuss all the remarks that are brought up [in order to adjust the proposal by these remarks in the next version]. *Does someone has any concerns [or remarks] about this proposal?*" +
    In the next version I will increase the level of descent, by asking a question: +
    *It looks like we considered all mentioned remarks. But we still want you to ask you if you still have some objections about this proposal. Do you have any significant doubts or concerns about this proposal that you believe would interfere with us working well? Please, express them. But otherwise, if it's something small, that time is over.* +
    In the next version I increase the level of descent again: +
    *Okay, everything is prepared. Is here somebody who would like to leave the community if we adopt this proposal?* +
    *By then you established so much trust, that if there is something like this, people will articulate it. Otherwise the people will recognize that we've done the best that we can to make it work for everyone.*
  ** 59:05- https://youtu.be/xbto_pUFD08?t=3545
    *** The art is intuitively knowing, how much descent to invite. ... and ... matching your language [matching the question] according to how much descent we want to invite.
  ** 59:54-
    *** Make visible the real life consequences [not punishments] of what happens if we agree with this decision.
    *** *Precondition for collaboration: willingness*
    *** Why would somebody not participate in the process? Because some people don't believe that that process will benefit me. The resources that it would take to participate appear me to me to be too much for the benefit that I believe I will gain from it. I need to individually connect with the people to see what's going on. *What it is that they're saying 'Yes' to?*, *What keeps them from trusting the activity?* and rather avoiding the question "Why don't they want to come?".
    *** An organisation never says 'no'. It's always a human being, an individual, that say's 'no'. [And 'no' is a poor expression of a 'yes'. What is it that the someone says 'yes' to?] *And if you can think about why person is saying 'no', you're already moving towards the possibility of collaborating.*
  ** 1:05:38- https://www.youtube.com/watch?v=xbto_pUFD08&feature=youtu.be&t=3938
    *** Global Governance Model that works for most powerful and the least powerful (reference to Daniel Markovits - The Meritocracy Trap: "... workers, middle class, but also superelite workers - unite.") If the model will work only for one of these groups, and those models will go nowhere, because we lack collectively the power to make them happen, and because ultimately if we do them, they will recreate the world that we have now even if we had the power. ... So creating something that works for both ends to me creates a robustness that could make it work, but mostly *there is a way that people who are committed to communities don't think about the individuals that are in the [institution] as something to consider. That is perhaps a reason why they're saying no. I don't see that we can get anywhere collaboratively, in a way that will create a different world, without taking into consideration the reality.* That unless you have global mass mobilization, that creates defection from the implicit support that the institutions and government have, you have to reckon with the power [over people].
    **** from both ends [reference to David Harvey: The 17 Contradictions of Capitalism: paraphrased: "... we need to work on both ends: income and exchange value of goods and services. Otherwise the income will grow, and the prices of goods and services will increase, or income will likely stagnate and the prices will go up regardless."]
  
* link:https://www.youtube.com/watch?v=lfkZJDxC-YY[Mutual Aid - Peter Kropotkin - Ch. 1 - Mutual Aid Among Animals] or link:[the same video in a playlist for the entire book]
  ** 21:28- https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=1288
  ** 26:24- https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=1584
  ** 31:40- https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=1900
  ** 54:40- https://www.youtube.com/watch?v=lfkZJDxC-YY&feature=youtu.be&list=PLAWpwCQqndn68ADSHK1vsFUQ93n3hLcv4&t=3280
  
* link:https://www.youtube.com/watch?v=qEVLkX0SSug[Economics, But Not as You Know It]
  ** 31:47- https://www.youtube.com/watch?v=qEVLkX0SSug&feature=youtu.be&t=1907 - The Singapore Problem
  ** 1:16:06- https://www.youtube.com/watch?v=qEVLkX0SSug&feature=youtu.be&t=4566 - The Singapore Problem cont.
  
* link:https://www.youtube.com/watch?v=n5j5EW933Kw[Economics: The User's Guide | Ha-Joon Chang | Talks at Google]
  ** 12:42- https://youtu.be/n5j5EW933Kw?t=762
  ** 22:18- https://www.youtube.com/watch?v=n5j5EW933Kw&feature=youtu.be&t=1338
  ** 30:20- https://www.youtube.com/watch?v=n5j5EW933Kw&feature=youtu.be&t=1820
  ** 46:46- https://www.youtube.com/watch?v=n5j5EW933Kw&feature=youtu.be&t=2806
  ** 54:10- https://www.youtube.com/watch?v=n5j5EW933Kw&feature=youtu.be&t=3250
  ** 54:15- https://www.youtube.com/watch?v=n5j5EW933Kw&feature=youtu.be&t=3255
  
* link:https://www.youtube.com/watch?v=CtZZj4j5UpI[LSE Events | The Meritocracy Trap]
  ** 5:28-5:37 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=328
  ** 7:48-8:20 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=468
  ** 8:55-10:51 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=535
  ** 10:51-11:49 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=651
  ** 12:10-12:45 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=730
  ** 15:36-16:05 https://youtu.be/CtZZj4j5UpI?t=936
  ** 19:41-25:29 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=1181
  ** 25:30-26:39 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=1530
  ** 26:40-27:06 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=1600
  ** 30:32-32:36 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=1832
  ** 33:41-34:37 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2021
  ** 34:37-38:46 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2077 - somatization
  ** 38:47-40:10 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2327 - alienation
  ** *40:10-42:32 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2410* - proletariat can't measure up to elites ("Not good enough"-belief)
  ** *42:33-45:54 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2553* - deserve
  ** 45:44-46:39 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2754 - deserve, debt
  ** 46:40-47:33 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2800
  ** 48:29-49:39 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2909 - health
  ** 49:40-54:16 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=2980
  ** 54:16-55:05 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=3256
  ** *55:05 (55:55)-(56:11) 59:12 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=3305* - deserve
  ** *59:13-1:03:32 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=3553*
    *** 59:50-59:51 - fenomena -> "van Avermaet" / "vanaanamat" pronunciation by Matt White
    **** beginning-0:50 - https://www.youtube.com/watch?v=Q7m781sW5WE&feature=youtu.be&t=0 +
    4:17-end - https://www.youtube.com/watch?v=Q7m781sW5WE&feature=youtu.be&t=257
  ** *1:03:33-1:05:53 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=3813*
  ** *1:05:55-1:07:41 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=3955*
    *** "The virtues that the meritocracts claim are themselves unstable normatively. *It's not that meritocracy undermines the equality of opportunity. Of course it does.* ... [The meritocrats] started the war. Not because they are vicious or venal, but because responding to incentives in a way in which people do, they started out a snowball mechanism of training concentration, fetish for skill, more training, more fetish for skill, which doesn't actually benefit the society as a whole and makes them extremely wealthy, and what they call *'merit'*, isn't actually a virtue at all, *it's just a way of justifying a fundamentally unjustified and offensive distribution of advantage.*"
  ** 1:07:42-1:12:44 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=4062
  ** 1:14:59-1:22:21 https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=4499
  ** 1:25:26- https://www.youtube.com/watch?v=CtZZj4j5UpI&feature=youtu.be&t=5126
  
* link:https://veganvanguardpodcast.com/20-mental-health-addiction-and-capitalist-realism-with-mad-blender/[20. Mental Health, Addiction, and Capitalist Realism with Mad Blender]
  ** 1:18:18-1:31:26
  *** 1:23:52-1:24:15
  ** 1:31:51-1:32:24

* link:https://bitchyshitshow.com/2020/03/31/008-covid-19-and-seizing-the-means-part-1-a-collaboration-with-mexie-of-the-vegan-vanguard/[008 COVID-19 AND SEIZING THE MEANS (PART 1): A COLLABORATION WITH MEXIE OF THE VEGAN VANGUARD]
  ** 1:12:00-1:14:00
  ** 1:16:14-1:20:54
  ** 1:24:53-1:26:26
  ** 1:26:40-1:31:10
  ** 1:32:34-1:44:39
  ** 1:44:45-1:51:40

* link:https://veganvanguardpodcast.com/48-covid-19-and-seizing-the-means-part-2-with-bitchy-shitshow/[48. COVID-19 and Seizing the Means (Part 2) with Bitchy Shitshow]
  ** 27:53- 30:20
  ** 36:00-36:51
  ** 51:45-52:21
  ** 53:50-55:00
  ** 57:15-59:20
  ** 1:00:47-1:03:41
  ** 1:09:21-1:10:48
  
* link:https://veganvanguardpodcast.com/how-competition-dominates-our-lives/[2. The Trope of “Competition” Dominates Our Lives]
  ** 16:30-16:51
  ** 16:40-20:37
  ** 21:43-21:53
  ** 23:23-24:37
  ** 24:57-27:05
  ** 28:14-28:26
  ** 29:20-33:00
  ** 33:30-35:47
  ** 38:25-40:10
  ** 40:20-45:04
  ** 51:51-52:31
  ** 57:55-1:11:52
  ** 1:14:40-1:18:42
  ** 1:19:18-1:20:46
  
* link:https://veganvanguardpodcast.com/42-sexual-violence-pedophilia-and-the-systems-that-perpetuate-them-with-kathrin/[42. Sexual Violence, Pedophilia, and the Systems that Perpetuate Them with Kathrin]
  ** 5:05-6:04
  ** 55:26-1:11:50
  
* link:https://veganvanguardpodcast.com/37-could-capitalism-exist-without-patriarchy/[37. Could Capitalism Exist Without Patriarchy?]
  ** 11:11-19:05
  ** 42:42-45:37
  
* link:https://veganvanguardpodcast.com/47-social-emotional-learning-sel-for-socialism-and-animal-liberation-with-pierce-delahunt/[47. Social Emotional Learning (SEL) for Socialism and Animal Liberation with Pierce Delahunt]
  ** 25:30-25:58
  ** 29:01-32:34
    *** Empathy from hell: emphatizing with another person's feelings and needs without being connected to own's
    *** 4 D's of disconnection [from life in ]:
      **** Denial - Amtssprache, denial of responsibility for my actions
      **** Diagnose - moralistic judgements, language of domination
      **** Demand - Amtssprache
      **** Deserve - making violence enjoyable
  ** 32:34-35:41
  ** 43:06-45:47
  
* *Punishment is the [deliberate] infliction of pain for purposes of revenge.* link:https://www.youtube.com/watch?v=YJ-EH9LrmUE&feature=youtu.be&t=99[James Gilligan, Revenge: 1:39-1:43]
  
* The problem with revenge is, that's endless. ... If all we do when people commit crimes, is punish them, we're simply participating in an an endless cycle of revenge, and counter revenge and counter counter revenge and so on. We learn nothing. The criminals only learn revenge is a good thing, and revenge is what the powerful do to the weak. link:https://www.youtube.com/watch?v=YJ-EH9LrmUE&feature=youtu.be&t=0[James Gilligan, Revenge: beginning-0:28], link:[James Gilligan, Revenge: 2:49-end]

* This is what I love about friends. Good friends agree with my jackal. Actually, that's the most dangerous thing on the planet. If somebody else  agrees with my jackal, now I can believe my jackal to be true. This is in the society how we create jackals. We call it *"sympathy party"*. It's very different than empathy. Sympathy party is to agree with someone else's jackal. ... In that moment it's the most delicious for her. "Oooh! Thank you! Finally somebody agrees that I'm right and he's wrong!". *It's a pleasure for a short term* because then you go back home, pumped up by this sympathy party, you come to the other person, and you say: "You see? There's really something wrong with you!". *And then you'll have a bigger fight.* link:https://youtu.be/KX_tgRM84RA?t=370[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 6:10-8:08)]

* Can you feel even for one second the beauty of both [needs, the beauty of all unfulfilled needs at both conflict parties]? I want [to fulfill all the needs]. And the key now is [to ask yourself] "And I don't know how [to meet both needs right now] ...". Because my brain has been programmed to think "Shit, what to do?! AAARGH! WHAT TO DO!?" I want to fulfil the needs of both sides. Can you breathe three seconds in not knowing? And just feel the beauty of all the unfulfilled needs in a conflict. ... Creativity comes then by itself. Creativity is effortless. You don't need to think "What to do?" *When you recognize what is important for both of you, [and find the unfulfilled needs], creativity will come to you [effortlessly].* When you connect to your need it's a natural process. link:https://www.youtube.com/watch?v=KX_tgRM84RA&feature=youtu.be&t=2279[Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 37:59-43:06]

* I'm not trying to solve conflict. I'm only connecting with the essence, with the needs. Needs will bring me creativity. It asks a certain muscle, that I call *"breathing in the not knowing"*. ... When I know what is important for me and what is important for the other, the essence of us, our needs [we want to fulfill], images will start to come to me. The skill is first to know what is really important. If I don't know her needs, when I hear "I want to swimm.", but I don't get what it is really about, then I think "We have to go to the see." And that is immediately a danger to my needs and I want to [show a middle finger]. If you try to solve [a conflict] before knowing what it is really about [that it's about that my needs and the other person's matter equally]. If the other person sees that I their needs matter, suddenly he/she becomes more flexible. There is a whole magic that nobody was teaching me was avaliable there. When a human being is fully heard, and has a sense that his needs are being taken seriously, immediately there is a new openness. I learned immediately to think "Shit, what to do?" Then any solution that will come will be like a band-aid on the leg. Try to practice connecting with the needs, not to solve the conflict. Just to connect with the needs and sit there. It feels horrible for jackal educated human beings. [Jackals think:] "Yes, but what to do?" link:https://www.youtube.com/watch?v=KX_tgRM84RA&feature=youtu.be&t=3252[Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 54:12-1:00:25]

* *Instead of believing somebody's words to be true, I believe their experience [behind the words] to be true.* ... So I put my focus on their feelings and needs.  ... On their experience behind the words. And the whole art is the art of guessing. [Focus on their humanity, on their observation, feelings and needs and requests.] link:https://www.youtube.com/watch?v=KX_tgRM84RA&feature=youtu.be&t=4515[(Nonviolent Communication (NVC): Yoram Mosenzon full workshop: 'Connecting in Conflict': 1:15:15-1:15:59)]

* As much as possible in as little time as possible vs The best of possible in whatever time necessary to do it. link:https://www.youtube.com/watch?v=bux3TJWvyqE&feature=youtu.be&t=98[(Manfred Max-Neef - The Benefits of a Slow Life: 1:38-1:51)]

* *_Book - James Gilligan - Violence: Our Deadly Epidemic and its Causes_*. +
Every act of violence somewhere is an attempt to create justice to right a wrong that happened before. That wrong may happen two seconds before or might have happened 50 years before. But there's somewhere in the person's deep organism some wrong that have happend that needs to be righted, and the violence is an expression of that. Now we can all understand the pull to justice *but why does it go to violence rather than to other means? Because we feel shame. All the people that he had talked with essentially without exception were carrying boatloads of shame* in them about who they are, about what has happened to them, about what they want, and most particulary, about anything that had to do with tenderness, with any need for love, for connection, for appreciation. They had so much shame about it. One of the things that are so clear coming out of this is that *punishment makes things worse because it increases shame link:https://cassandravoices.com/current-affairs/global/special-report-punitive-policies-inflict-further-exclusion-and-trauma-on-syrian-refugee-children/[[and intensifies trauma response and symptoms]]. If shame is at the root of violence, punishment is not going to work. It only going to make the person get into a deeper loop* about who they are now. "Not only I'm ashamed about everything else, now I'm ashamed about the things that I've done and I've been punished, I've been ostracized, there's no room for me." link:https://www.youtube.com/watch?v=msWYVhmuQhw&feature=youtu.be&t=604[(Albany Addresses Bullying: Miki Kashtan: A Compassionate Perspective on Bullying 3/5/2011: 10:04-12:43)]

* [Shame] is not only now more common, its purpose has shifted from protecting the group [i.e. the community] to protecting the powerful. So *most of us walk around with some degree of shame that is just there in the background that keeps us from doing things.* And *we get shamed for what we want. If you look at early childhood, you are made to be ashamed for wanting what you want, for moving spontaneously, for going for what is of direct interest to you, for saying what is true for you, everything that is about being you is put into question.* ... This is why I decided to become 100% shameless. Why is this funny? Because the word _shameless_ describes someone who is a terrible person, totally outside of the norm. It's as if we're told that having a certain amount of shame, constatly, is a good thing. link:https://www.youtube.com/watch?v=mErG7mSzwkc&feature=youtu.be&t=2029[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 33:49-34:40, 1:34:51-1:35:23]

* Authorities figures tend just by nature to use shame. link:https://www.youtube.com/watch?v=2KXwnbsQUrI&feature=youtu.be&t=123[(Restorative Justice Continuum - Howard Zehr Ph.D EM 2:03-2:12)]

* Shame is calling me to do self-reflection. And that is sometimes very painful to be willing to do my self-reflection, and to stop projecting my frustrated feelings onto other people. link:https://www.youtube.com/watch?v=0pleCht2jN4&feature=youtu.be&t=439[(NVC Guilt and Shame - Kirsten Kristensen: 7:19-7:40)]

* There's a moral transformation, transformation of basic political categories which what a revolution really is. But I think in order to go further with this we need to change our basic categories of what labor is. It's just as in the 19th century, the idea of labor theory of value as material production, was incredibly effective, although it turned out to have very real limits which allowed it to be reversed. We need to change our conceptions of labor to one that starts from caring labor. *What society is, is a process of the mutual creation of human beings. So not just the creation of material world, it's a creation of each other.* That's what we're doing. That's what we're doing right now here. Caring, education are the primary things. There is a free education movement right now in Amsterdam and London, there is a huge student movement emerging. I find this very exciting. One of the first things that they're putting in their plank is that *"We've been told that the purpose of education is to improve economy. We want it backwards. The purpose of the economy is to improve education. To give the people the freedom and leisure to understand the world. To learn things."* Our perspectives are totally backwards. *If you take education as part of that broader process of caring, mutual nurture and mutual support that creates the world by which we create each other.* I think that if we begin to look at the world that way, well of course that's the way the most people who ever lived get see the world. Most societies it's just assumed that material production is just one subordinate moment in a broader process by which we create each other - creating people. *Thus factory labor is a form of carying labor if the stuff you're producing in a factory is that people care about, is that people need. But it's sort of second order form. It's things that are useful in what's the really primary business of human life which is our taking care of each other. And I think that if we transform our categories, begin to rethink the world in that and make that common sense, then we'll truly have achieved a revolution.* link:https://www.youtube.com/watch?v=2QUdrdgPI-I&feature=youtu.be&t=1837[(David Graeber: All Economies are Ultimately Human Economies (2015): 30:37-33:23)]

* So, I suggested that instead of production and consumption we substitute care and freedom. Perhaps caregiving and care is really that work we do which maintains and increases other people's freedom of which the paradigm would be *play*. Because play is action done for itself. Because what is caregiving labor? You take care of kids so they can play. link:https://www.youtube.com/watch?v=kikzjTfos0s&feature=youtu.be&t=2958[On Bullsh*t Jobs | David Graeber | RSA Replay: 49:18-49:38, link to Peter's Gray - Play ???]

* Practice does not make perfect. Only perfect practice makes perfect. +
 Übung macht nicht perfekt. Perfekte Übung macht perfekt. +
 Tréning nerobí majstra. Majstrovský tréning robí majstra. +
 link:...[(Vince Lombardi - baseball player)]

* It's not practice that makes perfect... but perfect practice that makes perfect. +
  Es ist nicht Übung die perfekt macht..., sondern perfekte Übung, die perfekt macht. +
  Nie je to tréning, ktorý robí majstra..., ale perfektný tréning, ktorý robí majstra. +
  link:???[(Cal Ripken Sr.)], link:???[(Daniel Markovits - Meritocracy and its Discontents: 48:40-49:30)]
  
* Our greatest glory is not in never falling, but in rising every time we fall. +
Unsere größte Ehre liegt nicht darin, nie zu fallen, sondern darin, dass wir jedes Mal aufstehen, wenn wir fallen. +
Confucius

* https://www.ia.gov.sk/data/files/np_PKSD/Analyzy/Stat/Prekazky_v_praci_a_ochrana_prace_NP_PKSD.pdf -- kapitola 2.12 Sabbatical - Syndróm vyhorenia

* I've learned that people will forget what you said, people will forget what you did, but *people will remember how they felt with you.* +
  Ich habe gelernt, dass Leute vergessen, was du gesagt hast, Leute vergessen, was du gemacht hast, aber Leute werden sich daran erinnern, wie sie sich bei dir gefühlt haben. +
  link:???[Maya Angelou]

* How to speak giraffe with our inner jackals? And in fact, they are probably the most severe jackals we will ever have to deal with. First of all they are so much faster than these other jackals. These inner jackals, they speek with a speed of light, and they have been in there for so long, that often time we are not even aware, that we are jackaling ourselves. Therefore giraffes love to have certain feelings. Giraffes love to have feelings like depression and guilt. Why does the giraffe like those feelings? Because those feelings tell us, jackals infested our thinking. That we are jackaling ourselves. We're telling ourselves that there's something wrong with us. And whenever we're doing that, as a giraffe, we want to tame those inner jackals. How do we tame an internal jackal? The same way we tame an external jackal. No matter what message comes at you from another person, no matter how jackalish it sounds, it's simply an expression of feelings and unmet needs. So we put giraffe ears on and we hear the feelings and the unmet needs. We do the same thing with our internal jackals. Once we've had identified that we see what we're telling ourself, we want to translate that internal judgement into "What are the feelings and needs that are being expressed through this self judgement?" And then you know what we find? The same thing we find with external jackals. That there are no jackals. Jackals are simply giraffes with a language problem. Likewise these internal messages, that keep eating out our soul and morale, if you really hear the life energy being expressed behind that message, we find out that it's a very loving message. We don't feel bad about ourselves at all. ... Whey you have the word "fault" in your consciousness, you know, you have been beset with jackals. When we think in a jackal way, there always must be fault, blame. [But isn't this how the news are presented in media? Every day?] ... "I'm sad, I really would have liked to have known then what I'm learning today." Now you're in touch with life energy behind your message. You're really hearing what you feel and need. But notice how different it is from thinking that thinking "there is something wrong with you. That you should have known better." Notice that when we are in touch with our feelings and needs, that motivates us to do something about the needs. But when all it goes in our head is "should have" and "what's wrong with you" [or what would the others think about me], that doesn't help us learn from the situation. That doesn't mobilize us to change. [link:https://www.youtube.com/watch?v=RSwEC4yvrb0&feature=youtu.be&t=1209[All we can do is to hate ourselves.] We just keep beating ourselves up for years, until we tame those inner jackals which always means to get connected to the life energy behind it. link:https://www.youtube.com/watch?v=HLgGt7yLhJg&feature=youtu.be&t=6084[Atelier communication non violente - Marshall Rosenberg - Danemark - sous-titres français: 1:41:25-1:46:16]

* link:https://www.youtube.com/watch?v=8kaVztNodEM[Marshall Rosenberg Nonviolent Communication RESOLVING CCONFLICTS]
** 20:19-31:12 https://www.youtube.com/watch?v=8kaVztNodEM&feature=youtu.be&t=1219
  *** Jackals think of these two possibilities: I must have all the power to force other people to behave, or the other option they think of is permissivness, giving up power and just giving in, letting the children [or the other people] over. How do we express our value judgements in giraffe? *"I would like, if you're willing. But, please, don't do it unless you're willing 'cause we both lose."* How do we recognize that the other person heard a request and not a demand? How do we get across now that it is in fact "I would like, if you're willing". When the person now *trust* that we're not saying the old messages. First of all, they may be suspicious for a while. Then you get responses like "Yes, mein Führer!" They believe, this is just a jackal trying to sneak into a giraffe's clothing. Even though I'm now practicing another language. They don't know yet that I'm really graduated. [They might say:] "Don't pull any of that giraffe business on me!" There is still worry that it's still your objective to get what you want. And as long as that's your objective, you can't get it. *So, as a giraffe, it's never your objective to get what you want from other people. It's only your objective to get what both people want. It's only when the other person trusts that I value their needs equal to my own [that their needs are equally as important as mine, that their needs matter equally as mine], that I have any _power with_ that person.* This is the central difference between power over - jackal power, and power with - giraffe power. Power over, jackal power, is easy to get: all you got to do is to make the other person suffer if they don't do what you want. But giraffe power, power with, I only have that to the degree to which the other person *trusts* that I am equally interested in their need fulfillment as my own. When they trust that I know that I can't benefit at their expense [because benefitting at somebody else's expense is not a benefit at all, because it's not sustainable, and it crumbles sooner or later anyway], and I have no desire to. It's only when they trust, I believe firmly enough, for what I'm asking for, I don't have to use fear, guilt or shame inducing tactics [or any other power over tactics]. When they trust all of that, then they can hear that that's just my request. This might be new on my part, so they might not trust it yet. +
  Different ways that jackals express no: "Yea, yea, yea, later", "Yes, mein Führer", "Who was your slave in your prior incarnation", or (sigh). All of these reaction tell us that this person is burdened, they're having to protect the most precious that each of us has: our autonomy. That is so difficult when that's under pressure. We'll fight to the death if we will have any source of humaneness left in us. None of us want's to do things because we're forced to do it. That's what I mean by "loving the life in the 'no'", be happy that this person is not doing it. Because when people do it and they don't look inside to see they're doing it inspite of themselves, everybody pays. That's why in giraffe we really mean it: *"Please do this ONLY IF you are willing. We all suffer unless everybody is doing things simply because they want to, because they see how it contributes to life."* +
  I'm not saying what you should say. If I'd tell you what you should say, my guess is you'll have trouble accepting it. "I'm offering you something that I'd say..." ... I wouldn't say "Only do this if you want to" 'cause I'm still telling them what to do. I'm still thinking that I'm the person who's job it is to tell them, what to do. That wouldn't meet my need, just if they did, if they want to. The other thing about that is, as a giraffe, I know that people never do anything except what they want. So that's kind of superflous. I don't think anybody ever does anything except what they want. The only difference is, jackals lie about it. They say "I didn't wanna do it." Then why did you do it? "They made me do it." "I had to do it." "Superiors orders." "Company policy." [Amtssprache - a language that denies choice and responsibility.] There's no responsibility for actions in Jackalland. But a giraffe speaking person knows that in each moment each of us only does only what we want. In this sense, giraffes is not introducing anything new into the universe. *People as long as they've ever been around don't do anything except what they want.* +
  "What if we requested the other person to do something?" Well, even before the conversation starts, *if my objective is to get the other person to do what I want I've lost already.* *"What would the giraffe objective be?" To make a connection with that person. Giraffe dance. Giraffes like to dance. And there is a certain kind of dance that goes: Empathy, Honesty, Empathy, Honesty, ... And giraffes really like that dance 'cause they believe miracles can come off that dance. When we really connect with people in a certain way, any kind of conflict can be resolved* without fear, without guilt, without shame [or any other power over tactics]. *So we trust that dance.* If we go in wanting to dance, well, and we trust that we may come out with the person doing what we want, for reasons what we want. There is no force on it, they're doing it willingly 'cause they see the purpose [meaning, reason]. Or we come out of it valuing what the other person dit, or wants to do. Maybe, so *we don't know, that as a giraffe, we know that if we dance, we'll like whereever we end up. I'm trying to form a kind of connection with this person, that I think is conducive to working out whatever differences are there. I want to form a quality of connection, that's my primary objective*, quality of the connection, and then I trust, that if that quality is of a certain sort, where all of our energy doesn't go into defending each other, violating each other. *When we're really safe, and we really trust that each has the other person's well being at mind, then I know, that this is gonna get results.* I have no doubt about it. But I won't go in there, thinking that that's got to be, that they're gonna study.  ... *So I don't know how it's gonna come out, but but I know that if we get there in a certain process, we'll both like it [breathing in the not knowing]. It has to be clear about our values [needs, purposes, reasons]: "What quality of connection do I value making with people?" "Do I value people as an equals?" "If so, then does my behaviour demonstrate that when I'm with other people?"* That doesn't mean that I have equal knowledge, or equal strength, but do I really value treating people as equals. "And how do I do that, if this person is age 5, or 12?" *"Do I value the use of violence for people to get their way?" So it's for me just being consistent with my values and "How I would like people to treat me?" If that's really what I value, that quality of our connection, and trust that it is of a certain sort, then I trust wherever the conflict goes.*
** 59:03-1:01:06 https://www.youtube.com/watch?v=8kaVztNodEM&feature=youtu.be&t=3543
  *** Culturally and politically some people might not be used to this reflection [of feelings and needs] back. [The may consider it as an "invasion" into their private space]. [So, after the empathy,] they may say "Don't pull any of that psychology crap on me!" **So we [show empathy] it again. Silently. For this to be powerful doesn't mean we have to say it outloud.* It's at the very moment that I turn my atention what is this person feeling. So when he says "Don't pull any of that psychology crap on me!" I turn my attention to what is the other person feeling [and what of their needs are not being fulfilled] when he/she says that. I guess the other person is scared and annoyed [nervous, uncomfortable, unpleasant], 'cause he/she may not understand what this [my response] is all about, and the other person wanted me to respond in a way that he/she was more familiar with. That's what I hear in that message. I don't have to say it outloud. *I'd like to be able to say it outlout to check it out 'cause I might be wrong, but just the fact that I'm trying to find the person's feelings [and unfulfilled needs with possible request for me] is already a success. Because when I'm looking for another person's feelings, I take away all power that person has to limit my power, my personal sense of respect.* Only when I take in the judgement, it starts to get scary. *But when I'm conscious that all judgements are simply tragic expressions of needs, why be scared of judgements. They're just saying: "This person is in pain. This person needs something." ["This person has needs that are not being met." "Please! Please!! PLEASE!!"]. This is a good example where the truth sets us free. The truth is, this person has feelings and needs. So why get caught up in their images?*
** 1:05:01-1:06:09 https://www.youtube.com/watch?v=8kaVztNodEM&feature=youtu.be&t=3901
  *** *Better to have [the Nonviolent Communication] in your heart and be broken for the words. "Whenever I really get connected to that energy, even when I speak jackal it's giraffe." So the words aren't as important as the consciousness of why I'm interrested in giraffe. The quality of the connection. If that's really what you're after, the words come with practice. But it's that spiritual quality at the beginning. Without that [spiritual quality] the rest doesn't help.*

* Out beyond the ideas of right and wrong there is a field. I'll meet you there. / We'll meet us there. +
Jenseits den Ideen von richtig und falsch gibt es einen Platz. Ich treffe dich da. / Wir treffen uns da. +
Za hranicou dobrého a zlého je miesto. Tam ťa stretnem. / Tam sa stretneme. +
link:???[Rumi - poet]

* If you need to do something, you can do it badly. +
  Wenn du etwas tun brauchst, kannst du das schlecht tun. +
  Keď niečo potrebuješ urobiť, môžeš to urobiť zle. +
  link:???[Gilbert Keith Chesteron]

* Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away. +
  Perfektion wird nicht erreicht, wenn es nicht mehr dazuzugeben gibt, sondern wenn es nicht mehr etwas wegzunehmen gibt.
  link:???[Antoine de Saint-Exupéry]
  
* The world is shaped by people who believe and trust the future and their past experiences, abilities and intuition. The more you can trust the future, the more you can engage in the present moment. And vice versa. [I'm wondering, how the parenting and education plays a role in this] link:???[Cedric Dumont - From Fear to Flow: 13:19-???]

* Educated risk-takers enjoy to study things on their own. We know the consequences. We know there is something at stake. Everything is prepared. Preparation plays a vital role. link:???[Cedric Dumont - From Fear to Flow: ???-???]

* If the risk is bigger that the satisfaction, don't do it. +
  If the satisfaction is bigger than the risk, do it. +
  link:???[Cedric Dumont - From Fear to Flow: ???-???]

* *Emotions -> Actions -> Habits -> Life -> Destiny* +
The more more positive the emotions are, the more chances that the rest will follow. Fear is a necessity in a high rist environment. It reinds you that you're onto something important with high consequences. +
link:???[Cedric Dumont - From Fear to Flow: ???-???]

* Staying in touch with your own mortality helps you to make decisions that are meaningful to you. link:???[Cedric Dumont - From Fear to Flow: ???-???]

* When you're tense, you can't feel it. And when you can't feel it, you can't recreate it. [Relaxed attitude helps me to experience my dream feelings again.] link:???[Doug Newburg - RPM Researchgate link ???]

* ... to make business more spiritual we must make business more humane. link:https://sci-hub.tw/10.1023/b:busi.0000005730.37745.07[Searching for Spirituality in All the Wrong Places - Journal of Business Ethics - Conclusion]

* The structures focus more on self-regulation than on expressing the student's feelings, needs and ideas. link:???[Alfie Kohn - OFJCC: ???-???]

* *Tests* measure what matters least. If the teacher needs to give a est, the teacher needs help in how to teach and assess. No matter whether they're standardized or not. Tests create more anxiety and achievement pressure. link:???[(Alfie Kohn - OFJCC: ~1:23:00???)], link:https://en.wikipedia.org/wiki/Meritocracy#Critique[Meritocracy: Critique - Wiki]

* [Compulsory] *Homework* [at and below the highschool level] is unnecessary. Research shows no benefit of homework before high school. And even there it's questionable. So why do we persist? BGUTI! - "Better get used to it!". "People will do to you mean and unpleasant things in the future, start doing them now!" +
Homework is literally all pain and no gain. It produces frustration, exhaustion, family conflicts and nagging, less time for kids to do what they care about when they get home, and loss of interest in learning. Homework effectively extinguishes curiosity [when the kid doesn't do it and the teacher or parent punishes the kid physically or psychologically with shame, guilt, the concept of duty, obligation or deserve]. There is no sacrifice in not giving homework academically. +
"As I got better in teaching, I assigned less and less homework. Now I assign none." *Getting rid of homework was intellectually beneficial.* "Students talked during the lesson about things they learned at the subject and compared them with current events in the world." Homework [can be considered as] a tool for the school how to manage family time. *The family needs to have the freedom to decide how to spend its time!* Instead of making the students work a second shift of academeics at home. +
Six hour of academics is more than enough.

* Talk to your kids at home about *what* they're learning in school. Never about *how well* the teacher thinks they're learning!

* If you need to give grades [or evaluate / judge]:
    . write acomment or talk with the student *without* the grades and points. The students will be more interested in learning *only* when there is no letter or number attached to the comment.
    . let the student decide the final amount of points and the final grade or letter. *The good you've done by removing grades from the occasion [and consciousness] and the trust you've shown to the students _far_ outweights the situations in which some students use the system for their advantage.* +
    They will see that obedience contributes to vilence in the same way that grades or tests do.
    
* Self-discipline is [perceived as] more important than empathy [which has devastating effects on the individual]. [Alfie Kohn - OFJCC]
    
* People of all ages are more likely to perservere when they have a chance to make the decisions about the things that affect them. Therefore, if someone doesn't persist, he or shewas to some extent excluded from decision-making, rather than he or she didn't have enough self-discipline. [Alfie Kohn ???]

* Miki - I have some say ... . link:???[Miki - Liberation 2: ???]

* Kohn - Kids have some say ... . link:???[Alfie Kohn - Youngest Citizens]

* link:https://www.youtube.com/watch?v=h4fQEn15NgI[The Gun Has No Trigger: David Graeber]
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=507[[8:27]-8:46] ... but if we would incorporate ourselves then we have to have a whole hierarchical structure, president, vicepresident, *and those rules and regulations are enforced ultimately by violence* ...
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=575[[9:35]-9:47] ... It's because the moment you have large, heavy objects [cars, buildings], they fall under government regulation [endless laws] in various ways, and that regulation is ultimately enforced by violence and that violence is a sort of a thing that we often oversee ...
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=575[[12:09]-13:41] Violence becomes incorporated into our world in ways we don't recognize it. ... Even the structural vivolence: there are forms of inequality and oppression which are ultimately displacement of violence. So racism, is a form os structural violence, sexism, patriarchy. *These are forms of inequality that have violent effects.* ... *It's actually the violence that holds the entire thing together* and away there are displacements of violence. ... They are ultimately based on larger structures where violence is systematically deployed. ... but these structures work best when the violence isn't actually deployed.
** link:https://www.youtube.com/watch?v=h4fQEn15NgI&feature=youtu.be&t=903[[15:03]-16:05] ... because all forms of action are symbolic and communicative. *What interesting about violence is that it's the only form of action that has any real chance of having a systematic and predictable effect on others without the medium of symbolic communication of any kind.* ... like the're doing something, you shoot them and they stop. ... *But the effects of violence are fairly predictable ... and that very fact gives the violence a quality which almost all other forms of action lack which is that you can relatively predictable effects on the actions of other people about whom you understand nothing.* Any other way you want to affect some other person's actions you have to have some idea what they think is going on, who they think they are, who they think you are, what they want, what they fear. If you shoot them or hit them hard enough is kind of becomes irrelevant. *This is why violence is the preferred weapon of the stupid.*

* *Pareto efficiency* or *Pareto optimality* is a situation where no individual or preference criterion can be better off without making at least one individual or preference criterion worse off. link:https://en.wikipedia.org/wiki/Pareto_efficiency[(Pareto Efficiency - Wiki)], link:https://www.youtube.com/watch?v=n5j5EW933Kw[(Economics: The User's Guide | Ha-Joon Chang | Talks at Google: ???-???)]

* BNP (Brutto Nationalprodukt - GDP/HDP) beinhaltet auch den Verkauf von Güte und Dienstleistungen, wie z. B. Waffen, Tabak, Alkohol, Prostitution, Drogen, organisierte Kriminalität, hazardne??? Spiele und Wetten +
BNP ignoriert externe einflüsse der Produktion und Dienstleistungen, wie z. B. Umweltverschmutzung, Zufriedenheit der Menschen (Einwohner, Angestellten, Studenten, Schüller), Nachhaltigkeit Haushaltspflege und Betreuung zu Hause. +
HDP (hruby domaci produkt) zahrna (priamo ci nepriamo) aj predaj tovarov a sluzieb, ako su napr. zbrane, tabak, alkohol, prositucia, drogy, organizovana kriminalita, hazardne hry a tipovanie. HDP ignoruje externe vplyvy vyroby a sluzieb, ako su napr. znecistenie zivotneho prostredia, spokojnost ludi (obyvatelov, zamestnancov, studentov, ziakov), pracu v domacnosti. +
link:https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/[(What are the 10 most harmful jobs?)], +
link:https://veganvanguardpodcast.com/48-covid-19-and-seizing-the-means-part-2-with-bitchy-shitshow/[(Mexie - veganvanguard - 48. - Covid-19 and Seizing the Means (Part 2) with Bitchy Shitshow: ??? 1:00:00)]

* The nakedness of standing without a frame, in a new paradigm, carries the pleasures of freedom but it also can evoke fears of looking foolish and exposed, feelings of shame that can readily erupt into rage and attack. This is the moment when we are most tempted to return to the familiar, to restore an old framework at all costs—this moment of paradigm shift, of epiphany or sudden radical insight, the creative moment in the lives of artists and scientists, the moment when our ordinary vision is removed and we come to see that the old ways of seeing were mistaken, were blinding us to what we now can see. link:https://www.uky.edu/~eushe2/quotations/gilligan.html[(Carol Gilligan, The Birth of Pleasure - Introduction)]

* Observing without evaluating is the highest form of human intelligence. +
Beobachten ohne zu bewerten ist die höchste Form der menschlichen Intelligenz. +
Pozorovanie bez posudzovania je najvyššou formou ľudskej inteligencie. +
link:???[Jiddu Krishnamurti]

* Ich kämpfe nicht. Ich *übersetze* alles in gewaltfreie Kommunikation. In die Sprache des Lebens. In die Sprache der Beobachtungen, Gefühle, Bedürfnisse und Bitten. I do it for me. I want to suffer less! For me! link:???[(M.B. Rosenberg)], link:https://www.youtube.com/watch?v=NR9JyTqaIto&feature=youtu.be&t=3465[NVC Israeli and Palestinian panel at Ecome Center February 2015 (Nonviolent Communication): 57:45-1:03:13]

* Let's find another way of meeting your needs that will be more effective and less costly. [M.B. Rosenberg]

* Everything everybody does at every moment, does it to fullfil his or her needs. [M.B. Rosenberg]

* Ich mache nichts falsch. Ich mache keine Fehler. Giraffen machen keine Fehler. Giraffen machen nur Sachen, die ihre Bedürfnisse erfüllen. Wir machen keine Fehler. Wir machen nur Sachen, die wir nicht gemacht hätten, wenn wir damals gewusst hätten, was wir seitdem gelernt haben. Das bedeutet nicht, dass wir perfekt sind. Das Ziel des Lebens ist nicht perfekt zu sein. Das Ziel des Lebens ist, fortschreitend weniger dumm zu sein. Das Ziel des Lebens ist zu feiern, wenn unsere Bedürfnisse erfüllt werden, und trauern, wenn nicht. link:youtube???[M.B. Rosenberg - Creating a Life Serving System Within Oneself], link:youtube???[M. B. Rosenberg - Wie sprichst du mit dir selber wenn du fehler machst?]

* Empathy vs Forgiveness; If we try to forgive before we've got enough empathy, the forgiveness creates even more pain. Verzeihung bedeutet, dass ich etwas falsch gemacht habe. Niemand macht etwas schlecht oder falsch. Wir alle handeln in jedem Augenblick, um unsere Bedürfnisse zu erfüllen. link:???[M.B. Rosenberg - Creating Life Serving System Withing Oneself: ???]

* Being alive means to be connected to your feelings and needs. Whenever you feel angry, guilty, ashamed or depressed *take your time* to bring yourself to life [to reconnect with your feelings and needs]. link:...[M.B. Rosenberg Workshop Making Life Wonderful 1/4 55:12-???, M.B. Rosenberg - Take your time]

* I found that 4 year olds learn this [NVC] process much faster than adults. And on much deeper level. ... [Nonviolent communication] is faster [to learn] when people have the purpose of it in mind. ... *The purpose is not to get people to do what you want, but to create the quality of connection that everybody's needs get met [compassionately].* That is a radicaly different story that most of us have been taught. *We have been taught, there is a right and a wrong way to do everything. The authorities know what's right. If you want to make it in this world, you have to do what the authorities say is right.* link:https://www.youtube.com/watch?v=NqJ-0EIsy9U[(Marshall Rosenberg - NVC Workshop 2004 Portland, OR: 1:59:39-2:00:38)]

* link:...[(M. B. Rosenberg - Nonviolent Communication Audiobook ~4:43:00-???)]

* Request vs Demand [(M. B. Rosenberg San Francisco Workshop 1:16:19-1:19:46)]

* How a person responds when it's burdened by a request link:...[(M. B. Rosenberg San Francisco Workshop 1:26:17-1:29:52)]

* Only things that people are saying: Please and Thank you link:...[(M. B. Rosenberg San Francisco Workshop ~1:30:00-???)]

* Criticism = Pain + Unmet Need link:...[(M. B. Rosenberg San Francisco Workshop ~1:34:00-1:42:29, M .B. Rosenberg Resolvng Conflicts with Children ???-???)]

* Hear the yes behind the no. "No" is a "yes" to other needs. Hear the feelings and needs behind the "no". "No" is a tragic expression of a "yes". Say the need! link:...[(M.B. Rosenberg - San Francisco Workshop ???-???)]

* Enjoy my pain. Don't try to comfort me, don't try to fix me, don't try to encourage me. Don't try to give me advice. Don't try to tell me that it's my fault. Caressing the Jackal [NVC Rosenberg, Mosenzon]

* please! please!! please!!! link:youtube KdFc2B-tZLc[Marshall Rosenberg - Making Life Wonderful 2_4 - Nonviolent Communication NVC: cca 1:13:00-1:25:00]

* Eye for an eye and the world goes blind link:...[ghandi], link:...[detroit become human]

* We have been trained to be quite habitual in things that are quite unnatural. link:???[ghandi]

* the importance of present request link:...[Marshall Rosenberg Making Life Wonderful cca 1:31:36-1:33:35]

* ... because *all human beings have the same needs.* link:...[(Film 02 SELF EMPATHY Session 1 - M. B. Rosenberg)]

* Take your time to come from an energy you choose to come from, not from an energy you've been programmed to come from.

* Quotes link:https://www.youtube.com/watch?v=RDkh1al3P9k&feature=youtu.be&t=2487[Speaking Peace - M.B.Rosenberg]

* ??? link:...[(M. B. Rosenberg San Francisco Workshop ~2:26:00-???)]

* No human being is good [no human being is bad - judging is too easy], but all are sacred. link:https://www.youtube.com/watch?v=LdOFhyKACxE[Dr. James Gilligan - On How All Human Beings Are Sacred], link:restoration_justice_part[Rosenberg - Creating a Life Serving System within Oneself]

* link:https://www.youtube.com/watch?v=_rSYiy420B0[Dr. James Gilligan - Youth and violence The role of education inspiring solutions]
  ** 1:02:17-1:09:18 https://www.youtube.com/watch?v=_rSYiy420B0&feature=youtu.be&t=3737
  ** 1:10:25-1:11:03 https://www.youtube.com/watch?v=_rSYiy420B0&feature=youtu.be&t=4225
  ** 1:12:07-1:14:23 https://www.youtube.com/watch?v=_rSYiy420B0&feature=youtu.be&t=4327
  ** 1:14:24-1:21:12 https://www.youtube.com/watch?v=_rSYiy420B0&feature=youtu.be&t=4464
  ** 1:21:13-1:33:33

* https://www.youtube.com/watch?v=bH9t1lAX2UQ Training Session # 2 Marshall Rosenberg CNVC org - 49:20-49:42

* https://www.youtube.com/watch?v=bH9t1lAX2UQ Training Session # 2 Marshall Rosenberg CNVC org - 58:10-1:07:16

* Never give them the power to submit or rebel link:...[(Training Session # 2 Marshall Rosenberg CNVC org - 58:10-???, M.B. Rosenberg - resolving conflicts with children, NVC San Fran workshop)]

* The behavior of somebody else is never the cause of our feelings. The behavior of somebody else is only the *stimulus* for our feelings. The cause of our feelings is our *thoughts* stimulated by the behavior and our *unmet needs* behind our thoughts. ... If we're trying to convince ourselves or somebody else that their behavior is the cause for our feelings, then we're are trying to use *guilt* and *shame* to change the behavior of the other person. Guilt means that the other person is responsible for our feelings. This is not possible because we cannot be responsible for something else outside of ourselves. We are only responsible for our intentions, thoughts, words and actions. The other person is not responsible for my feelings, but it's responsible for his or her intentions, thoughts, words and actions. I'm responsible for how I respond to the response of the other person, and for what ear do I have on, giraffe or jackal, when I'm reacting to their response. Shame on the other hand means that the other person is _bad_ for what they're doing and _deserving_ punishment. By Dr. James Gilligan, shame and ebarassement without nonviolent stimulation is the most reliable predictor of future violence and recidivism. Shame increases violence. Punishment increases shame. Therefore, punishment causes higher rates of violence and recidivism. link:...[(M.B. Rosenberg, James Gilligan, Miki Kashtan)]

* Sometimes I do things that i wouldn't have done if I knew then what I've since learned. +
Manchmal tue ich Dinge, die ich nicht getan hätte, wenn ich damals gewusst hätte, was ich seitdem gelernt habe. +
Niekedy robím veci, ktoré by som nebol urobil, keby som vtedy vedel, čo som sa odvtedy naučil. +
link:???[(M.B. Rosenberg - Fehler)], link:???[(M.B. Rosenberg one of the vimeo videos / corona series)]

* *Rückmeldung bei unerfüllten Bedürfnissen: Kritik / Bitte:* +
  *Beobachtung* [ein Satz] -> *Gefühle* [ein Satz] -> *Bedürfnisse* [nächster Satz] -> *Bitte* [der letzte Satz] +
  oder +
  *Gefühl* -> *Bitte* +
  oder, wenn ich unter Zeitdruck bin: +
  *Bitte* -> *Bedürfnisse* -> *Gefühle* -> *Beobachtung*

* *Rückmeldung bei erfüllten Bedürfnissen: Dankbarkeit:* +
  *Beobachtung* -> *Gefühle* -> *Bedürfnisse*

* *Stimulus / Anreiz* +
  Beobachtung / observation +
  Erlebnis / experience +
  Erinnerung / memory +
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Grund, Ursache / reason, cause* +
  Gedanke (kann auch blitzschnell sein) / though (can also be very quick) +
  Thoughts that are *disconnected from needs (i.e. life)* and *violence provocative* + [M.B. Rosenberg - Film 02 SELF EMPATHY Session 1: 1:43:00]
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Gefühl / feeling* +
  Wahrnehmungen im Körper / sensations in the body +
  ↓ +
  *Reaktion (innere Stimme, innerer Lehrer / inner voice, inner educator): +
  Wurzel / root* +
  erfüllte/unerfüllte Bedürfnisse (wenn wir mit den Bedürfnissen verbunden sind) +
  Urteil, Analyse, Diagnose, Interpretation (wenn wir von den Bedürfnissen getrennt sind und mit einfühlungsblockierender Kommunikation verbunden sind)
  
Nothing anybody does can't make us angry. It's only a stimulus. It's our unmet needs that have such enormous power to make changes in our bodies, like muscle tension, release of hormones, enemy images.
  
link:https://www.youtube.com/watch?v=jArsTeP66FE&feature=youtu.be&t=5863[Film 02 SELF EMPATHY Session 1: 1:37:43 (1:39:14)-]

* The map is not the territory. The words are never what they express. Look behind the words. See the truth. The truth is the other person has feelings and needs that are not being met. [Alexander Korzhybsky - General semantics], link:???[M.B. Rosenberg: Experiencing Needs as a Gift], link:[San Francisco Workshop]

* selfish, selfless, self-full [M.B. Rosenberg - Experiencing Needs as a Gift]

* Prefigurative environment link:youtube???[Making Life Wonderful 2/3/4 ??? - M.B. Rosenberg]

* There are no jackals. That all jackals are just illiterate girrafes, giraffes with a language problem. 

* "Clinical" [or "saint", "scientific", "academic"] ... it's called *word magic*. You add that word, boom, nobody can touch you. link:https://www.youtube.com/watch?v=tY78qJNLoQ0&feature=youtu.be&t=1242[(Thomas Szasz - The Myth of Mental Illness: 20:42-21:04)]
  
== Fundamental Attribution Error

The environment matters. The nurturing and education matters. It's not everything in the individual, as neoliberalism tries to convince us of. The enviromental factors and wealth have a decisive impact on the success of the individual.

Who's Cheating Whom - Alfie Kohn

Daniel Markovits - The Meritocracy Trap link:[(https://www.youtube.com/watch?v=CtZZj4j5UpI)]

link:https://en.wikipedia.org/wiki/Meritocracy#Critique[*Meritocracy*]

* The reliability of the authority and system that assesses each individual's merit is another point of concern. As a meritocratic system relies on a standard of merit to measure and compare people against, the system by which this is done has to be reliable to ensure that their assessed merit accurately reflects their potential capabilities. Standardized testing, which reflects the meritocratic sorting process, has come under criticism for being rigid and unable to accurately assess many valuable qualities and potentials of students. Education theorist Bill Ayers, commenting on the limitations of standardized testing, writes that "Standardized tests can't measure initiative, creativity, imagination, conceptual thinking, curiosity, effort, irony, judgment, commitment, nuance, good will, ethical reflection, or a host of other valuable dispositions and attributes. What they can measure and count are isolated skills, specific facts and function, content knowledge, the least interesting and least significant aspects of learning."[54] Merit determined through the opinionated evaluations of teachers, while being able to assess the valuable qualities that cannot be assessed by standardized testing, are unreliable as the opinions, insights, biases, and standards of the teachers vary greatly. If the system of evaluation is corrupt, non-transparent, opinionated or misguided, decisions regarding who has the highest merit can be highly fallible.

link:https://en.wikipedia.org/wiki/Peter_principle[*Peter Principle*]

* In a hierarchy every employee tends to rise to his level of incompetence.
* In time, every post tends to be occupied by an employee who is incompetent to carry out its duties.

and so on???

== Sozialismus, Kommunismus, Schenkökonomie

- Homo economicus - narrowly self-interested person with the goal to maxmimize his/her own utility without consideration on other people alway acting rationaly and reasonably. [great, just awesome economic model of human. [sarcasm] But to not consider other people's needs is not rational. It leads to violence, y'now? Take a look at James Gilligan's work about shame, pride, violence and his work in prisons in Michigan.]

- Marx - he didn't solve all the systemic problems, but I think he solved a lot of them. Finally I've found some relief when I started to read, watch and listen to marxists. I started to make connections and sense why am I suffering under current economic system - the capitalism. It all gradually became clearer to me why am I experiencing so much suffering in this world.

link:https://www.profolus.com/topics/four-types-of-alienation-according-to-karl-marx/[THE FOUR TYPES OF ALIENATION] + link:https://en.wikipedia.org/wiki/Marx%27s_theory_of_alienation#Types_of_alienation[(wiki)]

. *Alienation of the worker from their product:* The design and development of a production rest not in the hands of a worker but within the decisions of the capitalists. A worker does not have control over what he or she intends to produce or the specifications of his or her product.
** unfulfilled needs: autonomy, importance of the workers needs, freedom, direct democracy, incluson, integration, power with, choice, spontaneity

. *Alienation of the worker from the act of production:* The production of goods and services within a capitalist society is repetitive and mechanical that offers little to no psychological satisfaction to the worker. Labor seems coerced because a worker undertakes this as a means of survival.
** unfulfilled needs: sense, freedom, creativity, safety, willingness, voluntariness, importance of the workers needs, power with, enjoyment, fulfilment

. *Alienation of the worker from their species-essence:* The species-essence or “Gattungswesen” of an individual comprises all of his or her innate potentials. Under a capitalist mode of production, an individual losses identity and the opportunity for self-development as he or she is forced to sell his or her labor-power as a market commodity.
** unfulfilled needs: creativity, connection with the worker's feelings and needs - with the life inside, sense, meaning, enjoyment, growth, development, identity, choice, strength, fulfilment, *empathy*

. *Alienation of the worker from other workers:* The reduction of labor to a mere market commodity creates the so-called labor market in which a worker competes against another worker. Labor is traded in a competitive labor market instead of considering it as a constructive socioeconomic activity characterized by collective common effort.
** unfulfilled needs: community

== Warum will ich programmieren?

* Lebo potrebujem prostredie, v ktorom sa budem cítiť v bezpečí.
* Lebo potrebujem prostredie, v ktorom môžem rásť a vzdelávať sa.
* Lebo potrebujem tvorivé prostredie.
* Lebo je to práca, pri ktorej môžem tvoriť.
* Lebo programovania som sa bál.
* Lebo sa bojím programovania.
* Lebo pri programovaní sa cítim ponorený.
* Lebo sa chcem naučiť improvizovať.
* Lebo si chcem zlepšiť hypotetické myslenie.
* Lebo chcem rozvíjať svoju fantáziu.
* Lebo sa chcem naučiť samostatne programovať.
* Lebo chcem pracovať cez deň.
* Lebo chcem žiť svoj sen.
* Lebo chcem mať okolo seba ľudí, od ktorých sa môžem niečo naučiť.
* Lebo chcem mať prácu, ktorá mi umožní učiť sa stále niečo nové.
* Lebo chcem mať prácu, ktorá mi dáva zmysel.
* Lebo chcem každý deň dávať zo seba to najlepšie.
* Lebo chcem mať prácu, ktorá pomáha ostatným.
* Lebo sa chcem naučiť spolupracovať.
* Lebo chcem byť samostatný.
* Lebo chcem mať moc.
* Lebo chcem mať moc tvoriť veci.
* Lebo chcem mať moc samostatne tvoriť veci.

== Programming

- Rober C. Martin - Clean Code

???

== Pilates, Yoga, Wim Hof Method

Active Clinic

???

== Food

* Slow sugars
** Millet/Hirse
** Spelt/Dinkel
** Buckwheat/Buchweizen

* Quick sugars (but be careful with burnout, quick sugars and health: link:https://goodmenproject.com/featured-content/recover-extreme-burnout-jgc/[Burnout Recovery - Jordan Gray - 10. Avoid processed sugar, caffeine, and any other stimulants or drugs])
** Honey
** Jams (prefferably home made)

* Calcium
** Poppy seeds
** Sesame seeds

* Mineral waters with Calcium
** Gemerka
** Baldovská
** Kláštorná

* Oils
** Rapeseed oil + mineral water with calcium
** Sunflower oil + mineral water with calcium
** Poppy seeds
** Sesame seeds

* Probiotics
** 5 stems, 50-60B: Custom Probiotic CP-1 Adult Formula
** 11 stems, 11B: Advance Probio24
** *Saccharomyces boulardii:* ExHelico / Yomogi (lactose) / Enterol (lactose)
** Probio-fix inum / Probio-fix (lactose) / Probio-fix ATB assist
** link:https://www.adc.sk/databazy/produkty/pil/uro-vaxom-243674.html[URO-VAXOM] (link:https://www.adc.sk/databazy/humanne-lieky/ucinna-latka/lyzat-escherichia-coli-6364.html[an alternative to Mutaflor]; only with prescription) / Hylak Forte

* Food supplements

** Dietary fiber
*** link:https://www.lekaren-bella.sk/zbozi/3634053/#letak[Prebiolax] / Vemica Psyllium PROBIO PLUS / Vemica Inulín PROBIO PLUS
** link:https://www.adc.sk/clanky/spravna-dispenzacia-digestiva-145.html[Digestion enzymes]
*** Pankreolan forte / Pangrol 20 000 (lactose)

** link:https://www.adc.sk/clanky/spravna-dispenzacia-systemova-enzymova-terapia-63.html[Enzymes]
*** ProfiZYM Plus / link:shorturl.at/kqvwD[H-Protect Enzyme] / EnzyMAX V

** Blood donation
*** link:https://www.adc.sk/databazy/produkty/detail/salus-floradix-zelezo-754866.html[SALUS Floradix Železo]

== Hygiene

* Body
** link:https://www.rosemont.sk/mydla/az-na-kozu-mydlo-musk-2366.html?search_query=az+na+kozu&results=40[MuSK]
** link:https://www.rosemont.sk/mydla/olivove-jemne-mydlo-ponio-1261.html[Ponio] / link:https://www.rosemont.sk/mydla/bambucke-jemne-mydlo-ponio-1257.html[Ponio]

* Teeth
** Curaprox 5460
** ApaCare Remineralisierende Zahncreme / link:https://zubne-pasty.heureka.sk/[dalsie zubne pasty]
** Compostable dental floss - bambus
** Interdental brushes: 0.4mm, 0.7mm
** Tongue scraper
** GC MI Paste Plus (with fluoride) / VOCO Remin Pro / ApaCare Repair / GC Tooth Mousse (without fluoride)

== Psyché

Epigenetics, Chronic Stress (helplessness and tension), *Trauma*, PTSD - Post Traumatic Stress Disorder: the lack of empathy after tauma, trauma response, trauma and ibs, difficulty trusting people, loss of friends, fragile friendships

expressive writing, empathy, NVC

* https://www.psychologytoday.com/us/blog/think-act-be/201609/21-common-reactions-trauma
* https://safety.gwu.edu/common-reactions-trauma
* https://safety.gwu.edu/sites/g/files/zaxdzs2386/f/downloads/Common%20Reactions%20to%20Trauma_4.pdf

== Diseases / Erkrankungen / Choroby

* [line-through]#Bruxism#
* Snorring
* PTSD
* IBS: Irritable Bowel Syndrome
* Belching
* Flatulence
* Heartburn
* NCCP: Non-Cardiac Chest Pain
* Dry skin in cold
* Burnout / Adrenal Fatigue [not sure] (link:https://duckduckgo.com/?q=adrenal+fatigue+burnout&iax=images&ia=images[])
* Overeating

== Why did I create this?

Chcel som sa vyliečiť z tráviacich problémov. Bolestí žalúdka, nafukovania, únavy po jedle.

Doktori to vzdali. Skúšali všetko možné. Nakoniec mi povedali: "Nevieme liečiť niečo, čo nevieme ani diagnostikovať". "Tak dík." pomyslel som si a išiel som preč.

Bol som zúfalý a vyčerpaný z choroby. Lekári tiež. Tak som po dvoch rokoch prevzal zodpovednosť za svojou liečbu do vlastných rúk.

Do ďalších dvoch rokoch sa môj zdravotný stav výrazne zlepšil. Asi som mal šťastie. Ale liečba psychosomatickej choroby, syndrómu dráždivého čreva (IBS - Irritable Bowel Syndrome), je komplikovaná a zdĺhavá. A nie len vnútorné, ale aj vonkajšie prostredie, hrá rovnako významnú úlohu pri liečbe. Toto tvrdenie potvrdzuje aj vedecká disciplína *epigenetika*. Ak naozaj vonkajšie prostredie ovplyvňuje biológiu človeka, t. j. jeho epigenóm, potom dokážeme vytvoriť vzťah medzi spoločnosťou a zdravím človeka, a medzi telom a dušou človeka, jeho pocitmi, potrebami, zážitkami, vnímaním vonkajšieho prostredia.

Čo vytvára našu realitu?

* Výchova
* Vzdelanie
* Vonkajšie prostredie
** Médiá
** Spoločnosť
** Kultúra
** Inštitúcie
** Náboženstvo

A teraz, vďaka epigenetike vieme zmerať, od ako vonkajšie prostredie vplýva na zdravie človeka. Vieme vytvoriť spojenie medzi spoločenskými vplyvmi a biológiou človeka. link:???[(Peter Spork - Gesundheit is kein Zufall)], link:???[(Zitat  - Peter Spork - Gesundheit is kein Zufall - Verbindung zwischen Soziologie und Biologie)]

Chcel som si konečne začať užívať život, potom, čo som asi šesť krát vyhorel. Asi som vymyslel prevenciu proti vyhoreniu a zachovanie radosti zo života. Ale berte to s rezervou: žiadne, že buď 100% garancia spokojnosti, alebo vrátenie peniazí ;) Ale pomohlo mi to začať odznova. Postupne prekonávať depriesie. A menej sa nenávidieť za chyby :/ A pomaly sa liečiť z chorôb, keď lekári hovorili, že ma nevedia vyliečiť.

*I just want to be healthy and live well! Do I want so much?!link:https://www.fileformat.info/info/unicode/char/203d/index.htm[‽]*

*Why did I recreated everything to feel good again? Why isn't it here right from the beginning!?*

Lebo môžem byť neviemaký odborník, keď neviem vychádzať s ľuďmi.

To ma vždy bude vyrušovať pri učení sa čohokoľvek odborného.

Chcem sa cítiť dobre s druhými ľuďmi.

Odbornosť nie je všetko. Odbornosť je jedna časť.

Ďalšia časť je ľudskosť.

Ľudskosť rozvíjam empatiou.

Empatia mi pomáha spájať sa so sebou samým a s ostatnými ľuďmi a rozumieť dobrým dôvodom, pocitom a potrebám, prečo ľudia robia to, čo robia.

Empatia lieči rany na duši rýchlejšie a do väčšej hĺbky než psychoanalýza, pretože empatia sa zameriava na prítomnosť. Pri psychoanalýze sa rozpráva o minulosti, lenže rozprávanie o minulosti a jej analyzovanie spomaľuje liečbu a môže jej dokonca brániť. Psychoanalýza poskytuje skôr intelektuálne porozumenie než emocionálne liečenie: súcit - empatiu.

Empatia je súčasťou emocionálnej inteligencie.

Lenže väčšina škôl a väčšina pedagógov používa praktiky, ktoré bránia rozvoju empatie a emocionálnej inteligencie. Veď akoby aj mohli. Pedagógovia sa trápia, lebo oni sami nevedia veľa o emocionálnej inteligencii a jej dôležitosti, a aj väčšina školských inštitúcii je  navrhnutá tak, aby kládli väčší dôraz na výkon, výsledky, súťaživosť, povinnosť a poslušnosť, než na starostlivosť, ochotu, dobrovoľnosť, súcit a zodpovednosť.

A namiesto altruistických ľudí vychovávajú ľudí sebeckých. Lebo, čo sa asi študent naučí? *Že ostatní ľudia sú potencionálnou prekážkou k jeho/jej úspechu.* A, že *ja dokážem uspieť iba vtedy, keď druhí zlyhajú.* link:???[Alfie Kohn - OFJCC], link:???[Daniel Markovits - Excellence vs Superiority]

V takomto prostredí potom trpia nielen študenti, ale aj učitelia a vedenie. Podobne vo firmách, trpia zamestnanci aj menežéri, ktorí vyznávajú túto ideológiu.

Som presvedčený, že nízka úroveň emocionálnej inteligencie a hrozba násilím umožňuje, aby sa takýto systém udržal.

A chcem sa vedieť smiať na svojich chybách. Chcem sa učiť zo svojich chýb a prestať sa nenávidieť za to, že robím chyby.

Výrazne mi v tom pomohlo štúdium a tréning nenásilnej komunikácie. Začal som v auguste 2019 _(14.8.2019)_. Pokračujem až dodnes. Vždy, keď ju použijem, uľaví sa mi. Máloktorá technika, ktorú som kedy skúšal bola tak spoľahlivá, ako je táto. Nenásilná komunikácia zvyšuje moju emocionálnu inteligenciu, vnímavosť, duševný pokoj a rovnováhu. Dáva mi nádej, že veci môžu byť aj inak. Lepšie. Udržateľné. Prospešné pre všetkých. Nielen iba pre elitu.

== Notes

Emotional intelligence, empathy and the idea of communism look to me very similar +
*Emotional inteligence:* The ability to recognize and manage one's own emotions and emotions of other people. link:https://www.skillsyouneed.com/general/emotional-intelligence.html[EI - Source] +
*Empathy:* Awareness of the feelings and needs in myself and other people and being able to see things from the point of view of others. link:https://www.skillsyouneed.com/general/emotional-intelligence.html[Empathy - Source] +
*Communism:* From each according to their abilities to each according to their needs. link:https://en.wikipedia.org/wiki/From_each_according_to_his_ability,_to_each_according_to_his_needs#:~:text=%22From%20each%20according%20to%20his,of%20goods%2C%20capital%20and%20services.[Idea of communism - Source]

---

Stres nie je pocit. Stres je úsudok. +
... +
...


stres = napätie + bezmocnosť +
Stress = Anspannung + Machtlosigkeit +
stress = tension + powerlessness

---

*Paradox*: I'm ashamed when I speak to a girl, that I'm not good enough for her, and she's ashamed as well because she thinks she doesn't deserve love and is ashamed of her beauty.

---

* *The prayer of peace / Das Gebet der Ruhe / Modlitba pokoja* _(27.5.2019)_ +
  Pokoj sa rozlieva každou bunkou môjho tela, moju myseľ napĺňa sústredenie a moje telo dýcha uvoľnením. +
  Die Ruhe fließt durch jede Zelle meines Körpers, mein Geist erfüllt Konzentration und mein Körper atmet die Entspannung. +
  The calmness flows through every cell of my body, my mind fills concentration and my body breaths relaxation. +

---

stav horiacej zúrivosti ???

---

Čo je to _svedomie_ / Gewissen / conscience?

---

Čo si len ja počnem, +
čo si len ja počať mám, +
jablkový rezeň si ja na obed dám. +
Juchuuu!

---

_Sonntag 9.8.2020_ +
*Sladký život*

Budeme sa hladkať, škrabkať, +
objímať a bozkávať. +
Budeme si hryzkať do uška +
a šepkať sladké nezmysly. +
Dotýkať sa telami aj slovami.

Škrabkať sa vo vlasoch, +
štekliť sa po nohách, +
túliť sa pod perinou +
v bezpečí, dôvere a radosti. +

Ochutnám tvoje sladké pery, +
stisnem tvoj mäkký zadoček, +
nadýchnem sa tvojich vlasov, +
nežne ťa pohryzkám na krk +
poškrabkám ťa svojimi fúzikmi, +
ktoré si už šiesty týždeň pestujem.

Privinieš si moju hlavu na svoju hruď, +
a budem počúvať tlkot tvojho srdca +
vo vzrušujúcom očakávaní.

Stisneme si naše hrude +
v horúcom objatí, +
a budme tancovať +
ako zemiačiky +
vo vriacej vode +
pôžitku a vášne.

Unavíme sa +
budeme spotení a smrdieť. +
Potom zaspíme. +
Budeme slintať do vankúša, +
prdieť do periny, +
hádzať rukami a nohami, +
chrápať a škrípať zubami, +
keď budeme v hlbokom spánku. +

Bude sa nám snívať +
o jednorožcoch, +
v ružovom vesmíre, ktorí +
skáču po obláčikoch, +
grcajú dúhu, +
a prdia motýle. +

Jesť +
eko, bio, racio, +
raw, vegan, organic +
bezlaktózové a bezlepkové +
potraviny z dovozu. +
Budeme grgať po každom jedle. +
Ach, tá úľava.

Zostarneme mladí, +
a pôjdeme na predčasný dôchodok. +

A budeme mať popiči život :D Ej! Bardzo zajebisty!

---

*Chcieť môžeš.* Marshall Bertram Rosenberg - parody, but pretty devastating for me ... +
*Snívaj ďalej.* Doug Newburg - parody

---

Unterstützen Hausaufgaben für Punkte die Ausbrennung in den Studenten? +
Ich gehe aus meiner eigenen Erfahrung aus. In der Grundschule, am Gymnasium, an der Uni, ich lernte und arbeitete hart jeden Tag. Von Tag bis Nacht. Ich fühlte mich angespannt und erschöpft. Um die Anspannung zu entspannen, habe ich mich körperlich befriedigt und Computerspiele gespielt. Manchmal bis frühen Morgen über die ganze Nacht. Ich arbeitete, und arbeitete, und spielte, ... Und dann wurde ich krank. Ich unterband mich von meinen Gefühlen und Bedürfnissen. Ich konzentrierte mich auf die Leistung, anstatt auf den Genuss und Freude am Lernen. Das TODO-Liste war mir wichtiger als meine eigene Gesundheit.s

---

Ich will es beschleunigen. Ich möchte gewaltfreie Erziehung, Kommunikation, Ausbildung und Management erleben. Ich will gewaltfrei leben.

---

https://www.rtvs.sk/televizia/archiv/13986/240457#973

---

Why the life is not fair? +
Because the world is driven by capitalism which supports meritocracy. Because capitalism isn't fair (by design). link:https://veganvanguardpodcast.com/how-competition-dominates-our-lives/[2. The Trope of “Competition” Dominates Our Lives: 2:37-3:22]

---

No one deserves anything. But everybody needs something. Everybody needs the same things. What differs immensely is the strategies in which we fulfil our needs.

---

I'm not a thing, agent, factor of production, human capital, commodity, number, letter or anything. I am a human that has feelings that I want to express and needs that I want to fulfill.

---

Entfremdung ist unvermeidbar im Kapitalismus. Kapitalismus kann nicht ohne Entfremdung funktionieren. Entfremdung is ein Baustein vom Kapitalismus. Ausbrennung ist das Ergebnis von der Entfremdung. Vielleicht, wenn ich einen Weg finde, wie ich mich mit der Entfremdung auseinandersetzen kann, kann ich die Ausbrennung komplett vermeiden... [Thx Marx für die Inspiration] +
Was ist der Gegenteil von Entfremdung? Verbindung. Verbindung is ein Bedürfnis. Wie kann ich das Bedürfnis nach Verbindung erfüllen? [Thx Marshall Rosenberg für die Inspiration]

---

Every feeling manifests itself in the body. +
Jedes Gefühl offenbart sich im Körper. +
Každý pocit sa prejaví v tele.

Schuld, Scham, Verletzung spüre ich im Herz. +
Angst, Überraschung, Schock, Sorgen spüre ich im Magen und Darm. +
Machlosigkeit, Hilflosigkeit, Verwirrung spüre ich im Kopf und in Augen.
Müdigkeit, Erschöpfung spüre ich im ganzen Körper.
Anspannung, Verwirrung spüre ich als ein Druck in der Ader auf der inneren Seite des linken Oberarm und als Herzschlagen.

---

Describe your level of suffering: +
Imagine that somebody link:https://cdn-grid.fotosearch.com/CSP/CSP040/heart-pierced-by-knife-clip-art__k65758817.jpg[stabs you in the heart with a knife]. Then turns the knife inside. Then the person pulls off the knife, and stabs you in the somach. Two times. Then the person grabs your neck and smashes your head to a wall. That's the pain I'm feeling.

---

Patriarchy and prostitution, objectification of women (and other people - as subordinate)

---

Porn = Patriarchy + Objectification of Women (e.g. Prostitution)

---

Nicht das verhalten jemanden Anderen velretzt mich, sondern meine unerfüllten Bedurfnisse. Die unerfüllten Bedürfnisse haben wirklich eine riesengroße Kraft. Diese Kraft spüre ich im Bauch, im Magen, im Herz und im Kopf. Dann beeinflüsst sie meinen ganzen Körper.

---

Die Leute sind nicht schlecht. Sie haben nur eine andere Erziehung und Ausbildung bekommen. Mit *schlecht* meine ich dass sie auf einer Weise benehmen, mit der ich nicht einverstanden bin. Sie waren nur so erzogen und ausgebildet.

---

There is no such thing as *_work-life balance_* [under capitalism]. Because the work interferes with my life. +
There is no such thing as *_equality of opportunity_* [under meritocracy - because talent and the quality of the education is positively corelated with wealth: the children nurtured in elite families have more opportunities and freedom of opportunity than children in poor families, because opportunities under capitalism are bound to the exchange value link:https://en.wikipedia.org/wiki/Meritocracy#20th_century_to_today[Wiki: Meritocracy - Today]]. And the reason, why the poorer people are failing is that they don't measure up link:[LSE Events | The Meritocracy Trap: ???42:00-42:00].

---

The children are not children. They are short adults. +
Kinder sind keine Kinder. Sie sind niedrige Erwachsene. +
Deti nie sú deti. Sú nízki dospelí.

---

Be innovative! Think different! Think out of the box! Ah... +
NMBBS - Neoliberal Managerial Buzzword BullShit +
So you say innovative, huh? What about an innovation called *Democratic Confederalism*? *_Socialism with Direct and Representative Democracy at the same time_*. So innovative, isn't it? :/

---

Coronavirus pandemic heals the earth: (maybe it is a hope for a sustainable future) +
https://www.cnbc.com/2020/03/18/photos-water-in-venice-italys-canals-clear-amid-covid-19-lockdown.html +
https://www.cnbc.com/2020/03/02/nasa-images-chinas-air-pollution-decreased-amid-coronavirus-measures.html +
link:https://sci-hub.st/10.1038/s41558-020-0797-x[Temporary reduction in daily global CO~2~ emissions during the COVID-19 forced confinement]

---

Was ich sehe, ist, dass Diktatur, Totalität, Kapitalismus und andere Formen der Erpressung sind sehr intolerant gegen Zärtlichkeit, Empathie, Mitgefühl, Einfühlsamkeit, Verständnis, Pflege, Genuss, Kommunität, Entgegenkommen, Bereitschaft, Sicherheit, Geborgenheit, Mut, Alternative, eigene/intrinsische Motivation, Zusammenarberit (keine Wettbewerbsfähigkeit), Verletzlichkeit. Ich fange an zu glauben, dass wir entweder eine gewaltfreie Zukunft haben, oder keine Zukunft haben. Und wenn eine Revolution entsteht, ich denke, dass die gewaltfreie Möglichkeit die einzige langfristig nachhaltige Möglichkeit ist. Und damit die Revolution gewaltfrei war, wir brauchen lernen, uns um unsere Erpresser zu kümmern. [Und dafür brauchen wir selbst, uns Empathie zu geben, weil wir nicht uns in jemanden hineinfühlen können, wenn wir nicht selbst genug Empathie haben.] +
link:https://www.youtube.com/watch?v=mErG7mSzwkc[Miki Kashtan - Social Change Series – Liberation in Three Chapters - 1: 42:37-42:54 (43:14)] +
link:https://www.youtube.com/watch?v=Qvmqeeme42M&feature=youtu.be&t=226[Miki Kashtan: Exiting the Either/Or Trap - Beyond Consensus vs. Command and Control: 3:46-4:14 (5:05)]

---

Gestapo-Pädagogik (feindliches Bild) =

* Gefühle: Beunruhigung, Enttäuschung, Ekel
* Unerfüllte Bedürfnisse: Gesundheit, Ehre, Würde, Pflege, Geduldigkeit, Empathie, Verständnis, 

---

Capitalism, Authoritharianism, Dictatorship =

* freedom to overwork yourself to death
* freedom to suffer
* freedom to compete into exhaustion (on the "free market")
* freedom to starve
* freedom to beg
* freedom to use money for arbitrary things
* freedom to oppress others
* freedom to exploit others
* freedom to profit from acts of violence (war)
* freedom to profit from natural disasters
* freedom to profit from diseases
* freedom to profit from weapons
* freedom to profit from drugs
* freedom to profit from organized criminality
* freedom to profit from prostitution
* freedom to profit from tobacco
* freedom to gamble
* freedom to bet

---

Wie kann sich ein Staat als "entwickelt" nennen, wenn er Leute hat, die obdachlos sind? +
Wie trauen wir uns eine "entwickelete" Gesellschaft nennen, wenn wir "Neglected Tropical Diseases" / Vernachlässigte (Tropen)Krankheiten in die Welt immer noch haben?

---

One Dollar - One Vote Rule +
the more money one has, the more political power one has in a market economy and the _"free market"_.

---

waiting for UBI - Universal Basic Income...

---

*Hobbesian model:* people are greedy and selfish and therefore must have a tyran that will oppress them to discipline them. [What a myth. Protective, not punitive use of force. Empathy and cooperation, not selfishness and competition]

---

Ich sehe Geld als ein Mittel der Erpressung (oppression). Am besten ist das auf einem Lohn (debt), einem Kredit zu sehen. Das Kredit versklavt die Menschen ihrer Arbeit. Wenn sie arbeiten, leiden sie, weil sie sich von ihr allmählich entfremnden. Wenn sie nicht arbeiten, leiden sie, weil sie ihre Bedürfnisse nicht mehr vollständig erfüllen können, weil Überleben hängt vom Einkommen ab. Wohnung, Essen, Hygiene, Gesundheit.

*Capitalism is a system that uses money to get more money.* [David Graeber - Debt: The first 5000 years], link:https://text.npr.org/s.php?sId=908456873[Eula Biss - Having and Being Had]

---

Education is not an obligation, contest, competition or transaction. Education is a gift. Just like all other needs.

---

What happens if I don't do it?  Question to help moving from guilt, shame and obedience to responsibility and honesty +
Was passiert, wenn ich das nicht mache? Eine Frage, die hilft, sich von Schuld, Scham und Gehorsamkeit zur Verantwortung und Ehrlichkeit bewegen.

---

Religious [Psychological] Violence

---

Doing thing for profit [or for any other pseudo-need] is a moraly bankrupt idea. +
Sachen für Profit zu tun ist eine moralisch pleite Idee.
Robiť veci pre zisk je morálne zbankrotovaná myšlienka.

---

Impostor syndrome, capitalism and Peter principle

* One of the things that I didn't want to have happen to me as I entered this new life and lifestyle was I didn't want to begin to think that I had what I had because I'd worked hard, which is one of the patterns of thought very common to upper middle class. I don't believe that I got what I got because I worked hard. I believe that I got what I got *because the [economic] system [of capitalism] favors me* in a number of different ways - one, because I'm white, but also because I started out middle-class. And I think that it's uncomfortable for people who start out with more to be reminded of that. +
So - and I do think that this is damaging in so many ways. The implication is that people who don't have enough have just not worked hard enough, and that's damaging to people who are working extremely hard and still don't have enough because they're being underpaid [or have grown up and educated in different conditions]. But it's also damaging to relationships between people who have more and people who have less if there is this implication hovering in the air that you could have as much as I have if only you just worked a little harder. [Eula Biss] +
link:https://text.npr.org/s.php?sId=908456873['Having And Being Had': A Book That Answers Your Questions On Capitalism]

* ...impostor syndrome can apply to anyone “who isn’t able to internalize and own their successes... [Audrey Ervin] +
link:https://time.com/5312483/how-to-deal-with-impostor-syndrome/[Impostor syndrome]

* Peter principle: Each person in a hierarchy accompanies a position, for which is not sufficiently qualified. Each person in a hierarchy has a position that corresponds to the level of his/her incompetence (Peter's Plateau).

* How they get together: In such case, the person might feel like an impostor because of the lack of skills, to perform or enjoy the job. Because capitalism is an hierarchical system, it can apply to anyone.

---

What would the others think about me?

* unfulfilled needs: spontaneity, authenticity

---

I would like you to see that there are multiple way of doing things.

---

Minimalism doesn’t mean to have as little things as possible, but to have such amount of particular kind of things that one necessarily needs and are important for him/her.
Minimalismus bedeutet nicht so wenig Sachen wie möglich haben, sondern so viel solchen Sachen haben, die er/sie notwendig braucht, und sind wichtig für ihn/sie.
Minimalizmus neznamená mať čo najmenej vecí, ale mať iba toľko takých vecí, ktoré nevyhnutne potrebuje a zaleží mu/jej na nich. (me)

---

At shopping I ask myself: "Will this thing be useful to me?" [What of my needs will this thing fulfil?]
Beim Einkaufen frage ich mich: "Wird dieses Ding nützlich für mich sein?" [Welche meiner Bedürfnisse erfüllt dieses Ding?]
Pri nakupovani sa pýtam: "Bude táto vec pre mňa užitočná?" [Aké z mojich potrieb bude táto vec napĺňať?]
The Minimalists - Youtube Podcast

--

Ako vyhadzujem veci - najprv odlozim nepotrebnu vec bokom [na odložisko] na chvilu (par dni, tyzdnov, mesiacov, rokov). Pokial ju nebudem potrebovat pocas toho ako bude odlozena, vyhodim ju.

---

What capitalism and cancer have in common? +
Both want to continuously grow. Maybe we have a sick economic system...

---


