= Life

- Punishment vs Discipline, Care and Reason - Ruff Lott
- Punishment and Rewards vs Care and Reason - Alfie Kohn, Samuel P. Oliner + Pearl M. Oliner [Altruistic Personality + Samuel Oliner Testimony], Miki Kashtan [Exiting the Either/Or Trap - 17th minute]
- Production and Comsumption vs Care and Freedom - David Graeber [O Bullsh*t Jobs - 49:18-49:44]
- Gratitude vs Reward, Praise and Compliments- M. B. Rosenberg, Alfie Kohn, Peter Gray
- Criticism, Praise and Compliments vs Observation, Feeling, Need and Request - M. B. Rosenberg
- Criticism and Blame vs Honesty - M. B. Rosenberg [Making life wonderful - part 1/4 - somewhere at the beginning]
- Feedback vs Evaluation and Judgement - Alfie Kohn
- Request vs Demand
- Power over vs Power with - Mary Parker Follett, Miki Kashtan [Exiting the Either/Or Trap - 30th minute], M. B. Rosenberg, Alfie Kohn, Mark Shepard
- Authority based on 'power over' model vs Authority based on 'power with' model - M. B Rosenberg [interview with paula gloria]
- Obedience vs Responsibility - M. B. Rosenberg-Workshop Denmark
- Obedience vs Respect
- Fear vs Respect
- Empathy, Power with and Respect vs Obedience - M. B. Rosenberg [NVC Workshop Portland OR - 1:34:41]
- Intrinsic motivation vs Extrinsic motivation vs Internal motivation - Alfie Kohn [OFJCC Overemphasizing achievement]
- Excellence vs Superiority - Daniel Markovits-The Meritocracy Trap (e.g. Is Meritocracy a Sham - 19min video)
- Duty and Obligation vs Freedom and Choice - Maria Montessori, Peter Gray, Alfie Kohn, M. B. Rosenberg
- We have been taught: "There is a right and a good way to do everything. ..." - Portland Workshop 2004 Rosenberg - 1:59:58-2:00:40
- As much as possible in as little time as possible vs As best as possible in whatever time necessary - Manfred Max-Neef - The Benefits of a Slow Life - 1:38-1:51
- Retributive justice vs Restorative Justice - Howard Zehr, M. B. Rosenberg, Miki Kashtan
- Oikonomia vs Chrematistike - Aristoteles, Manfred Max-Neef
- Agriculture vs Permaculture - Mark Shepard
- Efficiency vs Sufficiency and Well-being - Manfred Max-Neef[Collision course - article]
- Rule and Dogma - M. B. Rosenberg [Consentual rules: Resolving conflicts with children workshop]
- Education vs Indoctrination - Manfred Max-Neef, Peter Gray
- School vs Education - Peter Gray
- Codependency vs Interdependency
- Process vs Product - Rachel Rainbolt, Peter Gray
- Empathy vs Sympathy - Yoram Mosenzon

Culturally learned beliefs:
- spare the rod, spoil the child - Proverbs 13:24
- no pain, no gain
- Čím väčším peklom si prejdeš, tým silnejší z toho výjdeš. Ak z toho výjdeš. - Jaroslav Slávik, Československo má talent

Quotes

"Can you live with it?" - Miki Kashtan [Maximizing Willingness - 1:02:10-1:02:16]

the montessori method:
- 4:56-6:23
- 8:08-8:17
- 10:45-11:20
- associate object, word and stimuli
